openapi: 3.0.3
info:
  title: probe
  version: 1.0.0
paths:
  /pets:
    get:
      operationId: getPet
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - $ref: "#/components/schemas/Pet"
components:
  schemas:
    Pet:
      oneOf:
        - $ref: "#/components/schemas/Cat"
        - $ref: "#/components/schemas/Dog"
      discriminator:
        propertyName: kind
        mapping:
          cat: "#/components/schemas/Kitten"
          dog: "#/components/schemas/Puppy"
    Cat:
      type: object
      properties:
        kind:
          type: string
        name:
          type: string
    Dog:
      type: object
      properties:
        kind:
          type: string
        name:
          type: string
