openapi: 3.0.3
info:
  title: probe
  version: 1.0.0
paths:
  /files:
    post:
      operationId: postFiles
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                link:
                  type: object
                  properties:
                    url: {type: string}
            encoding:
              link:
                style: form
                explode: true
      responses:
        '204': {description: No Content}
