

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .link import Link


class Ok41(UniversalBaseModel):
    id: str
    order_id: typing_extensions.Annotated[str, FieldMetadata(alias="orderId"), pydantic.Field(alias="orderId")]
    person_id: typing_extensions.Annotated[str, FieldMetadata(alias="personId"), pydantic.Field(alias="personId")]
    provider_id: typing_extensions.Annotated[str, FieldMetadata(alias="providerId"), pydantic.Field(alias="providerId")]
    author_name: typing_extensions.Annotated[str, FieldMetadata(alias="authorName"), pydantic.Field(alias="authorName")]
    author_display_name: typing_extensions.Annotated[
        str, FieldMetadata(alias="authorDisplayName"), pydantic.Field(alias="authorDisplayName")
    ]
    user_name: typing_extensions.Annotated[str, FieldMetadata(alias="userName"), pydantic.Field(alias="userName")]
    is_delegate: typing_extensions.Annotated[str, FieldMetadata(alias="isDelegate"), pydantic.Field(alias="isDelegate")]
    create_timestamp: typing_extensions.Annotated[
        str, FieldMetadata(alias="createTimestamp"), pydantic.Field(alias="createTimestamp")
    ]
    create_timestamp_timezone: typing_extensions.Annotated[
        str, FieldMetadata(alias="createTimestampTimezone"), pydantic.Field(alias="createTimestampTimezone")
    ]
    comment: str
    type: str
    generated_by: typing_extensions.Annotated[
        str, FieldMetadata(alias="generatedBy"), pydantic.Field(alias="generatedBy")
    ]
    is_auto_generated: typing_extensions.Annotated[
        str, FieldMetadata(alias="isAutoGenerated"), pydantic.Field(alias="isAutoGenerated")
    ]
    links: typing_extensions.Annotated[typing.List[Link], FieldMetadata(alias="_links"), pydantic.Field(alias="_links")]

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
