openapi: 3.0.3
info:
  title: probe
  version: 1.0.0
security:
  - session: []
paths:
  /probe:
    get:
      operationId: probe
      responses:
        '204': {description: No Content}
components:
  securitySchemes:
    session:
      type: apiKey
      in: cookie
      name: SESSION
