openapi: 3.0.3
info:
  title: probe
  version: 1.0.0
paths:
  /contacts:
    post:
      operationId: createContact
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                attributes: {$ref: '#/components/schemas/Container/$defs/id'}
      responses:
        '204': {description: No Content}
components:
  schemas:
    Container:
      type: object
      $defs:
        id: {type: string}
