openapi: 3.0.3
info:
  title: probe
  version: 1.0.0
paths:
  /probe:
    get:
      operationId: getProbe
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Result'
components:
  schemas:
    Result:
      type: object
      properties:
        /:
          type: string
