openapi: 3.0.3
info: {title: Probe, version: '1'}
paths:
  /probe:
    get:
      parameters:
        - name: sort
          in: query
          schema: {type: string, enum: [createdAt, -createdAt], default: -createdAt}
      operationId: probe
      responses:
        '204': {description: OK}
