openapi: 3.0.3
info: {title: Probe, version: '1'}
paths:
  /probe:
    get:
      parameters:
        - name: categories
          in: query
          schema: {type: array, items: {type: string, enum: [first, second]}, default: third}
      operationId: probe
      responses:
        '204': {description: OK}
