openapi: 3.0.3
info: {title: Probe, version: '1'}
paths:
  /probe:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {type: string, enum: [createdAt, -createdAt], default: -createdAt}
