{
  "openapi": "3.0.3",
  "info": {
    "title": "probe",
    "version": "1.0.0"
  },
  "paths": {
    "/accounts": {
      "get": {
        "operationId": "listAccounts",
        "parameters": [
          {
            "name": "account_id",
            "in": "query",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "accountId",
            "in": "query",
            "schema": {
              "type": "string"
            },
            "x-fern-parameter-name": "otherAccount"
          }
        ],
        "responses": {
          "204": {
            "description": "No Content"
          }
        }
      }
    }
  }
}
