openapi: 3.0.3
info:
  title: probe
  version: 1.0.0
paths:
  /collections:
    get:
      operationId: getCollections
      x-fern-examples:
      - query-parameters:
          g: x
      parameters:
      - name: f
        in: query
        required: true
        schema:
          type: string
        x-fern-parameter-name: g
      responses:
        '204':
          description: No Content
