

import typing

import pydantic
from ...core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .patch_project_automation_config_batch_size_credentials_type import (
    PatchProjectAutomationConfigBatchSizeCredentialsType,
)


class PatchProjectAutomationConfigBatchSizeCredentials(UniversalBaseModel):
    type: PatchProjectAutomationConfigBatchSizeCredentialsType
    role_arn: str = pydantic.Field()
    """
    The ARN of the IAM role to use
    """

    external_id: str = pydantic.Field()
    """
    The automation-specific external id component (auto-generated by default)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
