//! `enum-type: literals` against Fern's literal-enum goldens.
//!
//! A targeted set of registered corpora ([`LITERAL_GOLDENS`]), together covering
//! every enum shape crozier generates, also carries `expected-literals/`: Fern's
//! output for the same spec and settings with `pydantic_config.enum_type` unset
//! (fern-python-sdk's `literals` default), produced by
//! `scripts/fern-literals-goldens.sh` exactly as `expected/` is and committed as
//! an overlay of it — only the files whose bytes differ, plus a manifest naming
//! the files Fern does not emit in that mode. The gate rebuilds the full
//! literals tree and byte-compares crozier's `--enum-type literals` output to it
//! with the corpus's own residuals, the same comparison `assert_corpus_matches`
//! makes against `expected/`.

use std::path::Path;

use super::{
    assert_generated_tree_matches, corpus_has_comparable_golden, fixture_dir, generate_corpus_with,
    registered_diff_corpora, walk_files, Corpus,
};

/// The test that byte-compares every literals golden, listed in
/// `just test-corpus-match` like each corpus's own test.
pub(super) const CORPUS_TEST: &str = "literals_match_fern_output_for_targeted_corpora";

/// The corpora held to a literals golden, each for the enum shapes it reaches:
/// - `exhaustive`: named component enums, inline enums inside union variants,
///   an enum request body and response, and the dropped `core/enum.py`;
/// - `enum-name-sanitization`: values that need sanitizing into member names
///   (`"0: Active"`) and an inline query-parameter enum of numeric strings;
/// - `enum-query-param`: an inline query-parameter enum on a nested resource;
/// - `enum-receiver-collision`: members whose names collide with `visit`'s
///   receiver;
/// - `openfigi.com`: inline property enums, optional and `nullable` ones, and a
///   path-parameter enum, in a real corpus document.
const LITERAL_GOLDENS: &[&str] = &[
    "exhaustive",
    "enum-name-sanitization",
    "enum-query-param",
    "enum-receiver-collision",
    "openfigi.com",
];

/// A corpus's literals golden overlay directory, beside its `expected/`.
const OVERLAY: &str = "expected-literals";
/// The overlay's manifest: provenance plus the `expected/` files Fern omits.
const MANIFEST: &str = ".crozier-literals-overlay.json";

/// A validated overlay manifest.
#[derive(Debug)]
struct Overlay {
    /// `expected/` files Fern does not emit with literal enums.
    removed: Vec<String>,
}

/// Read and validate `api`'s overlay manifest; `None` when it has no overlay.
/// The overlay is only meaningful over the golden it was reduced against, so its
/// recorded Fern versions must be the ones `expected/`'s provenance records.
fn read_overlay(api: &str) -> Result<Option<Overlay>, String> {
    let root = fixture_dir(api);
    let overlay = root.join(OVERLAY);
    if !overlay.exists() {
        return Ok(None);
    }
    let path = overlay.join(MANIFEST);
    let text = std::fs::read_to_string(&path)
        .map_err(|error| format!("{api}: cannot read {}: {error}", path.display()))?;
    let manifest: serde_json::Value = serde_json::from_str(&text)
        .map_err(|error| format!("{api}: invalid {MANIFEST}: {error}"))?;
    if manifest["enum_type"] != "literals" || manifest["base"] != "expected" {
        return Err(format!(
            "{api}: {MANIFEST} must record enum_type `literals` over base `expected`"
        ));
    }
    let base_provenance = root.join("expected/.crozier-fern-golden.json");
    if let Ok(text) = std::fs::read_to_string(&base_provenance) {
        let base: serde_json::Value = serde_json::from_str(&text)
            .map_err(|error| format!("{api}: invalid expected/ provenance: {error}"))?;
        if manifest["fern_python_sdk_version"] != base["fern_python_sdk_version"] {
            return Err(format!(
                "{api}: the literals golden was generated by fern-python-sdk {} but expected/ by {}; \
                 regenerate it with scripts/fern-literals-goldens.sh {api}",
                manifest["fern_python_sdk_version"], base["fern_python_sdk_version"]
            ));
        }
    }
    let removed: Vec<String> = manifest["removed"]
        .as_array()
        .ok_or_else(|| format!("{api}: {MANIFEST} has no `removed` list"))?
        .iter()
        .map(|entry| {
            entry
                .as_str()
                .map(str::to_string)
                .ok_or_else(|| format!("{api}: {MANIFEST} `removed` holds a non-string"))
        })
        .collect::<Result<_, _>>()?;
    for rel in &removed {
        if !root.join("expected").join(rel).is_file() {
            return Err(format!(
                "{api}: {MANIFEST} removes {rel}, which expected/ does not have"
            ));
        }
    }
    Ok(Some(Overlay { removed }))
}

/// The full literals golden of `api`: `expected/` minus the removed files, with
/// every overlay file laid over it.
fn materialize(api: &str, overlay: &Overlay) -> tempfile::TempDir {
    let tree = tempfile::tempdir().expect("literals golden tempdir");
    let copy = |from: &Path, rel: &str| {
        let to = tree.path().join(rel);
        std::fs::create_dir_all(to.parent().expect("a file has a parent")).expect("mkdir");
        std::fs::copy(from.join(rel), &to).expect("copy golden file");
    };
    let base = fixture_dir(api).join("expected");
    for rel in walk_files(&base) {
        if !overlay.removed.contains(&rel) {
            copy(&base, &rel);
        }
    }
    let layer = fixture_dir(api).join(OVERLAY);
    for rel in walk_files(&layer) {
        if rel != MANIFEST {
            copy(&layer, &rel);
        }
    }
    tree
}

/// The registered corpora with a comparable `expected/` golden.
fn comparable_corpora() -> Vec<&'static Corpus> {
    registered_diff_corpora()
        .into_iter()
        .filter(|corpus| {
            corpus_has_comparable_golden(corpus, &fixture_dir(corpus.api).join("expected"))
                .unwrap_or_else(|error| panic!("{}: {error}", corpus.api))
        })
        .collect()
}

/// The targeted corpora with their validated overlays.
fn literal_corpora() -> Vec<(&'static Corpus, Overlay)> {
    let corpora = comparable_corpora();
    LITERAL_GOLDENS
        .iter()
        .map(|api| {
            let corpus = corpora
                .iter()
                .find(|corpus| corpus.api == *api)
                .unwrap_or_else(|| {
                    panic!(
                        "{api}: listed in LITERAL_GOLDENS but no registered corpus with a golden"
                    )
                });
            let overlay = read_overlay(api)
                .unwrap_or_else(|error| panic!("{error}"))
                .unwrap_or_else(|| {
                    panic!("{api}: has no {OVERLAY}/; run scripts/fern-literals-goldens.sh {api}")
                });
            (*corpus, overlay)
        })
        .collect()
}

/// The literals gate covers exactly [`LITERAL_GOLDENS`]: each is a registered
/// corpus with a valid overlay, and no overlay sits outside the list, where no
/// test would read it.
#[test]
fn literal_goldens_are_exactly_the_targeted_set() {
    assert_eq!(literal_corpora().len(), LITERAL_GOLDENS.len());
    let fixtures = Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures");
    let mut on_disk: Vec<String> = std::fs::read_dir(&fixtures)
        .expect("read tests/fixtures")
        .map(|entry| {
            entry
                .expect("fixture entry")
                .file_name()
                .to_string_lossy()
                .into_owned()
        })
        .filter(|name| fixtures.join(name).join(OVERLAY).exists())
        .collect();
    on_disk.sort();
    let mut listed: Vec<String> = LITERAL_GOLDENS
        .iter()
        .map(|api| (*api).to_string())
        .collect();
    listed.sort();
    assert_eq!(
        on_disk, listed,
        "a fixture's {OVERLAY}/ is not in LITERAL_GOLDENS, or a listed one is missing"
    );
}

/// The literals golden is `expected/` minus the manifest's removed files, with the
/// overlay laid over it: Fern's literal enum modules replace the classes, and
/// every file the overlay does not carry is `expected/`'s own.
#[test]
fn the_literals_golden_is_expected_minus_removed_plus_overlay() {
    let api = "exhaustive";
    let overlay = read_overlay(api)
        .expect("valid exhaustive overlay")
        .expect("exhaustive has an overlay");
    assert_eq!(overlay.removed, ["src/fern/core/enum.py"]);
    let tree = materialize(api, &overlay);
    assert!(!tree.path().join("src/fern/core/enum.py").exists());
    assert!(!tree.path().join(MANIFEST).exists());
    let weather =
        std::fs::read_to_string(tree.path().join("src/fern/types/types_weather_report.py"))
            .expect("overlaid enum module");
    assert!(
        weather.contains(
            "typing.Literal[\"SUNNY\", \"CLOUDY\", \"RAINING\", \"SNOWING\"], typing.Any"
        ),
        "{weather}"
    );
    // Unchanged files come from expected/ untouched.
    assert_eq!(
        std::fs::read(tree.path().join("pyproject.toml")).unwrap(),
        std::fs::read(fixture_dir(api).join("expected/pyproject.toml")).unwrap()
    );
}

/// crozier's `--enum-type literals` output reproduces Fern's literal-enum golden
/// byte-for-byte (under the shared parity rules) for every targeted corpus.
/// Corpora run concurrently, and every failure is reported, not only the first.
#[test]
fn literals_match_fern_output_for_targeted_corpora() {
    let corpora = literal_corpora();
    assert!(!corpora.is_empty(), "no corpus carries a literals golden");
    let workers = std::thread::available_parallelism().map_or(2, |n| n.get().div_ceil(2));
    let next = std::sync::atomic::AtomicUsize::new(0);
    let failures = std::sync::Mutex::new(Vec::new());
    std::thread::scope(|scope| {
        for _ in 0..workers {
            scope.spawn(|| loop {
                let index = next.fetch_add(1, std::sync::atomic::Ordering::Relaxed);
                let Some((corpus, overlay)) = corpora.get(index) else {
                    break;
                };
                let outcome = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                    let golden = materialize(corpus.api, overlay);
                    let out = generate_corpus_with(corpus, &["--enum-type", "literals"]);
                    assert_generated_tree_matches(corpus, golden.path(), out.path());
                }));
                if let Err(panic) = outcome {
                    let message = panic
                        .downcast_ref::<String>()
                        .cloned()
                        .or_else(|| panic.downcast_ref::<&str>().map(|s| (*s).to_string()))
                        .unwrap_or_default();
                    failures
                        .lock()
                        .expect("failure list")
                        .push(format!("{}: {message}", corpus.api));
                }
            });
        }
    });
    let failures = failures.into_inner().expect("failure list");
    assert!(
        failures.is_empty(),
        "{} of {} literals corpora diverge from Fern:\n{}",
        failures.len(),
        corpora.len(),
        failures.join("\n\n")
    );
}

/// One string enum, reached through a model field and an operation header.
pub(super) const ENUM_SPEC: &str = "openapi: 3.0.0
info:
  title: Pets
paths:
  /pets:
    get:
      operationId: getPet
      tags: [Pets]
      parameters:
        - name: X-Mode
          in: header
          required: true
          schema: { type: string, enum: [fast, slow] }
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: { $ref: '#/components/schemas/Pet' }
components:
  schemas:
    Status:
      type: string
      enum: [active, inactive]
    Pet:
      type: object
      required: [status]
      properties:
        status: { $ref: '#/components/schemas/Status' }
";

/// `crozier config`'s `enum-type` row for the python generator in `dir`:
/// `(value, source)`.
fn enum_type_row(dir: &Path, env: &[(&str, &str)]) -> (String, String) {
    let mut command = super::crozier_clean_env();
    command.current_dir(dir).arg("config");
    for (name, value) in env {
        command.env(name, value);
    }
    let out = command.output().expect("run crozier config");
    let stdout = String::from_utf8(out.stdout).expect("utf-8 stdout");
    assert!(out.status.success(), "{stdout}");
    super::config_rows(&stdout, "python")
        .into_iter()
        .find(|(field, _, _)| field == "enum-type")
        .map(|(_, value, source)| (value, source))
        .unwrap_or_else(|| panic!("`crozier config` printed no enum-type row:\n{stdout}"))
}

/// Which enum shape the SDK generated under `out` has, asserting every file the
/// setting decides agrees on it: the enum module, the `core/enum.py` runtime the
/// classes need, the header's serialization and the worked example.
fn written_enum_type(out: &Path) -> &'static str {
    let pkg = out.join("src/pets");
    let read = |rel: &str| std::fs::read_to_string(pkg.join(rel)).expect(rel);
    let status = read("types/status.py");
    let raw = read("pets/raw_client.py");
    let reference = std::fs::read_to_string(out.join("reference.md")).expect("reference.md");
    if status
        .contains("Status = typing.Union[typing.Literal[\"active\", \"inactive\"], typing.Any]")
    {
        assert!(
            !pkg.join("core/enum.py").exists(),
            "literals ship no StrEnum base"
        );
        assert!(
            raw.contains("\"X-Mode\": str(mode) if mode is not None else None"),
            "{raw}"
        );
        assert!(reference.contains("mode=\"fast\""), "{reference}");
        "literals"
    } else {
        assert!(status.contains("class Status(enum.StrEnum):"), "{status}");
        assert!(pkg.join("core/enum.py").is_file());
        assert!(
            raw.contains("\"X-Mode\": mode.value if mode is not None else None"),
            "{raw}"
        );
        assert!(
            reference.contains("mode=GetPetRequestXMode.FAST"),
            "{reference}"
        );
        "python-enums"
    }
}

/// `enum-type` resolves CLI > `CROZIER_ENUM_TYPE` > `generators.<name>` > the
/// built-in `python-enums`, like every Python-generator setting; `crozier config`
/// names the layer that won; it has no shared top-level form; and a bad value is
/// refused before anything is written.
#[test]
fn enum_type_resolves_through_every_layer_through_the_binary() {
    let dir = tempfile::tempdir().expect("tempdir");
    std::fs::write(dir.path().join("api.yml"), ENUM_SPEC).unwrap();
    let config = dir.path().join("crozier.yml");
    let pair = |value: &str, source: &str| (value.to_string(), source.to_string());
    let generate = |env: &[(&str, &str)], args: &[&str], output: &str| {
        let mut command = super::crozier_clean_env();
        command.current_dir(dir.path());
        for (name, value) in env {
            command.env(name, value);
        }
        command
            .args(["generate", "python", "--output", output])
            .args(args)
            .assert()
            .success();
        written_enum_type(&dir.path().join(output))
    };

    // No layer: the built-in python-enums, unchanged.
    std::fs::write(
        &config,
        "spec: ./api.yml\ngenerators:\n  python:\n    package-name: pets\n",
    )
    .unwrap();
    assert_eq!(
        enum_type_row(dir.path(), &[]),
        pair("python-enums", "default")
    );
    assert_eq!(generate(&[], &[], "default"), "python-enums");

    // The generator's own entry.
    std::fs::write(
        &config,
        "spec: ./api.yml\ngenerators:\n  python:\n    package-name: pets\n    enum-type: literals\n",
    )
    .unwrap();
    assert_eq!(
        enum_type_row(dir.path(), &[]),
        pair("literals", "generator")
    );
    assert_eq!(generate(&[], &[], "generator"), "literals");

    // The environment beats the config file; the flag beats the environment.
    let env = [("CROZIER_ENUM_TYPE", "python-enums")];
    assert_eq!(enum_type_row(dir.path(), &env), pair("python-enums", "env"));
    assert_eq!(generate(&env, &[], "env"), "python-enums");
    assert_eq!(
        generate(&env, &["--enum-type", "literals"], "flag"),
        "literals"
    );

    // Python-generator-specific: a shared top-level value is a config error.
    std::fs::write(&config, "spec: ./api.yml\nenum-type: literals\n").unwrap();
    super::crozier_clean_env()
        .current_dir(dir.path())
        .arg("config")
        .assert()
        .failure()
        .stderr(predicates::str::contains("enum-type"));

    // A bad value is refused, from either layer, and writes nothing.
    std::fs::write(
        &config,
        "spec: ./api.yml\ngenerators:\n  python:\n    package-name: pets\n",
    )
    .unwrap();
    super::crozier_clean_env()
        .current_dir(dir.path())
        .env("CROZIER_ENUM_TYPE", "python_enums")
        .args(["generate", "python", "--output", "bad-env"])
        .assert()
        .failure()
        .code(1)
        .stderr(predicates::str::contains(
            "`CROZIER_ENUM_TYPE` must be `python-enums` or `literals`, got `python_enums`",
        ));
    super::crozier_clean_env()
        .current_dir(dir.path())
        .args([
            "generate",
            "python",
            "--output",
            "bad-flag",
            "--enum-type",
            "strict",
        ])
        .assert()
        .failure()
        .code(2)
        .stderr(predicates::str::contains("python-enums"));
    assert!(!dir.path().join("bad-env").exists());
    assert!(!dir.path().join("bad-flag").exists());
}

/// The published JSON Schema documents `enum-type` on a generator, with exactly
/// its two values.
#[test]
fn the_schema_documents_enum_type() {
    let out = super::crozier_clean_env()
        .arg("schema")
        .output()
        .expect("run crozier schema");
    assert!(out.status.success());
    let schema: serde_json::Value = serde_json::from_slice(&out.stdout).expect("schema JSON");
    let field = &schema["$defs"]["GeneratorSettings"]["properties"]["enum-type"];
    assert_eq!(field["anyOf"][0]["$ref"], "#/$defs/EnumType", "{field}");
    let values: Vec<&str> = schema["$defs"]["EnumType"]["oneOf"]
        .as_array()
        .expect("EnumType's values")
        .iter()
        .map(|value| value["const"].as_str().expect("a string value"))
        .collect();
    assert_eq!(values, ["python-enums", "literals"]);
    // Python-generator-specific: not a shared top-level field.
    assert!(schema["properties"].get("enum-type").is_none());
}
