

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.card import Card
from ..types.create_card_response import CreateCardResponse
from ..types.disable_card_response import DisableCardResponse
from ..types.list_cards_response import ListCardsResponse
from ..types.retrieve_card_response import RetrieveCardResponse
from .raw_client import AsyncRawCardsClient, RawCardsClient


OMIT = typing.cast(typing.Any, ...)


class CardsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawCardsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawCardsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawCardsClient
        """
        return self._raw_client

    def list_cards(
        self,
        *,
        cursor: typing.Optional[str] = None,
        customer_id: typing.Optional[str] = None,
        include_disabled: typing.Optional[bool] = None,
        reference_id: typing.Optional[str] = None,
        sort_order: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCardsResponse:
        """
        Retrieves a list of cards owned by the account making the request.
        A max of 25 cards will be returned.

        Parameters
        ----------
        cursor : typing.Optional[str]
            A pagination cursor returned by a previous call to this endpoint.
            Provide this to retrieve the next set of results for your original query.

            See [Pagination](https://developer.squareup.com/docs/basics/api101/pagination) for more information.

        customer_id : typing.Optional[str]
            Limit results to cards associated with the customer supplied.
            By default, all cards owned by the merchant are returned.

        include_disabled : typing.Optional[bool]
            Includes disabled cards.
            By default, all enabled cards owned by the merchant are returned.

        reference_id : typing.Optional[str]
            Limit results to cards associated with the reference_id supplied.

        sort_order : typing.Optional[str]
            Sorts the returned list by when the card was created with the specified order.
            This field defaults to ASC.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCardsResponse
            Success

        Examples
        --------
        from fern import FernApi

        client = FernApi(
            authorization="YOUR_AUTHORIZATION",
            token="YOUR_TOKEN",
        )
        client.cards.list_cards()
        """
        _response = self._raw_client.list_cards(
            cursor=cursor,
            customer_id=customer_id,
            include_disabled=include_disabled,
            reference_id=reference_id,
            sort_order=sort_order,
            request_options=request_options,
        )
        return _response.data

    def create_card(
        self,
        *,
        card: Card,
        idempotency_key: str,
        source_id: str,
        verification_token: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateCardResponse:
        """
        Adds a card on file to an existing merchant.

        Parameters
        ----------
        card : Card

        idempotency_key : str
            A unique string that identifies this CreateCard request. Keys can be
            any valid string and must be unique for every request.

            Max: 45 characters

            See [Idempotency keys](https://developer.squareup.com/docs/basics/api101/idempotency) for more information.

        source_id : str
            The ID of the source which represents the card information to be stored. This can be a card nonce or a payment id.

        verification_token : typing.Optional[str]
            An identifying token generated by [Payments.verifyBuyer()](https://developer.squareup.com/reference/sdks/web/payments/objects/Payments#Payments.verifyBuyer).
            Verification tokens encapsulate customer device information and 3-D Secure
            challenge results to indicate that Square has verified the buyer identity.

            See the [SCA Overview](https://developer.squareup.com/docs/sca-overview).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateCardResponse
            Success

        Examples
        --------
        from fern import Card, FernApi

        client = FernApi(
            authorization="YOUR_AUTHORIZATION",
            token="YOUR_TOKEN",
        )
        client.cards.create_card(
            card=Card(),
            idempotency_key="idempotency_key",
            source_id="source_id",
        )
        """
        _response = self._raw_client.create_card(
            card=card,
            idempotency_key=idempotency_key,
            source_id=source_id,
            verification_token=verification_token,
            request_options=request_options,
        )
        return _response.data

    def retrieve_card(
        self, card_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RetrieveCardResponse:
        """
        Retrieves details for a specific Card.

        Parameters
        ----------
        card_id : str
            Unique ID for the desired Card.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetrieveCardResponse
            Success

        Examples
        --------
        from fern import FernApi

        client = FernApi(
            authorization="YOUR_AUTHORIZATION",
            token="YOUR_TOKEN",
        )
        client.cards.retrieve_card(
            card_id="card_id",
        )
        """
        _response = self._raw_client.retrieve_card(card_id, request_options=request_options)
        return _response.data

    def disable_card(
        self, card_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DisableCardResponse:
        """
        Disables the card, preventing any further updates or charges.
        Disabling an already disabled card is allowed but has no effect.

        Parameters
        ----------
        card_id : str
            Unique ID for the desired Card.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DisableCardResponse
            Success

        Examples
        --------
        from fern import FernApi

        client = FernApi(
            authorization="YOUR_AUTHORIZATION",
            token="YOUR_TOKEN",
        )
        client.cards.disable_card(
            card_id="card_id",
        )
        """
        _response = self._raw_client.disable_card(card_id, request_options=request_options)
        return _response.data


class AsyncCardsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawCardsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawCardsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawCardsClient
        """
        return self._raw_client

    async def list_cards(
        self,
        *,
        cursor: typing.Optional[str] = None,
        customer_id: typing.Optional[str] = None,
        include_disabled: typing.Optional[bool] = None,
        reference_id: typing.Optional[str] = None,
        sort_order: typing.Optional[str] = None,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> ListCardsResponse:
        """
        Retrieves a list of cards owned by the account making the request.
        A max of 25 cards will be returned.

        Parameters
        ----------
        cursor : typing.Optional[str]
            A pagination cursor returned by a previous call to this endpoint.
            Provide this to retrieve the next set of results for your original query.

            See [Pagination](https://developer.squareup.com/docs/basics/api101/pagination) for more information.

        customer_id : typing.Optional[str]
            Limit results to cards associated with the customer supplied.
            By default, all cards owned by the merchant are returned.

        include_disabled : typing.Optional[bool]
            Includes disabled cards.
            By default, all enabled cards owned by the merchant are returned.

        reference_id : typing.Optional[str]
            Limit results to cards associated with the reference_id supplied.

        sort_order : typing.Optional[str]
            Sorts the returned list by when the card was created with the specified order.
            This field defaults to ASC.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListCardsResponse
            Success

        Examples
        --------
        import asyncio

        from fern import AsyncFernApi

        client = AsyncFernApi(
            authorization="YOUR_AUTHORIZATION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cards.list_cards()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_cards(
            cursor=cursor,
            customer_id=customer_id,
            include_disabled=include_disabled,
            reference_id=reference_id,
            sort_order=sort_order,
            request_options=request_options,
        )
        return _response.data

    async def create_card(
        self,
        *,
        card: Card,
        idempotency_key: str,
        source_id: str,
        verification_token: typing.Optional[str] = OMIT,
        request_options: typing.Optional[RequestOptions] = None,
    ) -> CreateCardResponse:
        """
        Adds a card on file to an existing merchant.

        Parameters
        ----------
        card : Card

        idempotency_key : str
            A unique string that identifies this CreateCard request. Keys can be
            any valid string and must be unique for every request.

            Max: 45 characters

            See [Idempotency keys](https://developer.squareup.com/docs/basics/api101/idempotency) for more information.

        source_id : str
            The ID of the source which represents the card information to be stored. This can be a card nonce or a payment id.

        verification_token : typing.Optional[str]
            An identifying token generated by [Payments.verifyBuyer()](https://developer.squareup.com/reference/sdks/web/payments/objects/Payments#Payments.verifyBuyer).
            Verification tokens encapsulate customer device information and 3-D Secure
            challenge results to indicate that Square has verified the buyer identity.

            See the [SCA Overview](https://developer.squareup.com/docs/sca-overview).

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        CreateCardResponse
            Success

        Examples
        --------
        import asyncio

        from fern import AsyncFernApi, Card

        client = AsyncFernApi(
            authorization="YOUR_AUTHORIZATION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cards.create_card(
                card=Card(),
                idempotency_key="idempotency_key",
                source_id="source_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.create_card(
            card=card,
            idempotency_key=idempotency_key,
            source_id=source_id,
            verification_token=verification_token,
            request_options=request_options,
        )
        return _response.data

    async def retrieve_card(
        self, card_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RetrieveCardResponse:
        """
        Retrieves details for a specific Card.

        Parameters
        ----------
        card_id : str
            Unique ID for the desired Card.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetrieveCardResponse
            Success

        Examples
        --------
        import asyncio

        from fern import AsyncFernApi

        client = AsyncFernApi(
            authorization="YOUR_AUTHORIZATION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cards.retrieve_card(
                card_id="card_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve_card(card_id, request_options=request_options)
        return _response.data

    async def disable_card(
        self, card_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> DisableCardResponse:
        """
        Disables the card, preventing any further updates or charges.
        Disabling an already disabled card is allowed but has no effect.

        Parameters
        ----------
        card_id : str
            Unique ID for the desired Card.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        DisableCardResponse
            Success

        Examples
        --------
        import asyncio

        from fern import AsyncFernApi

        client = AsyncFernApi(
            authorization="YOUR_AUTHORIZATION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.cards.disable_card(
                card_id="card_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.disable_card(card_id, request_options=request_options)
        return _response.data
