openapi: 3.1.0
info:
  title: probe
  version: 1.0.0
paths:
  /tools:
    get:
      operationId: getTool
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tool'
components:
  schemas:
    Tool:
      type: object
      properties:
        composition:
          anyOf:
          - type: object
            properties:
              name:
                type: string
              child0:
                type: string
              child1:
                type: string
          - type: string
