//! The parity shapes Fern was measured on under its default `enum_type`
//! (`literals`), each held whole against crozier's `--enum-type literals`.
//!
//! A case under [`LITERALS_MODE_DIR`] is one shape's document generated by Fern
//! CLI 5.67.1 with `fernapi/fern-python-sdk` 5.20.0 and `pydantic_config.enum_type`
//! unset, by `tools/fern-goldens/generate-fern-fixture.sh --enum-type literals`.
//! Its `fern-expected/` is that script's output as written: when the case has
//! a hand-written fixture of the same name, an overlay of the fixture's
//! `fern-expected/` (the files whose bytes differ, plus a manifest naming the
//! files Fern omits); otherwise, with its own `openapi.yml` beside it, the
//! complete tree reduced against nothing. The README beside the cases says
//! which shape each one is.

use std::path::{Path, PathBuf};

use super::{
    crozier, departure_ledger, golden_tree_failures, probe_fern_pins, repo_root, walk_files,
    GoldenLedger, HANDWRITTEN_DIR,
};

pub(super) const LITERALS_MODE_DIR: &str = "docs/fern-measurements/literals-mode";

pub(super) const TREE: &str = "fern-expected";

/// The overlay manifest `tools/fern-goldens/golden_overlay.py` writes.
pub(super) const MANIFEST: &str = ".crozier-overlay.json";

/// One case: the document crozier reads, the Fern tree it is held to, and
/// where that tree's unchanged files come from.
struct Case {
    name: String,
    spec: PathBuf,
    /// The hand-written fixture's `fern-expected/` an overlay sits on; `None`
    /// for a case carrying its complete tree.
    base: Option<PathBuf>,
    /// Files of `base` Fern does not emit under literals.
    removed: Vec<String>,
}

impl Case {
    fn golden(&self) -> String {
        format!("{LITERALS_MODE_DIR}/{}/{TREE}", self.name)
    }

    fn layer(&self) -> PathBuf {
        repo_root().join(self.golden())
    }

    /// Fern's literals tree: `base` minus `removed`, with the case's own files
    /// laid over it.
    fn materialize(&self) -> tempfile::TempDir {
        let tree = tempfile::tempdir().expect("literals tree tempdir");
        let copy = |from: &Path, rel: &str| {
            let to = tree.path().join(rel);
            std::fs::create_dir_all(to.parent().expect("a file has a parent")).expect("mkdir");
            std::fs::copy(from.join(rel), &to).expect("copy a Fern file");
        };
        if let Some(base) = &self.base {
            for rel in walk_files(base) {
                if !self.removed.contains(&rel) {
                    copy(base, &rel);
                }
            }
        }
        let layer = self.layer();
        for rel in walk_files(&layer) {
            if rel != MANIFEST {
                copy(&layer, &rel);
            }
        }
        tree
    }

    /// The ledger rows the materialized tree is held to: the case's own for a
    /// file it carries, the hand-written fixture's for every file it inherits.
    fn ledger(&self) -> Result<GoldenLedger, Vec<String>> {
        let own = departure_ledger().golden(&self.golden(), &[])?;
        let Some(base) = &self.base else {
            return Ok(own);
        };
        let inherited = departure_ledger().golden(&super::golden_path(base), &[])?;
        let files = walk_files(&self.layer())
            .into_iter()
            .filter(|rel| rel != MANIFEST)
            .collect();
        Ok(own.inherit(inherited, files, &self.removed))
    }
}

/// Every case, validated: its manifest records the pinned Fern pair under
/// literals, and it has exactly one document — its own, or its hand-written
/// fixture's, never both.
fn cases() -> Result<Vec<Case>, Vec<String>> {
    cases_in(repo_root())
}

/// Split from [`cases`] so the malformed-manifest test can point the same
/// validation at a scratch checkout instead of the committed overlays.
fn cases_in(repo: &Path) -> Result<Vec<Case>, Vec<String>> {
    let root = repo.join(LITERALS_MODE_DIR);
    let mut dirs: Vec<PathBuf> = std::fs::read_dir(&root)
        .map_err(|error| vec![format!("{LITERALS_MODE_DIR}: {error}")])?
        .filter_map(Result::ok)
        .map(|entry| entry.path())
        .filter(|path| path.is_dir())
        .collect();
    dirs.sort();
    let (cli_pin, sdk_pin) = probe_fern_pins();
    let mut cases = Vec::new();
    let mut failures = Vec::new();
    for dir in dirs {
        let name = dir
            .file_name()
            .map(|name| name.to_string_lossy().into_owned())
            .unwrap_or_default();
        let manifest_path = dir.join(TREE).join(MANIFEST);
        let manifest: serde_json::Value = match std::fs::read_to_string(&manifest_path)
            .map_err(|error| error.to_string())
            .and_then(|text| serde_json::from_str(&text).map_err(|error| error.to_string()))
        {
            Ok(manifest) => manifest,
            Err(error) => {
                failures.push(format!(
                    "{name}: {TREE}/{MANIFEST} is unreadable ({error}); regenerate the case with \
                     tools/fern-goldens/generate-fern-fixture.sh --enum-type literals"
                ));
                continue;
            }
        };
        let pins = [
            ("fern_cli_version", cli_pin.as_str()),
            ("fern_python_sdk_version", sdk_pin.as_str()),
            ("enum_type", "literals"),
        ];
        for (field, pin) in pins {
            if manifest[field] != pin {
                failures.push(format!(
                    "{name}: {TREE}/{MANIFEST} records {field} {}, not `{pin}` — regenerate the \
                     case at the corpus pin under literals",
                    manifest[field]
                ));
            }
        }
        let Some(removed) = manifest["removed"].as_array().and_then(|removed| {
            removed
                .iter()
                .map(|rel| rel.as_str().map(str::to_string))
                .collect::<Option<Vec<String>>>()
        }) else {
            failures.push(format!(
                "{name}: {TREE}/{MANIFEST} has no `removed` list of paths ({}); regenerate the \
                 case with tools/fern-goldens/generate-fern-fixture.sh --enum-type literals",
                manifest["removed"]
            ));
            continue;
        };
        let own_spec = dir.join("openapi.yml");
        let fixture = repo.join(HANDWRITTEN_DIR).join(&name);
        let case = match (own_spec.is_file(), fixture.join("fern-expected").is_dir()) {
            (true, false) if removed.is_empty() => Case {
                name,
                spec: own_spec,
                base: None,
                removed,
            },
            (true, false) => {
                failures.push(format!(
                    "{name}: carries its own openapi.yml, so its {TREE}/ is a complete tree, yet \
                     its manifest removes {removed:?}"
                ));
                continue;
            }
            (false, true) => Case {
                name,
                spec: fixture.join("openapi.yml"),
                base: Some(fixture.join("fern-expected")),
                removed,
            },
            (true, true) => {
                failures.push(format!(
                    "{name}: has both its own openapi.yml and the hand-written fixture \
                     {HANDWRITTEN_DIR}/{name}; keep the fixture's document and remove this copy"
                ));
                continue;
            }
            (false, false) => {
                failures.push(format!(
                    "{name}: has no openapi.yml and no hand-written fixture {HANDWRITTEN_DIR}/{name} \
                     for its overlay to sit on"
                ));
                continue;
            }
        };
        if let Some(base) = &case.base {
            for rel in &case.removed {
                if !base.join(rel).is_file() {
                    failures.push(format!(
                        "{}: its manifest removes {rel}, which {} does not have",
                        case.name,
                        super::golden_path(base)
                    ));
                }
            }
        }
        cases.push(case);
    }
    if failures.is_empty() {
        Ok(cases)
    } else {
        Err(failures)
    }
}

/// Every way crozier's literals output over `case` differs from Fern's tree
/// `expected`.
fn case_failures(case: &Case, expected: &Path, enum_type: &str) -> Vec<String> {
    let out = tempfile::tempdir().expect("crozier output tempdir");
    let result = crozier()
        .args(["generate", "python", "--spec"])
        .arg(&case.spec)
        .arg("--output")
        .arg(out.path())
        .args([
            "--package-name",
            "fern",
            "--project-name",
            "default_package_name",
            "--enum-type",
            enum_type,
        ])
        .output()
        .expect("run crozier");
    if !result.status.success() {
        return vec![format!(
            "{}: crozier failed over {}: {}",
            case.name,
            case.spec.display(),
            String::from_utf8_lossy(&result.stderr)
        )];
    }
    let ledger = match case.ledger() {
        Ok(ledger) => ledger,
        Err(failures) => return failures,
    };
    golden_tree_failures(
        &case.name,
        &case.spec.display().to_string(),
        &ledger,
        expected,
        out.path(),
    )
}

fn case(name: &str) -> Case {
    cases()
        .unwrap_or_else(|failures| panic!("{}", failures.join("\n")))
        .into_iter()
        .find(|case| case.name == name)
        .unwrap_or_else(|| panic!("no literals-mode case {name}"))
}

// llmlint: ignore-block[expensive_tests_stay_behind_their_own_edge] Every Fern golden comparison — the corpus `*_matches_fern_output` tests, the hand-written, probe and parameter-lowering gates — runs in this one binary suite by the project's design (crates/crozier-e2e/AGENTS.md), which drives the binary crozier:build leaves; this family of 30 cases joins them at about six seconds of a three-minute run, and giving golden comparisons their own Nx edge is a graph change for that whole family, not for this one.
/// Every case's complete literals tree equals crozier's `--enum-type literals`
/// output under the corpus gate's normalization, departures held to the ledger.
#[test]
fn literals_mode_measurements_match_fern() {
    let cases = cases().unwrap_or_else(|failures| panic!("{}", failures.join("\n")));
    assert!(
        cases.len() >= 30,
        "the literals-mode cases are missing: {:?}",
        cases.iter().map(|case| &case.name).collect::<Vec<_>>()
    );
    let failures: Vec<String> = cases
        .iter()
        .flat_map(|case| {
            let tree = case.materialize();
            case_failures(case, tree.path(), "literals")
        })
        .collect();
    assert!(failures.is_empty(), "{}", failures.join("\n\n"));
}
// llmlint: ignore-end[expensive_tests_stay_behind_their_own_edge]

/// The cases measure the enum mode: a described component enum is a bare
/// `Literal` alias under literals, so crozier's `python-enums` output over the
/// same document (its enum class and `core/enum.py`) fails the comparison.
#[test]
fn a_literals_case_refuses_python_enums_output() {
    let case = case("literal-enum-description-omitted");
    let tree = case.materialize();
    let alias = std::fs::read_to_string(tree.path().join("src/fern/types/sea_state.py"))
        .expect("the enum module");
    assert!(
        alias.contains("SeaState = typing.Union[typing.Literal[\"calm\", \"choppy\"], typing.Any]")
            && !alias.contains("How rough"),
        "{alias}"
    );
    let failures = case_failures(&case, tree.path(), "python-enums");
    assert!(
        failures
            .iter()
            .any(|failure| failure.contains("crozier's file set")
                || failure.contains("sea_state.py")),
        "{failures:?}"
    );
}

/// An unexplained byte beside a shape still fails: one changed literal in the
/// quoted enum's committed tree is a reported difference, not a departure.
#[test]
fn an_unexplained_literal_mismatch_fails() {
    let case = case("literal-enum-value-quote-escaping");
    let tree = case.materialize();
    let module = tree.path().join("src/fern/types/wording.py");
    let text = std::fs::read_to_string(&module).expect("the enum module");
    assert!(text.contains(r#""back\\room","#), "{text}");
    std::fs::write(
        &module,
        text.replace(r#""back\\room","#, r#""back\\rooms","#),
    )
    .expect("perturb the tree");
    let failures = case_failures(&case, tree.path(), "literals");
    assert!(
        failures
            .iter()
            .any(|failure| failure.contains("src/fern/types/wording.py differs")),
        "{failures:?}"
    );
}

/// Every case whose document is a hand-written fixture's carries only an
/// overlay: the files literals changes, never a second copy of the fixture's
/// unchanged ones.
#[test]
fn an_overlay_case_carries_only_the_files_literals_changes() {
    for case in cases().unwrap_or_else(|failures| panic!("{}", failures.join("\n"))) {
        let Some(base) = &case.base else { continue };
        for rel in walk_files(&case.layer()) {
            if rel == MANIFEST {
                continue;
            }
            let ours = std::fs::read(case.layer().join(&rel)).expect("an overlay file");
            assert!(
                std::fs::read(base.join(&rel)).ok().as_ref() != Some(&ours),
                "{}: {rel} is the fixture's own bytes; the overlay holds only what differs",
                case.name
            );
        }
    }
}

/// A manifest whose `removed` is not a list of paths is refused, naming the
/// case, rather than read as removing nothing.
#[test]
fn a_manifest_without_a_removed_list_is_refused() {
    let repo = tempfile::tempdir().expect("scratch checkout");
    let case = repo.path().join(LITERALS_MODE_DIR).join("sample-shape");
    std::fs::create_dir_all(case.join(TREE)).expect("case tree");
    std::fs::write(case.join("openapi.yml"), "openapi: 3.0.3\n").expect("document");
    let (cli, sdk) = probe_fern_pins();
    for removed in ["\"src/fern/core/enum.py\"", "[1]"] {
        std::fs::write(
            case.join(TREE).join(MANIFEST),
            format!(
                "{{\"fern_cli_version\": \"{cli}\", \"fern_python_sdk_version\": \"{sdk}\", \
                 \"enum_type\": \"literals\", \"base\": \"expected\", \"removed\": {removed}}}"
            ),
        )
        .expect("manifest");
        let failures = cases_in(repo.path()).err().expect("the case is refused");
        assert!(
            failures
                .iter()
                .any(|failure| failure.starts_with("sample-shape:")
                    && failure.contains("has no `removed` list of paths")),
            "{failures:?}"
        );
    }
}
