openapi: 3.0.3
info:
  title: probe
  version: 1.0.0
paths:
  /probe:
    x-fern-ignore: true
    post:
      operationId: probe
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
            examples:
              a:
                value:
                  id: a
                summary: Same
              b:
                value:
                  id: b
                summary: Same
      responses:
        '204':
          description: No Content
  /other:
    get:
      operationId: probe
      responses:
        '204':
          description: No Content
