openapi: 3.0.3
info:
  title: probe
  version: 1.0.0
paths:
  /probe:
    get:
      operationId: probe
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: &id001
                type: object
                properties:
                  id:
                    type: string
              examples:
                c:
                  value:
                    id: c
                  summary: One
            application/vnd.api+json:
              schema: *id001
              examples:
                a:
                  value:
                    id: a
                  summary: Same
                b:
                  value:
                    id: b
                  summary: Same
