openapi: 3.0.3
info:
  title: probe
  version: 1.0.0
paths:
  /probe:
    get:
      operationId: probe
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema: {$ref: '#/components/schemas/Thing'}
components:
  schemas:
    Thing:
      type: object
      properties:
        born:
          type: string
          format: date
          example: "2006-01-02T15:04:05+00:00"
