openapi: 3.0.3
info: {title: probe, version: 1.0.0}
paths:
  /probe:
    get:
      operationId: probe
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                allOf:
                  - {type: object, properties: {from: {type: string, format: date}}}
                  - {type: object, properties: {n: {type: integer}}}
              examples:
                response: {value: {from: "string [date]", n: 1}}
