

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .letta_usage_statistics_message_type import LettaUsageStatisticsMessageType


class LettaUsageStatistics(UniversalBaseModel):
    """
    Usage statistics for the agent interaction.

    Attributes:
        completion_tokens (int): The number of tokens generated by the agent.
        prompt_tokens (int): The number of tokens in the prompt.
        total_tokens (int): The total number of tokens processed by the agent.
        step_count (int): The number of steps taken by the agent.
        cached_input_tokens (Optional[int]): The number of input tokens served from cache. None if not reported.
        cache_write_tokens (Optional[int]): The number of input tokens written to cache. None if not reported.
        reasoning_tokens (Optional[int]): The number of reasoning/thinking tokens generated. None if not reported.
    """

    message_type: typing.Optional[LettaUsageStatisticsMessageType] = None
    completion_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of tokens generated by the agent.
    """

    prompt_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of tokens in the prompt.
    """

    total_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of tokens processed by the agent.
    """

    step_count: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of steps taken by the agent.
    """

    run_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The background task run IDs associated with the agent interaction
    """

    cached_input_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of input tokens served from cache. None if not reported by provider.
    """

    cache_write_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of input tokens written to cache (Anthropic only). None if not reported by provider.
    """

    reasoning_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of reasoning/thinking tokens generated. None if not reported by provider.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
