

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ReasoningContent(UniversalBaseModel):
    """
    Sent via the Anthropic Messages API
    """

    is_native: bool = pydantic.Field()
    """
    Whether the reasoning content was generated by a reasoner model that processed this step.
    """

    reasoning: str = pydantic.Field()
    """
    The intermediate reasoning or thought process content.
    """

    signature: typing.Optional[str] = pydantic.Field(default=None)
    """
    A unique identifier for this reasoning step.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
