

import typing

from ..core.client_wrapper import AsyncClientWrapper, SyncClientWrapper
from ..core.request_options import RequestOptions
from ..types.list_merchants_response import ListMerchantsResponse
from ..types.retrieve_merchant_response import RetrieveMerchantResponse
from .raw_client import AsyncRawMerchantsClient, RawMerchantsClient


class MerchantsClient:
    def __init__(self, *, client_wrapper: SyncClientWrapper):
        self._raw_client = RawMerchantsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> RawMerchantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        RawMerchantsClient
        """
        return self._raw_client

    def list_merchants(
        self, *, cursor: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> ListMerchantsResponse:
        """
        Returns `Merchant` information for a given access token.

        If you don't know a `Merchant` ID, you can use this endpoint to retrieve the merchant ID for an access token.
        You can specify your personal access token to get your own merchant information or specify an OAuth token
        to get the information for the  merchant that granted you access.

        If you know the merchant ID, you can also use the [RetrieveMerchant](https://developer.squareup.com/reference/square_2021-08-18/merchants-api/retrieve-merchant)
        endpoint to get the merchant information.

        Parameters
        ----------
        cursor : typing.Optional[int]
            The cursor generated by the previous response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMerchantsResponse
            Success

        Examples
        --------
        from fern import FernApi

        client = FernApi(
            authorization="YOUR_AUTHORIZATION",
            token="YOUR_TOKEN",
        )
        client.merchants.list_merchants()
        """
        _response = self._raw_client.list_merchants(cursor=cursor, request_options=request_options)
        return _response.data

    def retrieve_merchant(
        self, merchant_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RetrieveMerchantResponse:
        """
        Retrieve a `Merchant` object for the given `merchant_id`.

        Parameters
        ----------
        merchant_id : str
            The ID of the merchant to retrieve. If the string "me" is supplied as the ID,
            then retrieve the merchant that is currently accessible to this call.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetrieveMerchantResponse
            Success

        Examples
        --------
        from fern import FernApi

        client = FernApi(
            authorization="YOUR_AUTHORIZATION",
            token="YOUR_TOKEN",
        )
        client.merchants.retrieve_merchant(
            merchant_id="merchant_id",
        )
        """
        _response = self._raw_client.retrieve_merchant(merchant_id, request_options=request_options)
        return _response.data


class AsyncMerchantsClient:
    def __init__(self, *, client_wrapper: AsyncClientWrapper):
        self._raw_client = AsyncRawMerchantsClient(client_wrapper=client_wrapper)

    @property
    def with_raw_response(self) -> AsyncRawMerchantsClient:
        """
        Retrieves a raw implementation of this client that returns raw responses.

        Returns
        -------
        AsyncRawMerchantsClient
        """
        return self._raw_client

    async def list_merchants(
        self, *, cursor: typing.Optional[int] = None, request_options: typing.Optional[RequestOptions] = None
    ) -> ListMerchantsResponse:
        """
        Returns `Merchant` information for a given access token.

        If you don't know a `Merchant` ID, you can use this endpoint to retrieve the merchant ID for an access token.
        You can specify your personal access token to get your own merchant information or specify an OAuth token
        to get the information for the  merchant that granted you access.

        If you know the merchant ID, you can also use the [RetrieveMerchant](https://developer.squareup.com/reference/square_2021-08-18/merchants-api/retrieve-merchant)
        endpoint to get the merchant information.

        Parameters
        ----------
        cursor : typing.Optional[int]
            The cursor generated by the previous response.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        ListMerchantsResponse
            Success

        Examples
        --------
        import asyncio

        from fern import AsyncFernApi

        client = AsyncFernApi(
            authorization="YOUR_AUTHORIZATION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.merchants.list_merchants()


        asyncio.run(main())
        """
        _response = await self._raw_client.list_merchants(cursor=cursor, request_options=request_options)
        return _response.data

    async def retrieve_merchant(
        self, merchant_id: str, *, request_options: typing.Optional[RequestOptions] = None
    ) -> RetrieveMerchantResponse:
        """
        Retrieve a `Merchant` object for the given `merchant_id`.

        Parameters
        ----------
        merchant_id : str
            The ID of the merchant to retrieve. If the string "me" is supplied as the ID,
            then retrieve the merchant that is currently accessible to this call.

        request_options : typing.Optional[RequestOptions]
            Request-specific configuration.

        Returns
        -------
        RetrieveMerchantResponse
            Success

        Examples
        --------
        import asyncio

        from fern import AsyncFernApi

        client = AsyncFernApi(
            authorization="YOUR_AUTHORIZATION",
            token="YOUR_TOKEN",
        )


        async def main() -> None:
            await client.merchants.retrieve_merchant(
                merchant_id="merchant_id",
            )


        asyncio.run(main())
        """
        _response = await self._raw_client.retrieve_merchant(merchant_id, request_options=request_options)
        return _response.data
