

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .stack_event_hook_failure_mode import StackEventHookFailureMode
from .stack_event_hook_invocation_point import StackEventHookInvocationPoint
from .stack_event_hook_status import StackEventHookStatus
from .stack_event_resource_status import StackEventResourceStatus


class StackEvent(UniversalBaseModel):
    """
    The StackEvent data type.
    """

    stack_id: typing_extensions.Annotated[str, FieldMetadata(alias="StackId")] = pydantic.Field()
    """
    The unique ID name of the instance of the stack.
    """

    event_id: typing_extensions.Annotated[str, FieldMetadata(alias="EventId")] = pydantic.Field()
    """
    The unique ID of this event.
    """

    stack_name: typing_extensions.Annotated[str, FieldMetadata(alias="StackName")] = pydantic.Field()
    """
    The name associated with a stack.
    """

    logical_resource_id: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="LogicalResourceId")] = (
        pydantic.Field(default=None)
    )
    """
    The logical name of the resource specified in the template.
    """

    physical_resource_id: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="PhysicalResourceId")
    ] = pydantic.Field(default=None)
    """
    The name or unique identifier associated with the physical instance of the resource.
    """

    resource_type: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="ResourceType")] = (
        pydantic.Field(default=None)
    )
    """
    Type of resource. (For more information, go to <a href="https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-template-resource-type-ref.html">Amazon Web Services Resource Types Reference</a> in the CloudFormation User Guide.)
    """

    timestamp: typing_extensions.Annotated[dt.datetime, FieldMetadata(alias="Timestamp")] = pydantic.Field()
    """
    Time the status was updated.
    """

    resource_status: typing_extensions.Annotated[
        typing.Optional[StackEventResourceStatus], FieldMetadata(alias="ResourceStatus")
    ] = pydantic.Field(default=None)
    """
    Current status of the resource.
    """

    resource_status_reason: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="ResourceStatusReason")
    ] = pydantic.Field(default=None)
    """
    Success/failure message associated with the resource.
    """

    resource_properties: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="ResourceProperties")
    ] = pydantic.Field(default=None)
    """
    BLOB of the properties used to create the resource.
    """

    client_request_token: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="ClientRequestToken")
    ] = pydantic.Field(default=None)
    """
    <p>The token passed to the operation that generated this event.</p> <p>All events triggered by a given stack operation are assigned the same client request token, which you can use to track operations. For example, if you execute a <code>CreateStack</code> operation with the token <code>token1</code>, then all the <code>StackEvents</code> generated by that operation will have <code>ClientRequestToken</code> set as <code>token1</code>.</p> <p>In the console, stack operations display the client request token on the Events tab. Stack operations that are initiated from the console use the token format <i>Console-StackOperation-ID</i>, which helps you easily identify the stack operation . For example, if you create a stack using the console, each stack event would be assigned the same token in the following format: <code>Console-CreateStack-7f59c3cf-00d2-40c7-b2ff-e75db0987002</code>.</p>
    """

    hook_type: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="HookType")] = pydantic.Field(
        default=None
    )
    """
    The name of the hook.
    """

    hook_status: typing_extensions.Annotated[
        typing.Optional[StackEventHookStatus], FieldMetadata(alias="HookStatus")
    ] = pydantic.Field(default=None)
    """
    Provides the status of the change set hook.
    """

    hook_status_reason: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="HookStatusReason")] = (
        pydantic.Field(default=None)
    )
    """
    Provides the reason for the hook status.
    """

    hook_invocation_point: typing_extensions.Annotated[
        typing.Optional[StackEventHookInvocationPoint], FieldMetadata(alias="HookInvocationPoint")
    ] = pydantic.Field(default=None)
    """
    Invocation points are points in provisioning logic where hooks are initiated.
    """

    hook_failure_mode: typing_extensions.Annotated[
        typing.Optional[StackEventHookFailureMode], FieldMetadata(alias="HookFailureMode")
    ] = pydantic.Field(default=None)
    """
    <p>Specify the hook failure mode for non-compliant resources in the followings ways.</p> <ul> <li> <p> <code>FAIL</code> Stops provisioning resources.</p> </li> <li> <p> <code>WARN</code> Allows provisioning to continue with a warning message.</p> </li> </ul>
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
