

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .content_submission_shared_business_entities_content_definition import (
    ContentSubmissionSharedBusinessEntitiesContentDefinition,
)
from .content_submission_shared_business_entities_content_submission_attribute import (
    ContentSubmissionSharedBusinessEntitiesContentSubmissionAttribute,
)


class ContentSubmissionSharedBusinessEntitiesContentSubmission(UniversalBaseModel):
    """
    A content submission
    """

    attributes: typing_extensions.Annotated[
        typing.Optional[typing.List[ContentSubmissionSharedBusinessEntitiesContentSubmissionAttribute]],
        FieldMetadata(alias="Attributes"),
        pydantic.Field(alias="Attributes", description="Attributes of this ContentSubmission"),
    ] = None
    """
    Attributes of this ContentSubmission
    """

    build_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="BuildID"),
        pydantic.Field(
            alias="BuildID",
            description="ReadOnly. The ID of the Azure DevOps Build which will build the content package.",
        ),
    ] = None
    """
    ReadOnly. The ID of the Azure DevOps Build which will build the content package.
    """

    content_definition_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="ContentDefinitionID"),
        pydantic.Field(alias="ContentDefinitionID", description="The ID of the Content Definition."),
    ] = None
    """
    The ID of the Content Definition.
    """

    content_submission_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="ContentSubmissionID"),
        pydantic.Field(alias="ContentSubmissionID", description="The ID of this Content Submission."),
    ] = None
    """
    The ID of this Content Submission.
    """

    definition: typing_extensions.Annotated[
        typing.Optional[ContentSubmissionSharedBusinessEntitiesContentDefinition],
        FieldMetadata(alias="Definition"),
        pydantic.Field(alias="Definition", description="The ContentDefinition for this ContentSubmission"),
    ] = None
    """
    The ContentDefinition for this ContentSubmission
    """

    job_run_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="JobRunID"),
        pydantic.Field(
            alias="JobRunID", description="ReadOnly. The ID of the JobRun which will build the content package."
        ),
    ] = None
    """
    ReadOnly. The ID of the JobRun which will build the content package.
    """

    package_id: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="PackageID"),
        pydantic.Field(alias="PackageID", description="The ID of package generated by this content submission."),
    ] = None
    """
    The ID of package generated by this content submission.
    """

    release_notes: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ReleaseNotes"),
        pydantic.Field(alias="ReleaseNotes", description="Release Notes for this ContentSubmission"),
    ] = None
    """
    Release Notes for this ContentSubmission
    """

    repository: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="Repository"),
        pydantic.Field(
            alias="Repository", description="The SVN repository used as the source of this content submission"
        ),
    ] = None
    """
    The SVN repository used as the source of this content submission
    """

    revision: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="Revision"),
        pydantic.Field(alias="Revision", description="The SVN revision used as the source of this content submission."),
    ] = None
    """
    The SVN revision used as the source of this content submission.
    """

    submission_date: typing_extensions.Annotated[
        typing.Optional[dt.datetime],
        FieldMetadata(alias="SubmissionDate"),
        pydantic.Field(
            alias="SubmissionDate", description="Read Only. The UTC date and time the content submission was made."
        ),
    ] = None
    """
    Read Only. The UTC date and time the content submission was made.
    """

    user_id: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="UserID"),
        pydantic.Field(alias="UserID", description="Read Only. The ID of the user who submitted the content"),
    ] = None
    """
    Read Only. The ID of the user who submitted the content
    """

    version: typing_extensions.Annotated[
        typing.Optional[int],
        FieldMetadata(alias="Version"),
        pydantic.Field(
            alias="Version",
            description="Optional.  The version number assigned to this Content Submission and the resulting Package.\r\n            If not provided, version shall be 1 if it is the first content submission for the \r\n            ContentDefinitionID otherwise it shall be the highest content submission version for the\r\n            specified ContentDefinitionID incremented by 1.",
        ),
    ] = None
    """
    Optional.  The version number assigned to this Content Submission and the resulting Package.
                If not provided, version shall be 1 if it is the first content submission for the 
                ContentDefinitionID otherwise it shall be the highest content submission version for the
                specified ContentDefinitionID incremented by 1.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
