openapi: 3.0.3
info:
  title: probe
  version: 1.0.0
paths: {}
components:
  schemas:
    Node:
      type: object
      x-link:
        target:
          $ref: "#/components/schemas/Other"
      properties:
        id:
          type: string
    Other:
      type: object
      properties:
        parent: {$ref: '#/components/schemas/Node'}
