

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .event_stream_common import EventStreamCommon
from .timestamp import Timestamp


class Service(UniversalBaseModel):
    """
    Provides information about the service instance
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The service instance name. This should be a very short, human-readable name that may be displayed in listings of Service instances.
    """

    description: typing.Optional[str] = pydantic.Field(default=None)
    """
    The service instance description. This should be a human-readable description that may be showed in detailed views of Service instances. The description should be longer and more detailed than `name`.
    """

    type: str = pydantic.Field()
    """
    The type identifier for the service instance. The value must start with 'urn:x-tams:service'
    """

    api_version: str = pydantic.Field()
    """
    The version of the TAMS API specification this service instance implements
    """

    service_version: typing.Optional[str] = pydantic.Field(default=None)
    """
    The version of software providing this service. Note: Different implementations and software houses may use different conventions for their version identification. As such, this field is intentionally permissive and intended to be informative only. Client implementations should avoid using this field to determine compatibility.
    """

    event_stream_mechanisms: typing.Optional[typing.List[EventStreamCommon]] = pydantic.Field(default=None)
    """
    List the types of event stream that this service implementation supports
    """

    min_object_timeout: Timestamp = pydantic.Field()
    """
    The minimum timeframe within which a Media Object created by this service must be registered against a Flow segment before it is garbage collected. Services SHOULD allow a small grace period beyond the advertised value to account for latency in assigning the Objects and returning them to the Client. This timeout MUST be `300:0` (i.e. 5 minutes) or greater. Clients MUST be capable of reaching this minimum performance level. Clients SHOULD adapt to this value by balancing how many object URLs to request per page against how fast they will be used. Services MAY allow this value to be configured at deploy-time. Format as described by the [Timestamp](#/schemas/timestamp) type. For more infomation, see the documentation of the [`/flows/{flowId}/storage`](#/operations/POST_flows-flowId-storage) endpoint.
    """

    min_presigned_url_timeout: typing.Optional[Timestamp] = pydantic.Field(default=None)
    """
    The minimum timeframe within which pre-signed URLs generated by this Service are valid for (both for writing and reading content). This attribute MUST be set on implementations that support pre-signed URLs. Services SHOULD allow a small grace period beyond the advertised value to account for latency in generating pre-signed URLs and returning them to the Client. This timeout MUST be `30:0` (i.e. 30 second) or greater. The value of this parameter MUST be equal or less than `min_object_timeout` to avoid Objects being garbage collected while their pre-signed PUT URLs are still valid. Clients MUST be capable of reaching this minimum performance level. Clients SHOULD adapt to this value, by taking care to request URLs that will be used in a timely manner. Services MAY allow this value to be configured at deploy-time. Format as described by the [Timestamp](#/schemas/timestamp) type.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
