openapi: 3.0.3
info: {title: Probe, version: '1'}
paths:
  /probe:
    get:
      operationId: probe
      parameters:
        - name: value
          in: query
          schema: {type: array, items: {type: string}, default: all}
      responses:
        '204': {description: OK}
