

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class Error(UniversalBaseModel):
    """
    [RFC7807](https://tools.ietf.org/html/rfc7807) compliant response.
    """

    detail: typing.Optional[str] = pydantic.Field(default=None)
    """
    A human-readable explanation specific to this occurrence of the problem.
    """

    instance: typing.Optional[str] = pydantic.Field(default=None)
    """
    A URI reference that identifies the specific occurrence of the problem. It may or may
    not yield further information if dereferenced.
    """

    status: float = pydantic.Field()
    """
    The HTTP status code generated by the API server for this occurrence of the problem.
    """

    title: str = pydantic.Field()
    """
    A short, human-readable summary of the problem type.
    """

    type: str = pydantic.Field()
    """
    A URI reference [RFC3986] that identifies the problem type. This specification
    encourages that, when dereferenced, it provide human-readable documentation for
    the problem type.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
