openapi: 3.0.3
info:
  title: Lighthouse Network
  version: 1.0.0
paths:
  /beacon/api/status:
    get:
      operationId: beaconApiStatus
      x-fern-sdk-group-name: [beacon, api]
      x-fern-sdk-method-name: status
      responses:
        "200":
          description: The beacon's status line.
          content:
            application/json:
              schema:
                type: string
