#!/usr/bin/env python3
"""Which generated files a feature resting only on residual goldens lands in.

Some registered rows are golden tests with a measured `unmatched` residual:
every file of their goldens is byte-compared except the ones
`crates/crozier-e2e/tests/e2e.rs` names. A `golden` row whose only
real witnesses are those rows is proven only where the code it emits sits in a
byte-matched file, so this answers that per row, from crozier itself rather than
from a reading of its source: render the witness document as committed and
again with the feature's declaring nodes perturbed, generate both with the
crozier binary, and report the generated files that move, split by whether the
witness's golden test byte-compares them.

A row whose perturbation moves no file has no generated bytes the golden can
vouch for; the coverage report lists it as an open gap. The rows and their
perturbations are `CASES`; `docs/openapi-surface-coverage.md`'s *Golden rows
resting only on residual goldens* restates the result, and
`tools/surface-census/tests/surface_census_test.py` holds that table to the reach ledger and to each
residual's `unmatched` list.

Needs a built `crozier` (`cargo build`) and `ruff` on PATH, so the suite that
runs it is surface-reach's `test-residual-attribution`, after `crozier:build`,
and not the offline census suite.
"""

from __future__ import annotations

import importlib.util
import json
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path
from typing import Any, Callable

REPO = Path(__file__).resolve().parents[2]
CROZIER = REPO / "target" / "debug" / ("crozier.exe" if sys.platform == "win32" else "crozier")


def _census():
    spec = importlib.util.spec_from_file_location("openapi_surface_census", REPO / "tools" / "surface-census" / "openapi-surface-census.py")
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules.setdefault("openapi_surface_census", module)
    spec.loader.exec_module(module)
    return module


CENSUS = _census()
DISTINCT = {"type": "string", "format": "date-time"}


def _retype_format(old: str) -> Callable[[Any], int]:
    """Rewrite every `format: <old>` to `date-time`, which types the field differently."""
    def perturb(node: Any) -> int:
        count = 0
        if isinstance(node, dict):
            for key, value in node.items():
                if key == "format" and value == old:
                    node[key] = "date-time"
                    count += 1
                else:
                    count += perturb(value)
        elif isinstance(node, list):
            count += sum(perturb(value) for value in node)
        return count
    return perturb


def _retype_true_schemas(node: Any) -> int:
    """Replace every `true` schema at a property or `items` with a typed one."""
    count = 0
    if isinstance(node, dict):
        properties = node.get("properties")
        if isinstance(properties, dict):
            for name, value in properties.items():
                if value is True:
                    properties[name] = dict(DISTINCT)
                    count += 1
        if node.get("items") is True:
            node["items"] = dict(DISTINCT)
            count += 1
        count += sum(_retype_true_schemas(value) for value in node.values())
    elif isinstance(node, list):
        count += sum(_retype_true_schemas(value) for value in node)
    return count


def _stringify_null_examples(node: Any) -> int:
    """Give every Schema Object whose selected example is null a string one instead."""
    count = 0
    if isinstance(node, dict):
        if ("type" in node or "properties" in node or "examples" in node) and CENSUS.selected_example_kind(node) == "null":
            node.pop("example", None)
            node["examples"] = ["crozier-perturbed"]
            count += 1
        count += sum(_stringify_null_examples(value) for value in node.values())
    elif isinstance(node, list):
        count += sum(_stringify_null_examples(value) for value in node)
    return count


def _drop_server_extensions(document: Any) -> int:
    """Drop every `x-` extension a top-level Server Object writes."""
    count = 0
    for server in document.get("servers") or []:
        for key in [key for key in server if isinstance(key, str) and key.startswith("x-")]:
            del server[key]
            count += 1
    return count


# key -> (the residual row that is its only real witness, the perturbation)
CASES: dict[str, tuple[str, Callable[[Any], int]]] = {
    "format-idn-hostname": ("short-io", _retype_format("idn-hostname")),
    "format-iri": ("short-io", _retype_format("iri")),
    "boolean-schema-true": ("webflow-v2", _retype_true_schemas),
    "schema-example-null": ("webflow-v2", _stringify_null_examples),
    "extension-server": ("webflow-v2", _drop_server_extensions),
}


def _generate(document: Any, out: Path) -> dict[str, bytes]:
    source = out.with_suffix(".json")
    source.write_text(json.dumps(document), encoding="utf-8")
    completed = subprocess.run(
        [str(CROZIER), "generate", "--spec", str(source), "--output", str(out),
         "--package-name", "fern", "--project-name", "default_package_name"],
        capture_output=True, text=True,
    )
    if completed.returncode != 0:
        sys.exit(
            f"residual-attribution: crozier generate failed on {source.name}: "
            f"{completed.stderr.strip()[-600:]} — fix what it names in src/, then re-run "
            "`just residual-attribution`"
        )
    return {path.relative_to(out).as_posix(): path.read_bytes() for path in out.rglob("*") if path.is_file()}


def main() -> int:
    if not CROZIER.is_file():
        sys.exit(f"residual-attribution: no {CROZIER.relative_to(REPO)}; run `just residual-attribution`, which builds it")
    if shutil.which("ruff") is None:
        sys.exit("residual-attribution: `ruff` is not on PATH; install it with `just bootstrap`")
    registrations = CENSUS.golden_registrations(REPO / CENSUS.GOLDEN_REGISTRY)
    for key, (fixture, perturb) in CASES.items():
        path = CENSUS.spec_in(REPO / "tests" / "fixtures" / "corpus-sources" / fixture)
        if path is None:
            sys.exit(f"residual-attribution: {key}'s witness {fixture} has no committed source under "
                     "tests/fixtures/corpus-sources/; restore it from git (`just lint-corpus-sources` names "
                     "what is missing), then re-run")
        perturbed = CENSUS.load_document(path)
        if not perturb(perturbed):
            sys.exit(
                f"residual-attribution: {key}'s perturbation found nothing to change in {fixture}; "
                "its witness no longer declares the feature, so re-run `just golden-reach` and "
                "update CASES to the rows that still rest only on residual goldens"
            )
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            before = _generate(CENSUS.load_document(path), root / "before")
            after = _generate(perturbed, root / "after")
        moved = sorted(name for name in before.keys() | after.keys() if before.get(name) != after.get(name))
        unmatched = set(registrations[fixture].unmatched)
        matched = [name for name in moved if name not in unmatched]
        print(json.dumps({
            "key": key, "fixture": fixture,
            "byte_matched": matched, "unmatched": [name for name in moved if name in unmatched],
        }, sort_keys=True))
    return 0


if __name__ == "__main__":
    sys.exit(main())
