

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .address import Address


class Card(UniversalBaseModel):
    """
    Represents the payment details of a card to be used for payments. These
    details are determined by the payment token generated by Web Payments SDK.
    """

    billing_address: typing.Optional[Address] = None
    bin: typing.Optional[str] = pydantic.Field(default=None)
    """
    The first six digits of the card number, known as the Bank Identification Number (BIN). Only the Payments API
    returns this field.
    """

    card_brand: typing.Optional[str] = pydantic.Field(default=None)
    """
    The card's brand.
    """

    card_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of the card.
    The Card object includes this field only in response to Payments API calls.
    """

    cardholder_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the cardholder.
    """

    customer_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of a customer created using the Customers API to be associated with the card.
    """

    enabled: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether or not a card can be used for payments.
    """

    exp_month: typing.Optional[int] = pydantic.Field(default=None)
    """
    The expiration month of the associated card as an integer between 1 and 12.
    """

    exp_year: typing.Optional[int] = pydantic.Field(default=None)
    """
    The four-digit year of the card's expiration date.
    """

    fingerprint: typing.Optional[str] = pydantic.Field(default=None)
    """
    __Not currently set.__ Intended as a Square-assigned identifier, based
    on the card number, to identify the card across multiple locations within a
    single application.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    Unique ID for this card. Generated by Square.
    """

    last4: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="last_4"),
        pydantic.Field(alias="last_4", description="The last 4 digits of the card number."),
    ] = None
    """
    The last 4 digits of the card number.
    """

    prepaid_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    Indicates whether the Card is prepaid or not.
    The Card object includes this field only in response to Payments API calls.
    """

    reference_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    An optional user-defined reference ID that associates this card with
    another entity in an external system. For example, a customer ID from an
    external customer management system.
    """

    version: typing.Optional[int] = pydantic.Field(default=None)
    """
    Current version number of the card. Increments with each card update. Requests to update an
    existing Card object will be rejected unless the version in the request matches the current
    version for the Card.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
