

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class CatalogImage(UniversalBaseModel):
    """
    An image file to use in Square catalogs. It can be associated with catalog
    items, item variations, and categories.
    """

    caption: typing.Optional[str] = pydantic.Field(default=None)
    """
    A caption that describes what is shown in the image. Displayed in the
    Square Online Store. This is a searchable attribute for use in applicable query filters
    using the [SearchCatalogObjects](https://developer.squareup.com/reference/square_2021-08-18/catalog-api/search-catalog-objects).
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The internal name to identify this image in calls to the Square API.
    This is a searchable attribute for use in applicable query filters
    using the [SearchCatalogObjects](https://developer.squareup.com/reference/square_2021-08-18/catalog-api/search-catalog-objects).
    It is not unique and should not be shown in a buyer facing context.
    """

    url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL of this image, generated by Square after an image is uploaded
    using the [CreateCatalogImage](https://developer.squareup.com/reference/square_2021-08-18/catalog-api/create-catalog-image) endpoint.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
