

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .additional_recipient import AdditionalRecipient
from .address import Address
from .order import Order


class Checkout(UniversalBaseModel):
    """
    Square Checkout lets merchants accept online payments for supported
    payment types using a checkout workflow hosted on squareup.com.
    """

    additional_recipients: typing.Optional[typing.List[AdditionalRecipient]] = pydantic.Field(default=None)
    """
    Additional recipients (other than the merchant) receiving a portion of this checkout.
    For example, fees assessed on the purchase by a third party integration.
    """

    ask_for_shipping_address: typing.Optional[bool] = pydantic.Field(default=None)
    """
    If `true`, Square Checkout will collect shipping information on your
    behalf and store that information with the transaction information in your
    Square Dashboard.
    
    Default: `false`.
    """

    checkout_page_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL that the buyer's browser should be redirected to after the
    checkout is completed.
    """

    created_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The time when the checkout was created, in RFC 3339 format.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    ID generated by Square Checkout when a new checkout is requested.
    """

    merchant_support_email: typing.Optional[str] = pydantic.Field(default=None)
    """
    The email address to display on the Square Checkout confirmation page
    and confirmation email that the buyer can use to contact the merchant.
    
    If this value is not set, the confirmation page and email will display the
    primary email address associated with the merchant's Square account.
    
    Default: none; only exists if explicitly set.
    """

    order: typing.Optional[Order] = None
    pre_populate_buyer_email: typing.Optional[str] = pydantic.Field(default=None)
    """
    If provided, the buyer's email is pre-populated on the checkout page
    as an editable text field.
    
    Default: none; only exists if explicitly set.
    """

    pre_populate_shipping_address: typing.Optional[Address] = None
    redirect_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL to redirect to after checkout is completed with `checkoutId`,
    Square's `orderId`, `transactionId`, and `referenceId` appended as URL
    parameters. For example, if the provided redirect_url is
    `http://www.example.com/order-complete`, a successful transaction redirects
    the customer to:
    
    <pre><code>http://www.example.com/order-complete?checkoutId=xxxxxx&amp;orderId=xxxxxx&amp;referenceId=xxxxxx&amp;transactionId=xxxxxx</code></pre>
    
    If you do not provide a redirect URL, Square Checkout will display an order
    confirmation page on your behalf; however Square strongly recommends that
    you provide a redirect URL so you can verify the transaction results and
    finalize the order through your existing/normal confirmation workflow.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
