

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .disputed_payment import DisputedPayment
from .money import Money


class Dispute(UniversalBaseModel):
    """
    Represents a dispute a cardholder initiated with their bank.
    """

    amount_money: typing.Optional[Money] = None
    brand_dispute_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the dispute in the card brand system, generated by the card brand.
    """

    card_brand: typing.Optional[str] = pydantic.Field(default=None)
    """
    The card brand used in the disputed payment.
    """

    created_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The timestamp when the dispute was created, in RFC 3339 format.
    """

    dispute_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique ID for this `Dispute`, generated by Square.
    """

    disputed_payment: typing.Optional[DisputedPayment] = None
    due_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The time when the next action is due, in RFC 3339 format.
    """

    evidence_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    The IDs of the evidence associated with the dispute.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The unique ID for this `Dispute`, generated by Square.
    """

    location_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the location where the dispute originated.
    """

    reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    The dispute reason why the cardholder initiated the dispute with their bank.
    """

    reported_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The timestamp when the dispute was reported, in RFC 3339 format.
    """

    reported_date: typing.Optional[str] = pydantic.Field(default=None)
    """
    The timestamp when the dispute was reported, in RFC 3339 format.
    """

    state: typing.Optional[str] = pydantic.Field(default=None)
    """
    The current state of this dispute.
    """

    updated_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The timestamp when the dispute was last updated, in RFC 3339 format.
    """

    version: typing.Optional[int] = pydantic.Field(default=None)
    """
    The current version of the `Dispute`.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
