

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .inventory_adjustment_group import InventoryAdjustmentGroup
from .money import Money
from .source_application import SourceApplication


class InventoryAdjustment(UniversalBaseModel):
    """
    Represents a change in state or quantity of product inventory at a
    particular time and location.
    """

    adjustment_group: typing.Optional[InventoryAdjustmentGroup] = None
    catalog_object_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Square-generated ID of the
    [CatalogObject](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogObject) being tracked.
    """

    catalog_object_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The [type](https://developer.squareup.com/reference/square_2021-08-18/enums/CatalogObjectType) of the
    [CatalogObject](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogObject) being tracked. Tracking is only
    supported for the `ITEM_VARIATION` type.
    """

    created_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    An RFC 3339-formatted timestamp that indicates when the inventory adjustment is received.
    """

    employee_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Square-generated ID of the [Employee](https://developer.squareup.com/reference/square_2021-08-18/objects/Employee) responsible for the
    inventory adjustment.
    """

    from_state: typing.Optional[str] = pydantic.Field(default=None)
    """
    The [inventory state](https://developer.squareup.com/reference/square_2021-08-18/enums/InventoryState) of the related quantity
    of items before the adjustment.
    """

    goods_receipt_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Square-generated ID of the goods receipt that caused the
    adjustment. Only relevant for state transitions from the Square for Retail
    app.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A unique ID generated by Square for the
    `InventoryAdjustment`.
    """

    location_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Square-generated ID of the [Location](https://developer.squareup.com/reference/square_2021-08-18/objects/Location) where the related
    quantity of items is being tracked.
    """

    occurred_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    A client-generated RFC 3339-formatted timestamp that indicates when
    the inventory adjustment took place. For inventory adjustment updates, the `occurred_at`
    timestamp cannot be older than 24 hours or in the future relative to the
    time of the request.
    """

    purchase_order_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Square-generated ID of the purchase order that caused the
    adjustment. Only relevant for state transitions from the Square for Retail
    app.
    """

    quantity: typing.Optional[str] = pydantic.Field(default=None)
    """
    The number of items affected by the adjustment as a decimal string.
    Can support up to 5 digits after the decimal point.
    """

    reference_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    An optional ID provided by the application to tie the
    `InventoryAdjustment` to an external
    system.
    """

    refund_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Square-generated ID of the [Refund][#type-refund] that
    caused the adjustment. Only relevant for refund-related state
    transitions.
    """

    source: typing.Optional[SourceApplication] = None
    to_state: typing.Optional[str] = pydantic.Field(default=None)
    """
    The [inventory state](https://developer.squareup.com/reference/square_2021-08-18/enums/InventoryState) of the related quantity
    of items after the adjustment.
    """

    total_price_money: typing.Optional[Money] = None
    transaction_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The Square-generated ID of the [Transaction][#type-transaction] that
    caused the adjustment. Only relevant for payment-related state
    transitions.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
