

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .loyalty_event_accumulate_points import LoyaltyEventAccumulatePoints
from .loyalty_event_adjust_points import LoyaltyEventAdjustPoints
from .loyalty_event_create_reward import LoyaltyEventCreateReward
from .loyalty_event_delete_reward import LoyaltyEventDeleteReward
from .loyalty_event_expire_points import LoyaltyEventExpirePoints
from .loyalty_event_other import LoyaltyEventOther
from .loyalty_event_redeem_reward import LoyaltyEventRedeemReward


class LoyaltyEvent(UniversalBaseModel):
    """
    Provides information about a loyalty event.
    For more information, see [Loyalty events](https://developer.squareup.com/docs/loyalty-api/overview/#loyalty-events).
    """

    accumulate_points: typing.Optional[LoyaltyEventAccumulatePoints] = None
    adjust_points: typing.Optional[LoyaltyEventAdjustPoints] = None
    create_reward: typing.Optional[LoyaltyEventCreateReward] = None
    created_at: str = pydantic.Field()
    """
    The timestamp when the event was created, in RFC 3339 format.
    """

    delete_reward: typing.Optional[LoyaltyEventDeleteReward] = None
    expire_points: typing.Optional[LoyaltyEventExpirePoints] = None
    id: str = pydantic.Field()
    """
    The Square-assigned ID of the loyalty event.
    """

    location_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the [location](https://developer.squareup.com/reference/square_2021-08-18/objects/Location) where the event occurred.
    """

    loyalty_account_id: str = pydantic.Field()
    """
    The ID of the [loyalty account](https://developer.squareup.com/reference/square_2021-08-18/objects/LoyaltyAccount) in which the event occurred.
    """

    other_event: typing.Optional[LoyaltyEventOther] = None
    redeem_reward: typing.Optional[LoyaltyEventRedeemReward] = None
    source: str = pydantic.Field()
    """
    Defines whether the event was generated by the Square Point of Sale.
    """

    type: str = pydantic.Field()
    """
    The type of the loyalty event.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
