

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class LoyaltyEventSource(enum.StrEnum):
    """
    Defines whether the event was generated by the Square Point of Sale.
    """

    SQUARE = "SQUARE"
    LOYALTY_API = "LOYALTY_API"

    def visit(self, square: typing.Callable[[], T_Result], loyalty_api: typing.Callable[[], T_Result]) -> T_Result:
        if self is LoyaltyEventSource.SQUARE:
            return square()
        if self is LoyaltyEventSource.LOYALTY_API:
            return loyalty_api()
