

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .money import Money
from .order_line_item_applied_tax import OrderLineItemAppliedTax


class OrderServiceCharge(UniversalBaseModel):
    """
    Represents a service charge applied to an order.
    """

    amount_money: typing.Optional[Money] = None
    applied_money: typing.Optional[Money] = None
    applied_taxes: typing.Optional[typing.List[OrderLineItemAppliedTax]] = pydantic.Field(default=None)
    """
    The list of references to the taxes applied to this service charge. Each
    `OrderLineItemAppliedTax` has a `tax_uid` that references the `uid` of a top-level
    `OrderLineItemTax` that is being applied to this service charge. On reads, the amount applied
    is populated.
    
    An `OrderLineItemAppliedTax` is automatically created on every taxable service charge
    for all `ORDER` scoped taxes that are added to the order. `OrderLineItemAppliedTax` records
    for `LINE_ITEM` scoped taxes must be added in requests for the tax to apply to any taxable
    service charge. Taxable service charges have the `taxable` field set to `true` and calculated
    in the `SUBTOTAL_PHASE`.
    
    To change the amount of a tax, modify the referenced top-level tax.
    """

    calculation_phase: typing.Optional[str] = pydantic.Field(default=None)
    """
    The calculation phase at which to apply the service charge.
    """

    catalog_object_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The catalog object ID referencing the service charge [CatalogObject](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogObject).
    """

    catalog_version: typing.Optional[int] = pydantic.Field(default=None)
    """
    The version of the catalog object that this service charge references.
    """

    metadata: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Application-defined data attached to this service charge. Metadata fields are intended
    to store descriptive references or associations with an entity in another system or store brief
    information about the object. Square does not process this field; it only stores and returns it
    in relevant API calls. Do not use metadata to store any sensitive information (such as personally
    identifiable information or card details).
    
    Keys written by applications must be 60 characters or less and must be in the character set
    `[a-zA-Z0-9_-]`. Entries can also include metadata generated by Square. These keys are prefixed
    with a namespace, separated from the key with a ':' character.
    
    Values have a maximum length of 255 characters.
    
    An application can have up to 10 entries per metadata field.
    
    Entries written by applications are private and can only be read or modified by the same
    application.
    
    For more information, see [Metadata](https://developer.squareup.com/docs/build-basics/metadata).
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the service charge.
    """

    percentage: typing.Optional[str] = pydantic.Field(default=None)
    """
    The service charge percentage as a string representation of a
    decimal number. For example, `"7.25"` indicates a service charge of 7.25%.
    
    Exactly 1 of `percentage` or `amount_money` should be set.
    """

    taxable: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Indicates whether the service charge can be taxed. If set to `true`,
    order-level taxes automatically apply to the service charge. Note that
    service charges calculated in the `TOTAL_PHASE` cannot be marked as taxable.
    """

    total_money: typing.Optional[Money] = None
    total_tax_money: typing.Optional[Money] = None
    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of the service charge.
    """

    uid: typing.Optional[str] = pydantic.Field(default=None)
    """
    A unique ID that identifies the service charge only within this order.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
