

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .money import Money
from .order_fulfillment import OrderFulfillment
from .order_line_item import OrderLineItem
from .order_line_item_discount import OrderLineItemDiscount
from .order_line_item_tax import OrderLineItemTax
from .order_money_amounts import OrderMoneyAmounts
from .order_pricing_options import OrderPricingOptions
from .order_return import OrderReturn
from .order_reward import OrderReward
from .order_rounding_adjustment import OrderRoundingAdjustment
from .order_service_charge import OrderServiceCharge
from .order_source import OrderSource
from .refund import Refund
from .tender import Tender


class Order(UniversalBaseModel):
    """
    Contains all information related to a single order to process with Square,
    including line items that specify the products to purchase. `Order` objects also
    include information about any associated tenders, refunds, and returns.

    All Connect V2 Transactions have all been converted to Orders including all associated
    itemization data.
    """

    closed_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The timestamp for when the order reached a terminal [state](https://developer.squareup.com/reference/square_2021-08-18/enums/OrderState), in RFC 3339 format (for example "2016-09-04T23:59:33.123Z").
    """

    created_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The timestamp for when the order was created, in RFC 3339 format (for example, "2016-09-04T23:59:33.123Z").
    """

    customer_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the [customer](https://developer.squareup.com/reference/square_2021-08-18/objects/Customer) associated with the order.
    
    __IMPORTANT:__ You should specify a `customer_id` if you want the corresponding payment transactions
    to be explicitly linked to the customer in the Seller Dashboard. If this field is omitted, the 
    `customer_id` assigned to any underlying `Payment` objects is ignored and might result in the 
    creation of new [instant profiles](https://developer.squareup.com/docs/customers-api/what-it-does#instant-profiles).
    """

    discounts: typing.Optional[typing.List[OrderLineItemDiscount]] = pydantic.Field(default=None)
    """
    The list of all discounts associated with the order.
    
    Discounts can be scoped to either `ORDER` or `LINE_ITEM`. For discounts scoped to `LINE_ITEM`,
    an `OrderLineItemAppliedDiscount` must be added to each line item that the discount applies to.
    For discounts with `ORDER` scope, the server generates an `OrderLineItemAppliedDiscount`
    for every line item.
    
    __IMPORTANT__: If `LINE_ITEM` scope is set on any discounts in this field, using the deprecated
    `line_items.discounts` field results in an error. Use `line_items.applied_discounts`
    instead.
    """

    fulfillments: typing.Optional[typing.List[OrderFulfillment]] = pydantic.Field(default=None)
    """
    Details about order fulfillment.
    
    Orders can only be created with at most one fulfillment. However, orders returned
    by the API might contain multiple fulfillments.
    """

    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The order's unique ID.
    """

    line_items: typing.Optional[typing.List[OrderLineItem]] = pydantic.Field(default=None)
    """
    The line items included in the order.
    """

    location_id: str = pydantic.Field()
    """
    The ID of the seller location that this order is associated with.
    """

    metadata: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Application-defined data attached to this order. Metadata fields are intended
    to store descriptive references or associations with an entity in another system or store brief
    information about the object. Square does not process this field; it only stores and returns it
    in relevant API calls. Do not use metadata to store any sensitive information (such as personally
    identifiable information or card details).
    
    Keys written by applications must be 60 characters or less and must be in the character set
    `[a-zA-Z0-9_-]`. Entries can also include metadata generated by Square. These keys are prefixed
    with a namespace, separated from the key with a ':' character.
    
    Values have a maximum length of 255 characters.
    
    An application can have up to 10 entries per metadata field.
    
    Entries written by applications are private and can only be read or modified by the same
    application.
    
    For more information, see  [Metadata](https://developer.squareup.com/docs/build-basics/metadata).
    """

    net_amounts: typing.Optional[OrderMoneyAmounts] = None
    pricing_options: typing.Optional[OrderPricingOptions] = None
    reference_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A client-specified ID to associate an entity in another system
    with this order.
    """

    refunds: typing.Optional[typing.List[Refund]] = pydantic.Field(default=None)
    """
    The refunds that are part of this order.
    """

    return_amounts: typing.Optional[OrderMoneyAmounts] = None
    returns: typing.Optional[typing.List[OrderReturn]] = pydantic.Field(default=None)
    """
    A collection of items from sale orders being returned in this one. Normally part of an
    itemized return or exchange. There is exactly one `Return` object per sale `Order` being
    referenced.
    """

    rewards: typing.Optional[typing.List[OrderReward]] = pydantic.Field(default=None)
    """
    A set-like list of Rewards that have been added to the Order.
    """

    rounding_adjustment: typing.Optional[OrderRoundingAdjustment] = None
    service_charges: typing.Optional[typing.List[OrderServiceCharge]] = pydantic.Field(default=None)
    """
    A list of service charges applied to the order.
    """

    source: typing.Optional[OrderSource] = None
    state: typing.Optional[str] = pydantic.Field(default=None)
    """
    The current state of the order: `OPEN`, `COMPLETED`, or `CANCELED`.
    """

    taxes: typing.Optional[typing.List[OrderLineItemTax]] = pydantic.Field(default=None)
    """
    The list of all taxes associated with the order.
    
    Taxes can be scoped to either `ORDER` or `LINE_ITEM`. For taxes with `LINE_ITEM` scope, an
    `OrderLineItemAppliedTax` must be added to each line item that the tax applies to. For taxes
    with `ORDER` scope, the server generates an `OrderLineItemAppliedTax` for every line item.
    
    On reads, each tax in the list includes the total amount of that tax applied to the order.
    
    __IMPORTANT__: If `LINE_ITEM` scope is set on any taxes in this field, using the deprecated
    `line_items.taxes` field results in an error. Use `line_items.applied_taxes`
    instead.
    """

    tenders: typing.Optional[typing.List[Tender]] = pydantic.Field(default=None)
    """
    The tenders that were used to pay for the order.
    """

    total_discount_money: typing.Optional[Money] = None
    total_money: typing.Optional[Money] = None
    total_service_charge_money: typing.Optional[Money] = None
    total_tax_money: typing.Optional[Money] = None
    total_tip_money: typing.Optional[Money] = None
    updated_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The timestamp for when the order was last updated, in RFC 3339 format (for example, "2016-09-04T23:59:33.123Z").
    """

    version: typing.Optional[int] = pydantic.Field(default=None)
    """
    The version number, which is incremented each time an update is committed to the order.
    Orders not created through the API do not include a version number and
    therefore cannot be updated.
    
    [Read more about working with versions](https://developer.squareup.com/docs/orders-api/manage-orders#update-orders).
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
