

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .order_fulfillment_pickup_details import OrderFulfillmentPickupDetails
from .order_fulfillment_shipment_details import OrderFulfillmentShipmentDetails


class OrderFulfillment(UniversalBaseModel):
    """
    Contains details about how to fulfill this order.
    """

    metadata: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Application-defined data attached to this fulfillment. Metadata fields are intended
    to store descriptive references or associations with an entity in another system or store brief
    information about the object. Square does not process this field; it only stores and returns it
    in relevant API calls. Do not use metadata to store any sensitive information (such as personally
    identifiable information or card details).
    
    Keys written by applications must be 60 characters or less and must be in the character set
    `[a-zA-Z0-9_-]`. Entries can also include metadata generated by Square. These keys are prefixed
    with a namespace, separated from the key with a ':' character.
    
    Values have a maximum length of 255 characters.
    
    An application can have up to 10 entries per metadata field.
    
    Entries written by applications are private and can only be read or modified by the same
    application.
    
    For more information, see [Metadata](https://developer.squareup.com/docs/build-basics/metadata).
    """

    pickup_details: typing.Optional[OrderFulfillmentPickupDetails] = None
    shipment_details: typing.Optional[OrderFulfillmentShipmentDetails] = None
    state: typing.Optional[str] = pydantic.Field(default=None)
    """
    The state of the fulfillment.
    """

    type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of the fulfillment.
    """

    uid: typing.Optional[str] = pydantic.Field(default=None)
    """
    A unique ID that identifies the fulfillment only within this order.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
