

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .money import Money
from .order_line_item_applied_discount import OrderLineItemAppliedDiscount
from .order_line_item_applied_tax import OrderLineItemAppliedTax
from .order_line_item_modifier import OrderLineItemModifier
from .order_line_item_pricing_blocklists import OrderLineItemPricingBlocklists
from .order_quantity_unit import OrderQuantityUnit


class OrderLineItem(UniversalBaseModel):
    """
    Represents a line item in an order. Each line item describes a different
    product to purchase, with its own quantity and price details.
    """

    applied_discounts: typing.Optional[typing.List[OrderLineItemAppliedDiscount]] = pydantic.Field(default=None)
    """
    The list of references to discounts applied to this line item. Each
    `OrderLineItemAppliedDiscount` has a `discount_uid` that references the `uid` of a top-level
    `OrderLineItemDiscounts` applied to the line item. On reads, the amount
    applied is populated.
    
    An `OrderLineItemAppliedDiscount` is automatically created on every line item for all
    `ORDER` scoped discounts that are added to the order. `OrderLineItemAppliedDiscount` records
    for `LINE_ITEM` scoped discounts must be added in requests for the discount to apply to any
    line items.
    
    To change the amount of a discount, modify the referenced top-level discount.
    """

    applied_taxes: typing.Optional[typing.List[OrderLineItemAppliedTax]] = pydantic.Field(default=None)
    """
    The list of references to taxes applied to this line item. Each
    `OrderLineItemAppliedTax` has a `tax_uid` that references the `uid` of a
    top-level `OrderLineItemTax` applied to the line item. On reads, the
    amount applied is populated.
    
    An `OrderLineItemAppliedTax` is automatically created on every line
    item for all `ORDER` scoped taxes added to the order. `OrderLineItemAppliedTax`
    records for `LINE_ITEM` scoped taxes must be added in requests for the tax
    to apply to any line items.
    
    To change the amount of a tax, modify the referenced top-level tax.
    """

    base_price_money: typing.Optional[Money] = None
    catalog_object_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The [CatalogItemVariation](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogItemVariation) ID applied to this line item.
    """

    catalog_version: typing.Optional[int] = pydantic.Field(default=None)
    """
    The version of the catalog object that this line item references.
    """

    gross_sales_money: typing.Optional[Money] = None
    item_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of line item: an itemized sale, a non-itemized sale (custom amount), or the
    activation or reloading of a gift card.
    """

    metadata: typing.Optional[typing.Dict[str, str]] = pydantic.Field(default=None)
    """
    Application-defined data attached to this line item. Metadata fields are intended
    to store descriptive references or associations with an entity in another system or store brief
    information about the object. Square does not process this field; it only stores and returns it
    in relevant API calls. Do not use metadata to store any sensitive information (such as personally
    identifiable information or card details).
    
    Keys written by applications must be 60 characters or less and must be in the character set
    `[a-zA-Z0-9_-]`. Entries can also include metadata generated by Square. These keys are prefixed
    with a namespace, separated from the key with a ':' character.
    
    Values have a maximum length of 255 characters.
    
    An application can have up to 10 entries per metadata field.
    
    Entries written by applications are private and can only be read or modified by the same
    application.
    
    For more information, see [Metadata](https://developer.squareup.com/docs/build-basics/metadata).
    """

    modifiers: typing.Optional[typing.List[OrderLineItemModifier]] = pydantic.Field(default=None)
    """
    The [CatalogModifier](https://developer.squareup.com/reference/square_2021-08-18/objects/CatalogModifier)s applied to this line item.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the line item.
    """

    note: typing.Optional[str] = pydantic.Field(default=None)
    """
    The note of the line item.
    """

    pricing_blocklists: typing.Optional[OrderLineItemPricingBlocklists] = None
    quantity: str = pydantic.Field()
    """
    The quantity purchased, formatted as a decimal number.
    For example, `"3"`.
    
    Line items with a quantity of `"0"` are automatically removed
    when paying for or otherwise completing the order.
    
    Line items with a `quantity_unit` can have non-integer quantities.
    For example, `"1.70000"`.
    """

    quantity_unit: typing.Optional[OrderQuantityUnit] = None
    total_discount_money: typing.Optional[Money] = None
    total_money: typing.Optional[Money] = None
    total_tax_money: typing.Optional[Money] = None
    uid: typing.Optional[str] = pydantic.Field(default=None)
    """
    A unique ID that identifies the line item only within this order.
    """

    variation_name: typing.Optional[str] = pydantic.Field(default=None)
    """
    The name of the variation applied to this line item.
    """

    variation_total_price_money: typing.Optional[Money] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
