

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .address import Address
from .bank_account_payment_details import BankAccountPaymentDetails
from .card_payment_details import CardPaymentDetails
from .cash_payment_details import CashPaymentDetails
from .digital_wallet_details import DigitalWalletDetails
from .external_payment_details import ExternalPaymentDetails
from .money import Money
from .processing_fee import ProcessingFee
from .risk_evaluation import RiskEvaluation


class Payment(UniversalBaseModel):
    """
    Represents a payment processed by the Square API.
    """

    amount_money: typing.Optional[Money] = None
    app_fee_money: typing.Optional[Money] = None
    approved_money: typing.Optional[Money] = None
    bank_account_details: typing.Optional[BankAccountPaymentDetails] = None
    billing_address: typing.Optional[Address] = None
    buyer_email_address: typing.Optional[str] = pydantic.Field(default=None)
    """
    The buyer's email address.
    """

    capabilities: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    Actions that can be performed on this payment:
    - `EDIT_AMOUNT_UP` - The payment amount can be edited up.
    - `EDIT_AMOUNT_DOWN` - The payment amount can be edited down.
    - `EDIT_TIP_AMOUNT_UP` - The tip amount can be edited up.
    - `EDIT_TIP_AMOUNT_DOWN` - The tip amount can be edited down.
    """

    card_details: typing.Optional[CardPaymentDetails] = None
    cash_details: typing.Optional[CashPaymentDetails] = None
    created_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The timestamp of when the payment was created, in RFC 3339 format.
    """

    customer_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The [Customer](https://developer.squareup.com/reference/square_2021-08-18/objects/Customer) ID of the customer associated with the payment.
    """

    delay_action: typing.Optional[str] = pydantic.Field(default=None)
    """
    The action to be applied to the payment when the `delay_duration` has elapsed. This field
    is read-only.
    
    Current values include `CANCEL`.
    """

    delay_duration: typing.Optional[str] = pydantic.Field(default=None)
    """
    The duration of time after the payment's creation when Square automatically applies the
    `delay_action` to the payment. This automatic `delay_action` applies only to payments that
    do not reach a terminal state (COMPLETED, CANCELED, or FAILED) before the `delay_duration`
    time period.
    
    This field is specified as a time duration, in RFC 3339 format.
    
    Notes:
    This feature is only supported for card payments.
    
    Default:
    
    - Card-present payments: "PT36H" (36 hours) from the creation time.
    - Card-not-present payments: "P7D" (7 days) from the creation time.
    """

    delayed_until: typing.Optional[str] = pydantic.Field(default=None)
    """
    The read-only timestamp of when the `delay_action` is automatically applied,
    in RFC 3339 format.
    
    Note that this field is calculated by summing the payment's `delay_duration` and `created_at`
    fields. The `created_at` field is generated by Square and might not exactly match the
    time on your local machine.
    """

    employee_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    An optional ID of the employee associated with taking the payment.
    """

    external_details: typing.Optional[ExternalPaymentDetails] = None
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A unique ID for the payment.
    """

    location_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the location associated with the payment.
    """

    note: typing.Optional[str] = pydantic.Field(default=None)
    """
    An optional note to include when creating a payment.
    """

    order_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the order associated with the payment.
    """

    processing_fee: typing.Optional[typing.List[ProcessingFee]] = pydantic.Field(default=None)
    """
    The processing fees and fee adjustments assessed by Square for this payment.
    """

    receipt_number: typing.Optional[str] = pydantic.Field(default=None)
    """
    The payment's receipt number.
    The field is missing if a payment is canceled.
    """

    receipt_url: typing.Optional[str] = pydantic.Field(default=None)
    """
    The URL for the payment's receipt.
    The field is only populated for COMPLETED payments.
    """

    reference_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    An optional ID that associates the payment with an entity in
    another system.
    """

    refund_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    A list of `refund_id`s identifying refunds for the payment.
    """

    refunded_money: typing.Optional[Money] = None
    risk_evaluation: typing.Optional[RiskEvaluation] = None
    shipping_address: typing.Optional[Address] = None
    source_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The source type for this payment.
    
    Current values include `CARD`, `BANK_ACCOUNT`, `WALLET`, `CASH`, or `EXTERNAL`.
    """

    statement_description_identifier: typing.Optional[str] = pydantic.Field(default=None)
    """
    Additional payment information that gets added to the customer's card statement
    as part of the statement description.
    
    Note that the `statement_description_identifier` might get truncated on the statement description
    to fit the required information including the Square identifier (SQ *) and the name of the
    seller taking the payment.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    Indicates whether the payment is APPROVED, PENDING, COMPLETED, CANCELED, or FAILED.
    """

    tip_money: typing.Optional[Money] = None
    total_money: typing.Optional[Money] = None
    updated_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The timestamp of when the payment was last updated, in RFC 3339 format.
    """

    version_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    Used for optimistic concurrency. This opaque token identifies a specific version of the
    `Payment` object.
    """

    wallet_details: typing.Optional[DigitalWalletDetails] = None

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
