

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .money import Money
from .processing_fee import ProcessingFee


class PaymentRefund(UniversalBaseModel):
    """
    Represents a refund of a payment made using Square. Contains information about
    the original payment and the amount of money refunded.
    """

    amount_money: Money
    app_fee_money: typing.Optional[Money] = None
    created_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The timestamp of when the refund was created, in RFC 3339 format.
    """

    id: str = pydantic.Field()
    """
    The unique ID for this refund, generated by Square.
    """

    location_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The location ID associated with the payment this refund is attached to.
    """

    order_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the order associated with the refund.
    """

    payment_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the payment associated with this refund.
    """

    processing_fee: typing.Optional[typing.List[ProcessingFee]] = pydantic.Field(default=None)
    """
    Processing fees and fee adjustments assessed by Square for this refund.
    """

    reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    The reason for the refund.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    The refund's status:
    - `PENDING` - Awaiting approval.
    - `COMPLETED` - Successfully completed.
    - `REJECTED` - The refund was rejected.
    - `FAILED` - An error occurred.
    """

    updated_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The timestamp of when the refund was last updated, in RFC 3339 format.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
