

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .device_checkout_options import DeviceCheckoutOptions
from .money import Money


class TerminalCheckout(UniversalBaseModel):
    """ """

    amount_money: Money
    app_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The ID of the application that created the checkout.
    """

    cancel_reason: typing.Optional[str] = pydantic.Field(default=None)
    """
    Present if the status is `CANCELED`.
    """

    created_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The time when the `TerminalCheckout` was created, as an RFC 3339 timestamp.
    """

    deadline_duration: typing.Optional[str] = pydantic.Field(default=None)
    """
    An RFC 3339 duration, after which the checkout is automatically canceled.
    A `TerminalCheckout` that is `PENDING` is automatically `CANCELED` and has a cancellation reason
    of `TIMED_OUT`.
    
    Default: 5 minutes from creation
    
    Maximum: 5 minutes
    """

    device_options: DeviceCheckoutOptions
    id: typing.Optional[str] = pydantic.Field(default=None)
    """
    A unique ID for this `TerminalCheckout`.
    """

    location_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    The location of the device where the `TerminalCheckout` was directed.
    """

    note: typing.Optional[str] = pydantic.Field(default=None)
    """
    An optional note to associate with the checkout, as well as with any payments used to complete the checkout.
    """

    payment_ids: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    A list of IDs for payments created by this `TerminalCheckout`.
    """

    payment_type: typing.Optional[str] = pydantic.Field(default=None)
    """
    The type of payment the terminal should attempt to capture from. Defaults to `CARD_PRESENT`.
    """

    reference_id: typing.Optional[str] = pydantic.Field(default=None)
    """
    An optional user-defined reference ID that can be used to associate
    this `TerminalCheckout` to another entity in an external system. For example, an order
    ID generated by a third-party shopping cart. The ID is also associated with any payments
    used to complete the checkout.
    """

    status: typing.Optional[str] = pydantic.Field(default=None)
    """
    The status of the `TerminalCheckout`.
    Options: `PENDING`, `IN_PROGRESS`, `CANCEL_REQUESTED`, `CANCELED`, `COMPLETED`
    """

    updated_at: typing.Optional[str] = pydantic.Field(default=None)
    """
    The time when the `TerminalCheckout` was last updated, as an RFC 3339 timestamp.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
