openapi: 3.0.3
info:
  title: probe
  version: 1.0.0
paths:
  /agents:
    get:
      operationId: listAgents
      parameters:
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
            enum: ["2026-03-11"]
      responses:
        "204":
          description: No Content
