openapi: 3.0.3
info:
  title: probe
  version: 1.0.0
paths:
  /agents:
    get:
      operationId: listAgents
      parameters:
        - name: Api-Version
          in: header
          required: true
          schema: {$ref: '#/components/schemas/Version'}
      responses:
        "204":
          description: No Content
components:
  schemas:
    Version: {type: string, enum: ["2026-03-11"]}
