

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .applications_application_developer import ApplicationsApplicationDeveloper


class ApplicationsApplication(UniversalBaseModel):
    application_id: typing_extensions.Annotated[typing.Optional[int], FieldMetadata(alias="applicationId")] = (
        pydantic.Field(default=None)
    )
    """
    Unique ID assigned to the application
    """

    creation_date: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="creationDate")] = (
        pydantic.Field(default=None)
    )
    """
    Date the application was first added to our database.
    """

    first_published: typing_extensions.Annotated[
        typing.Optional[dt.datetime], FieldMetadata(alias="firstPublished")
    ] = pydantic.Field(default=None)
    """
    Date the first time the application status entered the 'Public' status.
    """

    link: typing.Optional[str] = pydantic.Field(default=None)
    """
    Link to website for the application where a user can learn more about the app.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the application
    """

    origin: typing.Optional[str] = pydantic.Field(default=None)
    """
    Value of the Origin header sent in requests generated by this application.
    """

    override_authorize_view_name: typing_extensions.Annotated[
        typing.Optional[str], FieldMetadata(alias="overrideAuthorizeViewName")
    ] = pydantic.Field(default=None)
    """
    An optional override for the Authorize view name.
    """

    redirect_url: typing_extensions.Annotated[typing.Optional[str], FieldMetadata(alias="redirectUrl")] = (
        pydantic.Field(default=None)
    )
    """
    URL used to pass the user's authorization code to the application
    """

    scope: typing.Optional[int] = pydantic.Field(default=None)
    """
    Permissions the application needs to work
    """

    status: typing.Optional[int] = pydantic.Field(default=None)
    """
    Current status of the application.
    """

    status_changed: typing_extensions.Annotated[typing.Optional[dt.datetime], FieldMetadata(alias="statusChanged")] = (
        pydantic.Field(default=None)
    )
    """
    Date the application status last changed.
    """

    team: typing.Optional[typing.List[ApplicationsApplicationDeveloper]] = pydantic.Field(default=None)
    """
    List of team members who manage this application on Bungie.net. Will always consist of at least the application owner.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
