

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel


class ProjectLogsEventMetrics(UniversalBaseModel):
    """
    Metrics are numerical measurements tracking the execution of the code that produced the project logs event. Use "start" and "end" to track the time span over which the project logs event was produced
    """

    start: typing.Optional[float] = pydantic.Field(default=None)
    """
    A unix timestamp recording when the section of code which produced the project logs event started
    """

    end: typing.Optional[float] = pydantic.Field(default=None)
    """
    A unix timestamp recording when the section of code which produced the project logs event finished
    """

    prompt_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of tokens in the prompt used to generate the project logs event (only set if this is an LLM span)
    """

    completion_tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    The number of tokens in the completion generated by the model (only set if this is an LLM span)
    """

    tokens: typing.Optional[int] = pydantic.Field(default=None)
    """
    The total number of tokens in the input and output of the project logs event.
    """

    caller_functionname: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    This metric is deprecated
    """

    caller_filename: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    This metric is deprecated
    """

    caller_lineno: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    This metric is deprecated
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
