

import datetime as dt
import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .object_reference_nullish import ObjectReferenceNullish
from .project_logs_event_classifications_value_item import ProjectLogsEventClassificationsValueItem
from .project_logs_event_context import ProjectLogsEventContext
from .project_logs_event_log_id import ProjectLogsEventLogId
from .project_logs_event_metadata import ProjectLogsEventMetadata
from .project_logs_event_metrics import ProjectLogsEventMetrics
from .span_attributes import SpanAttributes


class ProjectLogsEvent(UniversalBaseModel):
    id: str = pydantic.Field()
    """
    A unique identifier for the project logs event. If you don't provide one, Braintrust will generate one for you
    """

    xact_id: typing_extensions.Annotated[
        str,
        FieldMetadata(alias="_xact_id"),
        pydantic.Field(
            alias="_xact_id",
            description="The transaction id of an event is unique to the network operation that processed the event insertion. Transaction ids are monotonically increasing over time and can be used to retrieve a versioned snapshot of the project logs (see the `version` parameter)",
        ),
    ]
    """
    The transaction id of an event is unique to the network operation that processed the event insertion. Transaction ids are monotonically increasing over time and can be used to retrieve a versioned snapshot of the project logs (see the `version` parameter)
    """

    pagination_key: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="_pagination_key"),
        pydantic.Field(
            alias="_pagination_key",
            description="A stable, time-ordered key that can be used to paginate over project logs events. This field is auto-generated by Braintrust and only exists in Brainstore.",
        ),
    ] = None
    """
    A stable, time-ordered key that can be used to paginate over project logs events. This field is auto-generated by Braintrust and only exists in Brainstore.
    """

    created: dt.datetime = pydantic.Field()
    """
    The timestamp the project logs event was created
    """

    org_id: str = pydantic.Field()
    """
    Unique id for the organization that the project belongs under
    """

    project_id: str = pydantic.Field()
    """
    Unique identifier for the project
    """

    log_id: ProjectLogsEventLogId = pydantic.Field()
    """
    A literal 'g' which identifies the log as a project log
    """

    input: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    The arguments that uniquely define a user input (an arbitrary, JSON serializable object).
    """

    output: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    The output of your application, including post-processing (an arbitrary, JSON serializable object), that allows you to determine whether the result is correct or not. For example, in an app that generates SQL queries, the `output` should be the _result_ of the SQL query generated by the model, not the query itself, because there may be multiple valid queries that answer a single question.
    """

    expected: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    The ground truth value (an arbitrary, JSON serializable object) that you'd compare to `output` to determine if your `output` value is correct or not. Braintrust currently does not compare `output` to `expected` for you, since there are so many different ways to do that correctly. Instead, these values are just used to help you navigate while digging into analyses. However, we may later use these values to re-score outputs or fine-tune your models.
    """

    error: typing.Optional[typing.Any] = pydantic.Field(default=None)
    """
    The error that occurred, if any.
    """

    scores: typing.Optional[typing.Dict[str, typing.Optional[float]]] = pydantic.Field(default=None)
    """
    A dictionary of numeric values (between 0 and 1) to log. The scores should give you a variety of signals that help you determine how accurate the outputs are compared to what you expect and diagnose failures. For example, a summarization app might have one score that tells you how accurate the summary is, and another that measures the word similarity between the generated and grouth truth summary. The word similarity score could help you determine whether the summarization was covering similar concepts or not. You can use these scores to help you sort, filter, and compare logs.
    """

    metadata: typing.Optional[ProjectLogsEventMetadata] = pydantic.Field(default=None)
    """
    A dictionary with additional data about the test example, model outputs, or just about anything else that's relevant, that you can use to help find and analyze examples later. For example, you could log the `prompt`, example's `id`, or anything else that would be useful to slice/dice later. The values in `metadata` can be any JSON-serializable type, but its keys must be strings
    """

    tags: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    A list of tags to log
    """

    metrics: typing.Optional[ProjectLogsEventMetrics] = pydantic.Field(default=None)
    """
    Metrics are numerical measurements tracking the execution of the code that produced the project logs event. Use "start" and "end" to track the time span over which the project logs event was produced
    """

    context: typing.Optional[ProjectLogsEventContext] = pydantic.Field(default=None)
    """
    Context is additional information about the code that produced the project logs event. It is essentially the textual counterpart to `metrics`. Use the `caller_*` attributes to track the location in code which produced the project logs event
    """

    span_id: str = pydantic.Field()
    """
    A unique identifier used to link different project logs events together as part of a full trace. See the [tracing guide](https://www.braintrust.dev/docs/instrument) for full details on tracing
    """

    span_parents: typing.Optional[typing.List[str]] = pydantic.Field(default=None)
    """
    An array of the parent `span_ids` of this project logs event. This should be empty for the root span of a trace, and should most often contain just one parent element for subspans
    """

    root_span_id: str = pydantic.Field()
    """
    A unique identifier for the trace this project logs event belongs to
    """

    is_root: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Whether this span is a root span
    """

    span_attributes: typing.Optional[SpanAttributes] = None
    origin: typing.Optional[ObjectReferenceNullish] = None
    comments: typing.Optional[typing.List[typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Optional list of comments attached to this event
    """

    audit_data: typing.Optional[typing.List[typing.Optional[typing.Any]]] = pydantic.Field(default=None)
    """
    Optional list of audit entries attached to this event
    """

    async_scoring_state: typing_extensions.Annotated[
        typing.Optional[typing.Any],
        FieldMetadata(alias="_async_scoring_state"),
        pydantic.Field(alias="_async_scoring_state", description="The async scoring state for this event"),
    ] = None
    """
    The async scoring state for this event
    """

    facets: typing.Optional[typing.Dict[str, typing.Any]] = pydantic.Field(default=None)
    """
    Facets for categorization (dictionary from facet id to value)
    """

    classifications: typing.Optional[
        typing.Dict[str, typing.Optional[typing.List[ProjectLogsEventClassificationsValueItem]]]
    ] = pydantic.Field(default=None)
    """
    Classifications for this event (dictionary from classification name to items)
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
