

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class SpanAttributesPurpose(enum.StrEnum):
    """
    A special value that indicates the span was generated by a scoring automation
    """

    SCORER = "scorer"

    def visit(self, scorer: typing.Callable[[], T_Result]) -> T_Result:
        if self is SpanAttributesPurpose.SCORER:
            return scorer()
