

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .span_attributes_purpose import SpanAttributesPurpose
from .span_type import SpanType


class SpanAttributes(UniversalBaseModel):
    """
    Human-identifying attributes of the span, such as name, type, etc.
    """

    name: typing.Optional[str] = pydantic.Field(default=None)
    """
    Name of the span, for display purposes only
    """

    type: typing.Optional[SpanType] = None
    purpose: typing.Optional[SpanAttributesPurpose] = pydantic.Field(default=None)
    """
    A special value that indicates the span was generated by a scoring automation
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
