#!/usr/bin/env python3
"""Fail when a second enumeration of the corpus's admissible licences drifts in.

The rule for which licences the fixture corpus admits is stated in exactly one
place, `docs/corpus-licensing.md`. Before that file existed the four licence
names were restated in prose in a dozen documents and stated authoritatively in
none, which is how the set drifted out of date without anything noticing. This
check keeps the single statement single: it reads every tracked Markdown
document in the repository and fails when one of them lists the admissible
licences again.

What is allowed and what is not:

* Prose that REFERS to the rule — "outside the admissible set", "under a
  redistribution-compatible licence", a link to the rule file — is fine, and is
  what the other documents are expected to say.
* Naming ONE licence as a fact about one document — a `CORPUS.md` row's
  `license` column, "AGPL-3.0 (the repository's own, per the GitHub API)" — is
  fine. That is provenance, not the rule.
* A RUN of three or more distinct licence names joined only by list punctuation
  (`/`, `,`, `and`, `or`) is a second copy of the rule, and fails.

Run: `just lint-corpus-licensing` (part of `just check`).
"""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
# Every path this script compares or prints is spelled the way `git ls-files`
# reports one — POSIX separators, on every platform. Holding these as `Path`
# instead is what broke the Windows leg once: `str(Path("docs/x.md"))` is
# `docs\x.md` there, so the rule file stopped excluding itself from its own
# walk and the gate quoted it as its own drift.
RULE = "docs/corpus-licensing.md"
MARKER = "corpus-licence-set:"

# Documents the walk skips, each because it is not this repository's prose about
# its own corpus. Anything else tracked and Markdown is read.
SKIP_PREFIXES = (
    # Vendored third-party llmlint rule documents (`just llmlint-plugins-refresh`).
    "llmlint-plugins/",
    # Retained upstream licence texts, which necessarily name licences.
    "licenses/",
)
# Vendored Fern output — the goldens themselves, not this repository's prose
# about them. `tests/fixtures/CORPUS.md` and its `AGENTS.md` sit above these and
# ARE read: they are exactly where the rule used to be restated.
SKIP_FIXTURE_OUTPUT = re.compile(r"^tests/fixtures/[^/]+/")
SKIP_FILES = (
    # Generated by release-plz from merged commit subjects; not editable prose.
    "CHANGELOG.md",
)

LICENCE = (
    r"(?:"
    r"Apache(?:[-\s]?(?:License[-\s]?)?v?2(?:\.0)?)?"
    r"|MIT|ISC|Zlib|Unlicense"
    r"|BSD(?:[-\s]?\d[-\s]?Clause)?"
    r"|CC0(?:[-\s]?1(?:\.0)?)?"
    r"|CC[-\s]?BY(?:[-\s]?(?:SA|ND|NC))*(?:[-\s]?\d(?:\.\d)?)?"
    r"|AGPL|LGPL|GPL|MPL|EPL|MPL|EUPL|OSL"
    r")(?:[-\s]?\d(?:\.\d)?)?"
)
# Only list punctuation counts as a separator: a slash, a comma, or `and`/`or`.
# Bare whitespace does not, so ordinary prose that happens to name two licences
# in one sentence cannot be mistaken for a list.
SEPARATOR = r"\s*(?:/|,\s*(?:and\s+|or\s+)?|\s+(?:and|or)\s+)\s*"
ENUMERATION = re.compile(
    rf"\b{LICENCE}(?:{SEPARATOR}{LICENCE}\b){{2,}}", re.IGNORECASE
)


def tracked_markdown(root: Path) -> list[str]:
    listing = subprocess.run(
        ["git", "ls-files", "-z", "--", "*.md"],
        cwd=root,
        capture_output=True,
        text=True,
        check=True,
    )
    return [
        path
        for path in listing.stdout.split("\0")
        if path
        and path != RULE
        and path not in SKIP_FILES
        and not path.startswith(SKIP_PREFIXES)
        and not SKIP_FIXTURE_OUTPUT.match(path)
    ]


def enumerations_in(text: str) -> list[tuple[int, str]]:
    found = []
    for match in ENUMERATION.finditer(text):
        # Three DISTINCT names. "Apache 2.0 or Apache-2.0" is one name twice.
        names = {name.lower() for name in re.findall(LICENCE, match.group(), re.I)}
        normalized = {re.sub(r"[-\s]?\d(?:\.\d)?$", "", name) for name in names}
        if len(normalized) >= 3:
            found.append((text[: match.start()].count("\n") + 1, match.group()))
    return found


def check(root: Path) -> list[str]:
    """Every drift finding, as ready-to-read `path:line — text` lines."""
    problems = []
    rule = (root / RULE).read_text(encoding="utf-8")
    if MARKER not in rule:
        problems.append(
            f"{RULE}:0 — the canonical enumeration is gone (no `{MARKER}` marker);"
            " this check has nothing left to hold single"
        )
    elif not enumerations_in(rule):
        problems.append(
            f"{RULE}:0 — the canonical enumeration no longer lists three or more"
            " licences, so the rule is no longer stated where it claims to be"
        )
    for path in tracked_markdown(root):
        text = (root / path).read_text(encoding="utf-8")
        for line, quoted in enumerations_in(text):
            problems.append(f"{path}:{line} — {' '.join(quoted.split())}")
    return problems


def main() -> int:
    problems = check(REPO)
    if not problems:
        return 0
    print(
        "corpus-licensing-drift: the admissible-licence set is enumerated outside"
        f" {RULE}:",
        file=sys.stderr,
    )
    for problem in problems:
        print(f"  {problem}", file=sys.stderr)
    print(
        f"\nState the set only in {RULE} and have these documents refer to it"
        " (a link, or 'the admissible set') instead of listing licence names.",
        file=sys.stderr,
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
