#!/usr/bin/env python3
"""Census the OpenAPI surface every registered golden source *declares*.

`just fixtures-coverage` answers what the goldens reach in `src/`, and
`just fixtures-gaps` answers which generated bytes still diverge. Neither answers
the question this instrument exists for: **which OpenAPI shapes has the corpus
ever seen?** A shape no registered source declares is generator behaviour only
crozier vouches for — the gate stays green whatever crozier does with it — so
knowing the list is the first step to closing it
(`docs/openapi-surface-coverage.md`).

Three rules make the number honest; none of them a `grep` obeys.

* **Source documents only, never generated output.** A specification is what
  *declares* a feature; the emitted Python is not. A census that read an
  `expected/` tree would be measuring the answer instead of the question, so the
  only files opened here are the vendored `tests/fixtures/<name>/openapi.*`
  documents and the `link-ok` documents `scripts/fetch-corpus.sh` fetches into
  `.local/corpus/<name>/` from `tests/fixtures/CORPUS.md`.
* **The OpenAPI object model, not the text.** A text match scores a `trace`
  operation off a path parameter named `trace`, a `name` field off a schema
  property called `name`, and a `type` field off a property called `type` — all
  three shapes are in the vendored corpus today. The walk below knows the keys of
  a Schema Object's `properties` are *names*, the keys of a Paths Object are path
  templates, and the keys of a Responses Object are status codes, so none of them
  can be mistaken for a declared field. Free-form values (`example`, `examples`,
  `default`, `enum`, `const`) are never descended into for the same reason.
* **An unfetched source is a hard failure, not a silent skip.** A `link-ok` row
  whose spec has not been fetched would otherwise report as declaring nothing,
  and 137 of the 169 registered sources are `link-ok`. Pass `--allow-unfetched`
  to downgrade that to a warning, or `--vendored-only` to census the offline half
  on purpose.

The selector grammar, the region boundaries and how a census result becomes a
classified row are `docs/openapi-surface-coverage.md`; they are not restated
here. What only this file knows is the object-model table itself — `OBJECTS` and
`PREDICATES` below are the machine-readable half of that grammar.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Iterator

# ---------------------------------------------------------------------------
# Reading a source document
# ---------------------------------------------------------------------------
#
# The corpus is half JSON and half YAML, and this script has to run inside
# `just check` on the Linux/macOS/Windows matrix with nothing but the standard
# library — the gate installs no Python packages, so PyYAML is not available.
# The loader below therefore reads the block-YAML subset OpenAPI documents are
# written in (mappings, sequences, the three scalar styles, block scalars,
# anchors/aliases/merge keys, flow collections) and REFUSES anything else by
# name and line. Refusing is the point: a census built on a loader that guessed
# would be wrong quietly, which is the one failure mode the instrument cannot
# have.


class DocumentError(Exception):
    """A source document this census cannot read, with the site that stopped it."""

    def __init__(self, path: Path, line: int, message: str) -> None:
        super().__init__(f"{path}:{line}: {message}")
        self.path = path
        self.line = line


_NULL = {"", "~", "null", "Null", "NULL"}
_TRUE = {"true", "True", "TRUE"}
_FALSE = {"false", "False", "FALSE"}
_INT = re.compile(r"[-+]?[0-9]+$")
_FLOAT = re.compile(r"[-+]?(?:[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)(?:[eE][-+]?[0-9]+)?$")
_EXP = re.compile(r"[-+]?[0-9]+[eE][-+]?[0-9]+$")
# A block-mapping key ends at the first ':' that is followed by a space or the
# end of the line: `https://example.test: v` is one key, and `application/json:`
# is another. Anything else (a URL's `://`, a `{$request.body#/x}` template) is
# part of the key or of the value.
_KEY_END = re.compile(r":(?=\s|$)")
_ESCAPES = {
    "0": "\0", "a": "\a", "b": "\b", "t": "\t", "\t": "\t", "n": "\n",
    "v": "\v", "f": "\f", "r": "\r", "e": "\x1b", " ": " ", '"': '"',
    "/": "/", "\\": "\\", "N": "\x85", "_": "\xa0",
}


@dataclass(frozen=True)
class _Line:
    """One significant source line: its index, indentation and comment-free text."""

    index: int
    indent: int
    text: str


class _YamlReader:
    """A strict reader for the block-YAML subset OpenAPI documents are written in."""

    def __init__(self, path: Path, text: str) -> None:
        self.path = path
        self.lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
        if self.lines and self.lines[-1] == "":
            self.lines.pop()  # the file's terminating newline is not a line
        self.pos = 0
        self.anchors: dict[str, Any] = {}

    def fail(self, index: int, message: str) -> None:
        raise DocumentError(self.path, index + 1, message)

    @staticmethod
    def strip_comment(text: str) -> str:
        """Drop a trailing `#` comment, honoring quotes (`$ref: "#/x"` is not one)."""
        quote = ""
        cursor = 0
        while cursor < len(text):
            char = text[cursor]
            if quote:
                if char == "\\" and quote == '"':
                    cursor += 2  # an escape: the next character cannot close the quote
                    continue
                if char == quote:
                    quote = ""
            elif char in "\"'":
                quote = char
            elif char == "#" and (cursor == 0 or text[cursor - 1] in " \t"):
                return text[:cursor]
            cursor += 1
        return text

    def peek(self) -> _Line | None:
        """The next significant line, without consuming it."""
        while self.pos < len(self.lines):
            raw = self.lines[self.pos]
            stripped = self.strip_comment(raw).rstrip()
            if not stripped.strip():
                self.pos += 1
                continue
            indent = len(stripped) - len(stripped.lstrip(" "))
            if "\t" in stripped[: len(stripped) - len(stripped.lstrip())]:
                self.fail(self.pos, "tabs cannot indent YAML; re-indent with spaces")
            return _Line(self.pos, indent, stripped[indent:])
        return None

    def load(self) -> Any:
        first = self.peek()
        if first is None:
            self.fail(0, "the document is empty")
        if first.text.startswith("%"):
            self.fail(first.index, "YAML directives are not supported")
        if first.text == "---":
            self.pos += 1
        value = self.parse_block(0)
        trailing = self.peek()
        if trailing is not None and trailing.text not in {"...", "---"}:
            self.fail(trailing.index, f"unexpected content after the document: {trailing.text!r}")
        if trailing is not None and trailing.text == "---":
            self.fail(
                trailing.index,
                "the file holds more than one YAML document; an OpenAPI source is one document",
            )
        return value

    def parse_block(self, min_indent: int) -> Any:
        """Parse the block starting at the next significant line."""
        line = self.peek()
        if line is None or line.indent < min_indent:
            return None
        if line.text == "-" or line.text.startswith("- "):
            return self.parse_sequence(line.indent)
        if line.text == "?" or line.text.startswith("? "):
            self.fail(line.index, "explicit `? ` mapping keys are not supported")
        if line.text == ":" or line.text.startswith(": "):
            self.fail(line.index, "an empty mapping key is not supported")
        if self.split_key(line.text) is None:
            # Not an entry: a scalar written on its own line(s) under its key, the
            # way real documents wrap a long `description:`.
            self.pos = line.index + 1
            return self.parse_value(line.text, line.indent - 1, line.index)
        return self.parse_mapping(line.indent)

    def parse_mapping(self, indent: int) -> dict[Any, Any]:
        mapping: dict[Any, Any] = {}
        merges: list[Any] = []
        while True:
            line = self.peek()
            if line is None or line.indent < indent:
                break
            if line.indent == 0 and line.text in {"---", "..."}:
                break  # a document marker ends this block; load() reports it
            if line.indent > indent:
                self.fail(line.index, "unexpected indentation inside a block mapping")
            if line.text == "-" or line.text.startswith("- "):
                self.fail(line.index, "a sequence item where a mapping key was expected")
            if line.text == ":" or line.text.startswith(": "):
                self.fail(line.index, "an empty mapping key is not supported")
            split = self.split_key(line.text)
            if split is None:
                self.fail(line.index, f"expected a `key: value` mapping entry, got {line.text!r}")
            key_text, rest = split
            key = self.parse_key(line, key_text)
            self.pos = line.index + 1
            value = self.parse_value(rest, indent, line.index)
            if key == "<<":
                merges.append(value)
            else:
                mapping[key] = value
        for merged in merges:
            for source in merged if isinstance(merged, list) else [merged]:
                if isinstance(source, dict):
                    for key, value in source.items():
                        mapping.setdefault(key, value)
        return mapping

    def parse_sequence(self, indent: int) -> list[Any]:
        items: list[Any] = []
        while True:
            line = self.peek()
            if line is None or line.indent < indent:
                break
            if line.indent == 0 and line.text in {"---", "..."}:
                break  # a document marker ends this block; load() reports it
            if line.indent > indent:
                self.fail(line.index, "unexpected indentation inside a block sequence")
            if not (line.text == "-" or line.text.startswith("- ")):
                break
            rest = line.text[1:].lstrip(" ")
            if rest == "":
                self.pos = line.index + 1
                items.append(self.parse_block(indent + 1))
                continue
            if rest.startswith("- ") or rest == "-" or self.split_key(rest) is not None:
                # A nested collection opening on the dash line: blank the dash so
                # the item's own lines all sit at one indentation, then parse it
                # as an ordinary block. Rewriting the line (rather than threading
                # a synthetic first line through the parser) keeps every later
                # line of the item on its real source index, so failures still
                # name the line the reader would look at.
                raw = self.lines[line.index]
                self.lines[line.index] = raw[: line.indent] + " " + raw[line.indent + 1 :]
                items.append(self.parse_block(indent + 1))
                continue
            self.pos = line.index + 1
            items.append(self.parse_value(rest, indent, line.index))
        return items

    def split_key(self, text: str) -> tuple[str, str] | None:
        """Split `key: value` into its halves, or None when `text` is not an entry."""
        if text[0] in "\"'":
            end = self.scan_quoted(text, 0)
            if end is None or not (text[end:] == ":" or text[end:].startswith(": ")):
                return None
            return text[:end], text[end + 1 :].lstrip(" ")
        if text.startswith(("[", "{", "&", "*", "|", ">")):
            return None
        match = _KEY_END.search(text)
        if match is None or not text[: match.start()].strip():
            return None  # no `key:` at all, or the empty key `: value`
        return text[: match.start()], text[match.end() :].lstrip(" ")

    def parse_key(self, line: _Line, key_text: str) -> Any:
        if key_text.startswith("? "):
            self.fail(line.index, "explicit `? ` mapping keys are not supported")
        if key_text.startswith("!"):
            self.fail(line.index, "YAML tags are not supported")
        if key_text[0] in "\"'":
            end = self.scan_quoted(key_text, 0)
            assert end is not None  # split_key only returns a terminated quote
            return self.unquote(line, key_text[:end])
        return self.scalar(key_text.rstrip())

    def parse_value(self, rest: str, indent: int, index: int) -> Any:
        """The value of a mapping entry or sequence item declared on line `index`."""
        anchor = None
        if rest.startswith("&"):
            name, _, remainder = rest.partition(" ")
            anchor = name[1:]
            rest = remainder.lstrip(" ")
        if rest.startswith("!"):
            self.fail(index, "YAML tags are not supported")
        if rest.startswith("*"):
            name = rest[1:].strip()
            if name not in self.anchors:
                self.fail(index, f"alias *{name} has no anchor")
            value: Any = self.anchors[name]
        elif rest == "":
            following = self.peek()
            # A block sequence may sit at its key's own indentation, and most
            # generator-written documents do exactly that; anything else has to be
            # more indented than the key to belong to it.
            nested = following is not None and (
                following.indent > indent
                or (
                    following.indent == indent
                    and (following.text == "-" or following.text.startswith("- "))
                )
            )
            value = self.parse_block(following.indent) if nested else None
        elif rest[0] in "|>":
            value = self.block_scalar(rest, indent, index)
        elif rest[0] in "[{":
            value = self.flow(rest, index)
        else:
            value = self.scalar_value(rest, indent, index)
        if anchor is not None:
            self.anchors[anchor] = value
        return value

    def block_scalar(self, header: str, indent: int, index: int) -> str:
        style, header = header[0], header[1:].strip()
        chomp = ""
        explicit = 0
        for char in header:
            if char in "+-":
                chomp = char
            elif char.isdigit():
                explicit = int(char)
            else:
                self.fail(index, f"unsupported block scalar header {header!r}")
        body: list[str] = []
        block_indent = indent + explicit if explicit else 0
        cursor = index + 1
        while cursor < len(self.lines):
            raw = self.lines[cursor]
            if raw.strip() == "":
                body.append("")
                cursor += 1
                continue
            line_indent = len(raw) - len(raw.lstrip(" "))
            if line_indent <= indent:
                break
            if not block_indent:
                block_indent = line_indent
            if line_indent < block_indent:
                break
            body.append(raw[block_indent:])
            cursor += 1
        self.pos = cursor
        trailing = 0
        while body and body[-1] == "":
            body.pop()
            trailing += 1
        text = "\n".join(body) if style == "|" else self.fold(body)
        if chomp == "-" or not text:
            return text
        return text + "\n" * (1 + trailing if chomp == "+" else 1)

    @staticmethod
    def fold(body: list[str]) -> str:
        """Fold a `>` scalar: a break between two lines becomes a space, a run of
        empty lines becomes that many breaks, and a more-indented line keeps its
        own breaks."""
        out: list[str] = []
        folding = False
        cursor = 0
        while cursor < len(body):
            entry = body[cursor]
            if entry == "":
                run = 0
                while cursor < len(body) and body[cursor] == "":
                    run += 1
                    cursor += 1
                out.append("\n" * run)
                folding = False
                continue
            if entry.startswith(" "):
                out.append(("\n" if folding else "") + entry)
                folding = False
            else:
                out.append((" " if folding else "") + entry)
                folding = True
            cursor += 1
        return "".join(out)

    def scalar_value(self, rest: str, indent: int, index: int) -> Any:
        """A quoted or plain scalar, folding any more-indented continuation lines."""
        if rest[0] in "\"'":
            end = self.scan_quoted(rest, 0)
            if end is not None:
                trailing = rest[end:].strip()
                if trailing:
                    self.fail(index, f"unexpected text after a quoted scalar: {trailing!r}")
                return self.unquote(self.line_at(index), rest[:end])
            return self.multiline_quoted(rest, indent, index)
        pieces = [rest]
        cursor = index + 1
        while cursor < len(self.lines):
            candidate = self.strip_comment(self.lines[cursor]).rstrip()
            if not candidate.strip():
                break
            candidate_indent = len(candidate) - len(candidate.lstrip(" "))
            if candidate_indent <= indent:
                break
            pieces.append(candidate.strip())
            cursor += 1
        self.pos = cursor
        if len(pieces) == 1:
            return self.scalar(rest.strip())
        return " ".join(pieces)

    def multiline_quoted(self, rest: str, indent: int, index: int) -> str:
        """A quoted scalar whose closing quote is on a later line.

        The source line breaks are folded away BEFORE the escapes are read, which
        is the only order that survives a document like slurmdb-rest's: a
        double-quoted description holding both real `\\n` escapes and a trailing
        `\\` that cancels the source break. Folding afterwards would eat the
        escapes along with the breaks.
        """
        quote = rest[0]
        buffer = rest.rstrip()
        blanks = 0
        cursor = index + 1
        while cursor < len(self.lines):
            piece = self.lines[cursor].strip()
            cursor += 1
            if not piece:
                blanks += 1
                continue
            if quote == '"' and (len(buffer) - len(buffer.rstrip("\\"))) % 2 == 1:
                buffer = buffer[:-1] + piece  # a trailing backslash cancels the break
            elif blanks:
                buffer = f"{buffer}{chr(10) * blanks}{piece}"
            else:
                buffer = f"{buffer} {piece}"
            blanks = 0
            end = self.scan_quoted(buffer, 0)
            if end is not None:
                trailing = buffer[end:].strip()
                if trailing:
                    self.fail(index, f"unexpected text after a quoted scalar: {trailing!r}")
                self.pos = cursor
                return self.unquote(self.line_at(index), buffer[:end])
        self.fail(index, "a quoted scalar is never closed")
        raise AssertionError("unreachable")  # pragma: no cover - fail() raises

    def line_at(self, index: int) -> _Line:
        raw = self.strip_comment(self.lines[index]).rstrip()
        indent = len(raw) - len(raw.lstrip(" "))
        return _Line(index, indent, raw[indent:])

    @staticmethod
    def scan_quoted(text: str, start: int) -> int | None:
        """The index just past the quoted scalar at `start`, or None if unterminated."""
        quote = text[start]
        cursor = start + 1
        while cursor < len(text):
            char = text[cursor]
            if quote == '"' and char == "\\":
                cursor += 2
                continue
            if char == quote:
                if quote == "'" and text[cursor + 1 : cursor + 2] == "'":
                    cursor += 2
                    continue
                return cursor + 1
            cursor += 1
        return None

    def unquote(self, line: _Line, text: str) -> str:
        if text[0] == "'":
            return text[1:-1].replace("''", "'")
        body = text[1:-1]
        out: list[str] = []
        cursor = 0
        while cursor < len(body):
            char = body[cursor]
            if char != "\\":
                out.append(char)
                cursor += 1
                continue
            marker = body[cursor + 1 : cursor + 2]
            if marker in ("x", "u", "U"):
                width = {"x": 2, "u": 4, "U": 8}[marker]
                digits = body[cursor + 2 : cursor + 2 + width]
                try:
                    out.append(chr(int(digits, 16)))
                except ValueError:
                    self.fail(line.index, f"invalid \\{marker} escape {digits!r}")
                cursor += 2 + width
                continue
            if marker == "\n":
                cursor += 2
                continue
            if marker not in _ESCAPES:
                self.fail(line.index, f"unsupported escape \\{marker}")
            out.append(_ESCAPES[marker])
            cursor += 2
        return "".join(out)

    def flow(self, rest: str, index: int) -> Any:
        """A flow collection, gathered across lines until its brackets balance."""
        buffer = rest
        cursor = index + 1
        while self.flow_depth(buffer) > 0 and cursor < len(self.lines):
            buffer = f"{buffer} {self.strip_comment(self.lines[cursor]).strip()}"
            cursor += 1
        if self.flow_depth(buffer) != 0:
            self.fail(index, "a flow collection is never closed")
        self.pos = cursor
        value, end = self.flow_node(buffer, 0, index)
        if buffer[end:].strip():
            self.fail(index, f"unexpected text after a flow collection: {buffer[end:].strip()!r}")
        return value

    def flow_depth(self, text: str) -> int:
        depth = 0
        cursor = 0
        while cursor < len(text):
            char = text[cursor]
            if char in "\"'":
                end = self.scan_quoted(text, cursor)
                cursor = end if end is not None else len(text)
                continue
            if char in "[{":
                depth += 1
            elif char in "]}":
                depth -= 1
            cursor += 1
        return depth

    def flow_node(self, text: str, start: int, index: int) -> tuple[Any, int]:
        cursor = self.skip_space(text, start)
        if cursor >= len(text):
            self.fail(index, "a flow collection ends where a value was expected")
        char = text[cursor]
        if char == "[":
            return self.flow_collection(text, cursor, index, "]")
        if char == "{":
            return self.flow_collection(text, cursor, index, "}")
        if char in "\"'":
            end = self.scan_quoted(text, cursor)
            if end is None:
                self.fail(index, "a quoted scalar in a flow collection is never closed")
            return self.unquote(self.line_at(index), text[cursor:end]), end
        end = cursor
        while end < len(text) and text[end] not in ",]}:":
            end += 1
        raw = text[cursor:end].strip()
        if raw.startswith("*"):
            name = raw[1:]
            if name not in self.anchors:
                self.fail(index, f"alias *{name} has no anchor")
            return self.anchors[name], end
        return self.scalar(raw), end

    def flow_collection(self, text: str, start: int, index: int, closer: str) -> tuple[Any, int]:
        items: list[Any] = []
        mapping: dict[Any, Any] = {}
        cursor = start + 1
        while True:
            entered = cursor
            cursor = self.skip_space(text, cursor)
            if cursor >= len(text):
                self.fail(index, "a flow collection is never closed")
            if text[cursor] == closer:
                return (mapping if closer == "}" else items), cursor + 1
            value, cursor = self.flow_node(text, cursor, index)
            cursor = self.skip_space(text, cursor)
            if cursor < len(text) and text[cursor] == ":":
                entry, cursor = self.flow_node(text, cursor + 1, index)
                mapping[value] = entry
            else:
                items.append(value)
            cursor = self.skip_space(text, cursor)
            if cursor < len(text) and text[cursor] == ",":
                cursor += 1
            if cursor <= entered:
                # `flow_node` stops at `,]}:` and so returns without consuming a
                # delimiter it does not recognise here. Looping again from the
                # same cursor would append forever and exhaust memory rather than
                # report anything, so a round that consumed nothing is a parse
                # error naming where it stalled.
                self.fail(index, f"a flow collection stalls at {text[cursor:cursor + 1]!r}")

    @staticmethod
    def skip_space(text: str, cursor: int) -> int:
        while cursor < len(text) and text[cursor] in " \t":
            cursor += 1
        return cursor

    @staticmethod
    def scalar(text: str) -> Any:
        """Resolve a plain scalar to the type YAML's core schema gives it."""
        if text in _NULL:
            return None
        if text in _TRUE:
            return True
        if text in _FALSE:
            return False
        if _INT.match(text):
            return int(text)
        if _FLOAT.match(text) or _EXP.match(text):
            return float(text)
        return text


def load_document(path: Path) -> Any:
    """Parse one OpenAPI source document into plain Python objects."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as error:
        raise DocumentError(path, 0, f"cannot be read: {error}") from error
    if text.startswith("﻿"):
        text = text[1:]
    if path.suffix == ".json":
        try:
            return json.loads(text)
        except json.JSONDecodeError as error:
            raise DocumentError(path, error.lineno, f"is not valid JSON: {error.msg}") from error
    return _YamlReader(path, text).load()


# ---------------------------------------------------------------------------
# The OpenAPI object model
# ---------------------------------------------------------------------------

ONE, LIST, MAP = "one", "list", "map"


@dataclass(frozen=True)
class Child:
    """A field that carries further OpenAPI objects, and how they are held."""

    container: str
    kind: str


@dataclass(frozen=True)
class ObjectKind:
    """One OpenAPI object: which fields it declares and how a selector names it.

    `anchor` is the half of the selector grammar that cannot be derived from the
    specification: an anchor kind heads its own selector (`response.links`), and
    a non-anchor kind extends its parent's instead (`info.license.identifier`,
    `mediaType.encoding.headers`). The two lists are closed and are stated in
    `docs/openapi-surface-coverage.md`; they are here because the walk needs them.
    """

    name: str
    anchor: bool
    fields: dict[str, Child | None]
    free_map: Child | None = None


def _kind(
    name: str,
    anchor: bool,
    fields: dict[str, Child | None],
    free_map: Child | None = None,
) -> ObjectKind:
    return ObjectKind(name=name, anchor=anchor, fields=fields, free_map=free_map)


_SCHEMA_FIELDS: dict[str, Child | None] = {
    # 3.0 and 3.1 alike
    "$ref": None, "title": None, "multipleOf": None, "maximum": None,
    "exclusiveMaximum": None, "minimum": None, "exclusiveMinimum": None,
    "maxLength": None, "minLength": None, "pattern": None, "maxItems": None,
    "minItems": None, "uniqueItems": None, "maxProperties": None,
    "minProperties": None, "required": None, "enum": None, "type": None,
    "description": None, "format": None, "default": None, "readOnly": None,
    "writeOnly": None, "example": None, "deprecated": None,
    "allOf": Child(LIST, "schema"), "oneOf": Child(LIST, "schema"),
    "anyOf": Child(LIST, "schema"), "not": Child(ONE, "schema"),
    "items": Child(ONE, "schema"), "properties": Child(MAP, "schema"),
    "additionalProperties": Child(ONE, "schema"),
    "discriminator": Child(ONE, "discriminator"), "xml": Child(ONE, "xml"),
    "externalDocs": Child(ONE, "externalDocs"),
    # 3.0 only
    "nullable": None,
    # 3.1 (JSON Schema 2020-12)
    "$schema": None, "$id": None, "$anchor": None, "$comment": None,
    "$dynamicRef": None, "$dynamicAnchor": None, "$vocabulary": None,
    "const": None, "examples": None, "contentEncoding": None,
    "contentMediaType": None, "dependentRequired": None, "maxContains": None,
    "minContains": None,
    "$defs": Child(MAP, "schema"), "definitions": Child(MAP, "schema"),
    "prefixItems": Child(LIST, "schema"), "contains": Child(ONE, "schema"),
    "patternProperties": Child(MAP, "schema"),
    "propertyNames": Child(ONE, "schema"),
    "unevaluatedItems": Child(ONE, "schema"),
    "unevaluatedProperties": Child(ONE, "schema"),
    "if": Child(ONE, "schema"), "then": Child(ONE, "schema"),
    "else": Child(ONE, "schema"), "dependentSchemas": Child(MAP, "schema"),
    "contentSchema": Child(ONE, "schema"),
}

_PARAMETER_FIELDS: dict[str, Child | None] = {
    "description": None, "required": None, "deprecated": None,
    "allowEmptyValue": None, "style": None, "explode": None,
    "allowReserved": None, "example": None,
    "schema": Child(ONE, "schema"), "examples": Child(MAP, "example"),
    "content": Child(MAP, "mediaType"),
}

OBJECTS: dict[str, ObjectKind] = {
    "openapi": _kind("openapi", True, {
        "openapi": None, "jsonSchemaDialect": None,
        "info": Child(ONE, "info"), "servers": Child(LIST, "server"),
        "paths": Child(ONE, "paths"), "webhooks": Child(MAP, "pathItem"),
        "components": Child(ONE, "components"),
        "security": Child(LIST, "securityRequirement"),
        "tags": Child(LIST, "tag"), "externalDocs": Child(ONE, "externalDocs"),
    }),
    "info": _kind("info", True, {
        "title": None, "summary": None, "description": None,
        "termsOfService": None, "version": None,
        "contact": Child(ONE, "contact"), "license": Child(ONE, "license"),
    }),
    "contact": _kind("contact", False, {"name": None, "url": None, "email": None}),
    "license": _kind("license", False, {"name": None, "identifier": None, "url": None}),
    "server": _kind("server", True, {
        "url": None, "description": None, "variables": Child(MAP, "serverVariable"),
    }),
    "serverVariable": _kind("serverVariable", False, {
        "enum": None, "default": None, "description": None,
    }),
    "components": _kind("components", True, {
        "schemas": Child(MAP, "schema"), "responses": Child(MAP, "response"),
        "parameters": Child(MAP, "parameter"), "examples": Child(MAP, "example"),
        "requestBodies": Child(MAP, "requestBody"), "headers": Child(MAP, "header"),
        "securitySchemes": Child(MAP, "securityScheme"), "links": Child(MAP, "link"),
        "callbacks": Child(MAP, "callback"), "pathItems": Child(MAP, "pathItem"),
    }),
    # The keys of a Paths Object are path templates, and the keys of a Callback
    # Object are runtime expressions: names, never fields. `free_map` is what
    # keeps them out of the census.
    "paths": _kind("paths", False, {}, free_map=Child(ONE, "pathItem")),
    "callback": _kind("callback", True, {}, free_map=Child(ONE, "pathItem")),
    "pathItem": _kind("pathItem", True, {
        "$ref": None, "summary": None, "description": None,
        "get": Child(ONE, "operation"), "put": Child(ONE, "operation"),
        "post": Child(ONE, "operation"), "delete": Child(ONE, "operation"),
        "options": Child(ONE, "operation"), "head": Child(ONE, "operation"),
        "patch": Child(ONE, "operation"), "trace": Child(ONE, "operation"),
        "servers": Child(LIST, "server"), "parameters": Child(LIST, "parameter"),
    }),
    "operation": _kind("operation", True, {
        "tags": None, "summary": None, "description": None, "operationId": None,
        "deprecated": None,
        "externalDocs": Child(ONE, "externalDocs"),
        "parameters": Child(LIST, "parameter"),
        "requestBody": Child(ONE, "requestBody"),
        "responses": Child(ONE, "responses"),
        "callbacks": Child(MAP, "callback"),
        "security": Child(LIST, "securityRequirement"),
        "servers": Child(LIST, "server"),
    }),
    "externalDocs": _kind("externalDocs", True, {"description": None, "url": None}),
    "parameter": _kind("parameter", True, {"name": None, "in": None, **_PARAMETER_FIELDS}),
    "header": _kind("header", True, dict(_PARAMETER_FIELDS)),
    "requestBody": _kind("requestBody", True, {
        "description": None, "required": None, "content": Child(MAP, "mediaType"),
    }),
    "mediaType": _kind("mediaType", True, {
        "example": None, "schema": Child(ONE, "schema"),
        "examples": Child(MAP, "example"), "encoding": Child(MAP, "encoding"),
    }),
    "encoding": _kind("encoding", False, {
        "contentType": None, "style": None, "explode": None, "allowReserved": None,
        "headers": Child(MAP, "header"),
    }),
    # The keys of a Responses Object are status codes; only `default` is a field.
    "responses": _kind("responses", False, {
        "default": Child(ONE, "response"),
    }, free_map=Child(ONE, "response")),
    "response": _kind("response", True, {
        "description": None, "headers": Child(MAP, "header"),
        "content": Child(MAP, "mediaType"), "links": Child(MAP, "link"),
    }),
    "example": _kind("example", True, {
        "summary": None, "description": None, "value": None, "externalValue": None,
    }),
    "link": _kind("link", True, {
        "operationRef": None, "operationId": None, "parameters": None,
        "requestBody": None, "description": None, "server": Child(ONE, "server"),
    }),
    "tag": _kind("tag", True, {
        "name": None, "description": None, "externalDocs": Child(ONE, "externalDocs"),
    }),
    "schema": _kind("schema", True, _SCHEMA_FIELDS),
    "discriminator": _kind("discriminator", False, {"propertyName": None, "mapping": None}),
    "xml": _kind("xml", False, {
        "name": None, "namespace": None, "prefix": None, "attribute": None,
        "wrapped": None,
    }),
    "securityScheme": _kind("securityScheme", True, {
        "type": None, "description": None, "name": None, "in": None,
        "scheme": None, "bearerFormat": None, "openIdConnectUrl": None,
        "flows": Child(ONE, "oauthFlows"),
    }),
    "oauthFlows": _kind("oauthFlows", False, {
        "implicit": Child(ONE, "oauthFlow"), "password": Child(ONE, "oauthFlow"),
        "clientCredentials": Child(ONE, "oauthFlow"),
        "authorizationCode": Child(ONE, "oauthFlow"),
    }),
    "oauthFlow": _kind("oauthFlow", False, {
        "authorizationUrl": None, "tokenUrl": None, "refreshUrl": None, "scopes": None,
    }),
    # The keys of a Security Requirement Object are scheme names declared in
    # `components.securitySchemes`, so the object contributes no selector of its own.
    "securityRequirement": _kind("securityRequirement", True, {}),
    "reference": _kind("reference", True, {
        "$ref": None, "summary": None, "description": None,
    }),
}

# The closed list of fields that also emit a valued selector, `<selector>=<value>`.
# A field is here when its value is drawn from a small, specification-defined set
# that a region needs to census one member of at a time (`parameter.in=cookie`);
# `schema.format` is here despite being an open set because a format is exactly
# the kind of shape a generator either maps to a Python type or drops.
VALUED = {
    "openapi.openapi", "parameter.in", "parameter.style", "header.style",
    "mediaType.encoding.style", "schema.type", "schema.format",
    "securityScheme.type", "securityScheme.in", "securityScheme.scheme",
    "schema.additionalProperties",
}

# The one exception to "a boolean value emits no valued selector".
# `Census.declared_here` skips `bool` for every other member of `VALUED`, because
# a boolean field is written for its presence and `parameter.required=true` would
# be a second spelling of `parameter.required`. `schema.additionalProperties` is
# the field that is a *schema or a boolean*, and which boolean it carries is what
# `src/ir.rs`'s `is_inline_struct` and `is_map` branch on — `false` closes the
# object and hoists a model, `true` opens a map — so its two boolean spellings are
# two shapes rather than one presence. A schema-valued `additionalProperties`
# emits no valued selector at all, exactly as an open set would not.
VALUED_BOOL = {"schema.additionalProperties"}

# `$ref` inside these kinds is a declared field of the kind itself (a JSON Schema
# keyword, a Path Item reference); anywhere else a `$ref` makes the node a
# Reference Object, which is counted as one and not descended into.
REF_TRANSPARENT = {"schema", "pathItem"}

# The closed list of *predicate* selectors, `<selector>:<predicate>` — the third
# kind of selector, and the only place that list is declared. A field selector
# says a field was written and a valued selector says which member of a closed set
# it was written with; neither can express a property of a field's array members,
# a comparison between two documents' worth of one field's values, or anything at
# all about the map keys the grammar deliberately excludes as *names*. Every
# member below is one of those shapes. `docs/openapi-surface-coverage.md`'s
# `### The selector grammar` restates them for a reader, and
# `tests/surface_census_test.py` reconciles the two lists the way it already
# reconciles `VALUED`.
#
# Every member is **node-local**: it is decided from one object-model node's own
# declared fields and their values, with no `$ref` resolution and no
# document-scope comparison — except the three that were declared before the
# family was named, `operation.operationId:duplicate` and the two
# `normalized-collision` spellings, which compare one document's own values
# against each other and say so in their own sentence. A predicate that would need the schema a `$ref` points
# at is not a member of this family and is not declared here; those shapes are the
# enumeration holes `docs/openapi-surface-coverage.md`'s case analysis names
# H-ref-target, H-pointer-target and H-pointer-nesting.
PREDICATES = {
    "operation.tags:multiple": (
        "one per Operation Object whose `tags` array holds more than one member"
    ),
    "operation.operationId:duplicate": (
        "one per Operation Object whose `operationId` value is declared by more than "
        "one Operation Object of the same document, so a value written twice counts two"
    ),
    "openapi.paths:normalized-collision": (
        "one per Paths Object key that collides with at least one other key of the "
        "same document after path-template-name normalization, so a two-key collision "
        "counts two"
    ),
    "openapi.paths:templated-key": (
        "one per Paths Object key carrying at least one `{expression}` template "
        "expression, so a key with two counts one"
    ),
    "openapi.paths:several-template-expressions": (
        "one per Paths Object key carrying more than one `{expression}` template "
        "expression, so a key with one counts none and a key with three counts one"
    ),
    "components.schemas:normalized-collision": (
        "one per `components.schemas` key that collides with at least one other key of "
        "the same document after class-name normalization, so a two-key collision "
        "counts two"
    ),
    # The node-local family below is read off the arms of the six blind functions
    # of `src/ir.rs`, one member per property those arms test that a field or a
    # valued selector cannot say. Each is decided from the node in front of it.
    "schema.type:primary=array": (
        "one per Schema Object whose `type` names `array` first among its non-`null` "
        "members, which is the member `TypeField::primary` of `src/openapi.rs` reads, "
        "so a 3.1 `type: [string, array]` counts none and `type: [null, array]` counts "
        "one"
    ),
    "schema.properties:non-empty": (
        "one per Schema Object whose `properties` map holds at least one entry, so a "
        "declared-but-empty `properties: {}` counts none"
    ),
    "schema.oneOf:sole-non-null-member": (
        "one per Schema Object whose `oneOf` array holds exactly one member whose "
        "primary type is not `null`, beside at least one member whose primary type is "
        "`null`"
    ),
    "schema.anyOf:sole-non-null-member": (
        "one per Schema Object whose `anyOf` array holds exactly one member whose "
        "primary type is not `null`, beside at least one member whose primary type is "
        "`null`"
    ),
    "schema.oneOf:sole-member": (
        "one per Schema Object whose `oneOf` array holds exactly one member"
    ),
    "schema.anyOf:sole-member": (
        "one per Schema Object whose `anyOf` array holds exactly one member"
    ),
    "schema.enum:string-valued": (
        "one per Schema Object whose `enum` array yields at least one string value "
        "under crozier's own `string_enum_values` — the schema is `type: string`, or "
        "declares no `type` and every member is a string"
    ),
    "schema.const:string-valued": (
        "one per Schema Object whose `const` value yields a string under that same "
        "reading, which is the spelling `string_enum_values` falls back to when no "
        "`enum` is written"
    ),
    "openapi.paths:leading-literal-segment": (
        "one per Paths Object key whose first non-empty `/`-separated segment is not "
        "wholly a `{expression}` template expression, which is the segment "
        "`src/ir.rs`'s `path_group` returns"
    ),
    "openapi.paths:template-before-literal-segment": (
        "one per Paths Object key whose first non-empty segment is wholly a template "
        "expression and which carries a later segment that is not, so `path_group` "
        "skips one to return the other"
    ),
    "openapi.paths:all-segments-templated": (
        "one per Paths Object key with no non-empty segment that is not wholly a "
        "template expression, so a key whose every segment is templated counts one "
        "and so does a key carrying no segment at all"
    ),
    # The pointer-form family below is read off the arms of `ref_to_class` and of
    # `resolve_schema_pointer`'s two string-decided cases. Each is decided from one
    # `$ref` value's own segment structure — the six lexical ones from the string
    # alone, and `schema.$ref:undeclared-component-head` by comparing that string's
    # head against the document's own `components.schemas` keys, which is the
    # document-scope comparison `components.schemas:normalized-collision` already
    # makes. None of them opens the schema a pointer addresses: that is the
    # resolving walk `docs/openapi-surface-coverage.md` names H-pointer-nesting.
    "schema.$ref:cross-document": (
        "one per Schema Object whose `$ref` names another document — the value "
        "carries a non-empty part before its `#`, or no `#` at all — so "
        "`./other.yaml#/components/schemas/Author` counts and `#/definitions/Foo` "
        "does not"
    ),
    "schema.$ref:same-document-foreign-pointer": (
        "one per Schema Object whose `$ref` points inside its own document but "
        "outside `components.schemas`, so `#/definitions/Foo` and "
        "`#/components/parameters/Page` count and `#/components/schemas/Foo` does "
        "not"
    ),
    "schema.$ref:nested-properties": (
        "one per Schema Object whose `$ref` is a `#/components/schemas/` pointer "
        "carrying a `properties` segment with a segment after it, at a position the "
        "`ref_to_class` walk reads, so a pointer carrying two counts one"
    ),
    "schema.$ref:nested-items": (
        "one per Schema Object whose `$ref` is a `#/components/schemas/` pointer "
        "carrying an `items` segment at a position that same walk reads"
    ),
    "schema.$ref:composition-index": (
        "one per Schema Object whose `$ref` is a `#/components/schemas/` pointer "
        "carrying an `allOf`, `oneOf` or `anyOf` segment at a position that same "
        "walk reads"
    ),
    "schema.$ref:unnamed-segment": (
        "one per Schema Object whose `$ref` is a `#/components/schemas/` pointer "
        "carrying, at a position that same walk reads, a segment that names none of "
        "those five — a trailing `properties` included, since `ref_to_class` reads "
        "one as a name it cannot use rather than as a nesting step"
    ),
    "schema.$ref:undeclared-component-head": (
        "one per Schema Object whose `$ref` is a `#/components/schemas/` pointer "
        "whose head segment names no key of the same document's own "
        "`components.schemas`"
    ),
}

# The closed list of *conjunction* selectors, the fourth kind — a shape that is a
# combination of fields rather than one field, written with the two composition
# operators over the selectors above: `&` joins members declared at one
# object-model node, `>` descends into the object a field's value is. A count is
# one per node at the leftmost position, exactly the count rule the three kinds
# above already have.
#
# The list is closed because the cross-product of the grammar is not: four schema
# fields already spell fifteen non-empty combinations before nesting, and
# unbounded with it. What bounds this list instead is the branch structure of the
# six functions of `src/ir.rs` the goldens are blind to — a conjunction is worth
# enumerating iff two source documents differing only in it take different paths
# through one of `resolve_schema_pointer`, `nested_array_element`,
# `hoist_union_variant`, `ref_to_class`, `prop_type_ref` or `path_group`. Each
# entry below is read off one branch of one of those functions; the case analysis
# deriving them, and the enumeration holes for the branches no selector kind can
# express, are `docs/openapi-surface-coverage.md`'s
# `### The six blind regions of src/ir.rs, case by case`, which restates this
# table for a reader. `tests/surface_census_test.py` reconciles the two the way it
# already reconciles `VALUED` and `PREDICATES`.
#
# A branch earns a row only when a conjunction names it *exactly* — when the nodes
# this census counts and the nodes the generator sends down that branch differ
# only where another case of the same function claims them. That is what bounds
# the list to the entries below rather than to what the operators can spell: an
# arm reading something no member can say is a hole instead, and a row that
# pretended otherwise would count documents the generator sends elsewhere. Which
# properties a member can say is `PREDICATES`' business, not this table's — a
# collection's emptiness, an `enum`'s value types and which member of a `type`
# array comes first each have a predicate now, so the conditions those arms read
# compose here like any other member, and what is left a hole is an arm reading a
# `$ref`'s target, a comparison across the document, or the *absence* of a
# declaration.
#
# Nothing here counts: an entry is its spelling and one sentence saying what it
# counts. The count is composed from the entry's own members under the `&` and `>`
# rules, by `Census.conjunction_holds` below, so adding a row adds no code.
CONJUNCTIONS = {
    "schema.anyOf>schema.$ref": "one per Schema Object one of whose `anyOf` members is a Reference Object",
    "schema.anyOf>schema.allOf": "one per Schema Object one of whose `anyOf` members declares `allOf`",
    "schema.items>schema.$ref": "one per Schema Object whose `items` value is a Reference Object",
    "schema.items>schema.anyOf": "one per Schema Object whose `items` value declares `anyOf`",
    "schema.items>schema.oneOf": "one per Schema Object whose `items` value declares `oneOf`",
    "schema.oneOf>schema.$ref": "one per Schema Object one of whose `oneOf` members is a Reference Object",
    "schema.oneOf>schema.allOf": "one per Schema Object one of whose `oneOf` members declares `allOf`",
    "schema.properties>schema.anyOf": "one per Schema Object one of whose properties declares `anyOf`",
    "schema.properties>schema.oneOf": "one per Schema Object one of whose properties declares `oneOf`",
    "schema.items>schema.type:primary=array": "one per Schema Object whose `items` value declares `array` as its primary type",
    "schema.items>schema.properties:non-empty": "one per Schema Object whose `items` value declares a non-empty `properties` map",
    "schema.items>schema.additionalProperties=false": "one per Schema Object whose `items` value declares `additionalProperties: false`",
    "schema.oneOf>schema.type:primary=array&schema.items>schema.oneOf:sole-non-null-member": "one per Schema Object one of whose `oneOf` members declares `array` as its primary type over `items` holding a `oneOf` with one non-`null` member beside a `null` one",
    "schema.oneOf>schema.type:primary=array&schema.items>schema.anyOf:sole-non-null-member": "one per Schema Object one of whose `oneOf` members declares `array` as its primary type over `items` holding an `anyOf` with one non-`null` member beside a `null` one",
    "schema.anyOf>schema.type:primary=array&schema.items>schema.oneOf:sole-non-null-member": "one per Schema Object one of whose `anyOf` members declares `array` as its primary type over `items` holding a `oneOf` with one non-`null` member beside a `null` one",
    "schema.anyOf>schema.type:primary=array&schema.items>schema.anyOf:sole-non-null-member": "one per Schema Object one of whose `anyOf` members declares `array` as its primary type over `items` holding an `anyOf` with one non-`null` member beside a `null` one",
    "schema.oneOf>schema.type:primary=array&schema.items>schema.oneOf": "one per Schema Object one of whose `oneOf` members declares `array` as its primary type over `items` declaring `oneOf`",
    "schema.oneOf>schema.type:primary=array&schema.items>schema.anyOf": "one per Schema Object one of whose `oneOf` members declares `array` as its primary type over `items` declaring `anyOf`",
    "schema.anyOf>schema.type:primary=array&schema.items>schema.oneOf": "one per Schema Object one of whose `anyOf` members declares `array` as its primary type over `items` declaring `oneOf`",
    "schema.anyOf>schema.type:primary=array&schema.items>schema.anyOf": "one per Schema Object one of whose `anyOf` members declares `array` as its primary type over `items` declaring `anyOf`",
    "schema.oneOf>schema.type:primary=array&schema.items>schema.properties:non-empty": "one per Schema Object one of whose `oneOf` members declares `array` as its primary type over `items` declaring a non-empty `properties` map",
    "schema.anyOf>schema.type:primary=array&schema.items>schema.properties:non-empty": "one per Schema Object one of whose `anyOf` members declares `array` as its primary type over `items` declaring a non-empty `properties` map",
    "schema.oneOf>schema.type:primary=array&schema.items>schema.additionalProperties=false": "one per Schema Object one of whose `oneOf` members declares `array` as its primary type over `items` declaring `additionalProperties: false`",
    "schema.anyOf>schema.type:primary=array&schema.items>schema.additionalProperties=false": "one per Schema Object one of whose `anyOf` members declares `array` as its primary type over `items` declaring `additionalProperties: false`",
    "schema.oneOf>schema.properties:non-empty": "one per Schema Object one of whose `oneOf` members declares a non-empty `properties` map",
    "schema.anyOf>schema.properties:non-empty": "one per Schema Object one of whose `anyOf` members declares a non-empty `properties` map",
    "schema.properties>schema.enum:string-valued": "one per Schema Object one of whose properties declares a string-valued `enum`",
    "schema.properties>schema.const:string-valued": "one per Schema Object one of whose properties declares a string-valued `const`",
    "schema.properties>schema.properties:non-empty": "one per Schema Object one of whose properties declares a non-empty `properties` map",
    "schema.properties>schema.additionalProperties=false": "one per Schema Object one of whose properties declares `additionalProperties: false`",
    "schema.properties>schema.oneOf:sole-non-null-member": "one per Schema Object one of whose properties declares a `oneOf` with one non-`null` member beside a `null` one",
    "schema.properties>schema.anyOf:sole-non-null-member": "one per Schema Object one of whose properties declares an `anyOf` with one non-`null` member beside a `null` one",
    "schema.properties>schema.type:primary=array": "one per Schema Object one of whose properties declares `array` as its primary type",
    "schema.properties>schema.oneOf:sole-member&schema.oneOf>schema.properties:non-empty": "one per Schema Object one of whose properties declares a one-member `oneOf` whose member declares a non-empty `properties` map",
    "schema.properties>schema.anyOf:sole-member&schema.anyOf>schema.properties:non-empty": "one per Schema Object one of whose properties declares a one-member `anyOf` whose member declares a non-empty `properties` map",
    "schema.properties>schema.oneOf:sole-member&schema.oneOf>schema.additionalProperties=false": "one per Schema Object one of whose properties declares a one-member `oneOf` whose member declares `additionalProperties: false`",
    "schema.properties>schema.anyOf:sole-member&schema.anyOf>schema.additionalProperties=false": "one per Schema Object one of whose properties declares a one-member `anyOf` whose member declares `additionalProperties: false`",
}


def conjunction_parts(text: str) -> list[list[str]]:
    """One conjunction as its `>`-separated groups, each a list of `&` members."""
    return [group.split("&") for group in text.split(">")]


def is_conjunction(text: str) -> bool:
    """Whether this selector text uses either composition operator."""
    return ">" in text or "&" in text


def descent_field(member: str) -> str | None:
    """The field a group descends through: the last member, which must be a field."""
    if "=" in member or ":" in member:
        return None
    _, _, field = member.rpartition(".")
    return field or None


def compile_conjunction(text: str) -> tuple[tuple[frozenset[str], str | None], ...]:
    """One conjunction as the groups `Census.conjunction_holds` evaluates.

    Each group is the set of members that must hold at one node, paired with the
    field the following `>` descends through — the group's last member, since that
    is the member the operator binds to.
    """
    groups = conjunction_parts(text)
    return tuple(
        (
            frozenset(members),
            None if index == len(groups) - 1 else descent_field(members[-1]),
        )
        for index, members in enumerate(groups)
    )


def canonical_conjunction(text: str) -> str:
    """This conjunction's one name: members sorted, the descended member last.

    A conjunction that could be written two ways would be two names for one shape,
    so a group's members are ordered — lexicographically, except that the member a
    following `>` descends through is written last, since that is the member the
    operator binds to.
    """
    groups = conjunction_parts(text)
    spelled = []
    for index, members in enumerate(groups):
        if index == len(groups) - 1:
            spelled.append("&".join(sorted(members)))
        else:
            head, last = members[:-1], members[-1]
            spelled.append("&".join([*sorted(head), last]))
    return ">".join(spelled)


COMPILED_CONJUNCTIONS = {text: compile_conjunction(text) for text in CONJUNCTIONS}


def is_reference_node(node: dict[Any, Any], kind_name: str) -> bool:
    """Whether this node is a Reference Object rather than the kind that holds it.

    `$ref` inside a `REF_TRANSPARENT` kind is a declared field of the kind itself;
    anywhere else it makes the node a Reference Object, counted as one and not
    descended into.
    """
    return "$ref" in node and kind_name not in REF_TRANSPARENT


# ---------------------------------------------------------------------------
# crozier's own name normalization
# ---------------------------------------------------------------------------
#
# Two predicates ask which *names* crozier would render as one Python identifier,
# so the normalizations below are not invented here.
#
# `openapi.paths:normalized-collision` asks which Paths Object keys crozier would
# render as one request URL: that is `naming::field_name` of `src/naming.rs`, the
# transform `src/ir.rs` gives a path parameter's `py_name` and `src/emit.rs`'s
# `url_arg` interpolates back into the URL — `/users/{userId}` and
# `/users/{user_id}` both emit `f"users/{encode_path_param(user_id)}"`. What is
# mirrored is that function and the four helpers it calls, case for case,
# including the cases it treats specially: a reserved name takes a trailing `_`, a
# digit-leading one takes an `f_` prefix, a non-identifier character is a word
# boundary, whitespace is a hard boundary, and a digit-bearing word joins its
# neighbour without an underscore.
#
# `components.schemas:normalized-collision` asks which `components.schemas` keys
# crozier would render as one generated class: that is `naming::class_name`, the
# transform `src/ir.rs`'s `ref_to_class` gives a named schema — `OBRate1_0` and
# `OB_Rate1_0` both name `ObRate10`. It is `to_pascal_case` plus the two cases
# `class_name` treats specially: a leading digit is spelled out as an English word,
# and every remaining non-identifier character folds to `_`.
#
# `tests/surface_census_test.py` reconciles both ports against the expectations
# `src/naming.rs`'s own unit tests pin, so crozier's casing cannot change without
# failing a check here.

_PYTHON_KEYWORDS = frozenset({
    "False", "None", "True", "and", "as", "assert", "async", "await", "break",
    "class", "continue", "def", "del", "elif", "else", "except", "finally",
    "for", "from", "global", "if", "import", "in", "is", "lambda", "nonlocal",
    "not", "or", "pass", "raise", "return", "try", "while", "with", "yield",
})
# Builtins Fern munges in field contexts; `naming::is_reserved` is the two sets.
_RESERVED_BUILTINS = frozenset(
    {"all", "bool", "float", "int", "list", "long", "map", "set", "uuid"}
)
# A path template expression: `{userId}` in `/users/{userId}/roles`.
_TEMPLATE_EXPRESSION = re.compile(r"\{([^{}]*)\}")


def _is_digit(char: str) -> bool:
    return "0" <= char <= "9"


def _is_lower(char: str) -> bool:
    return "a" <= char <= "z"


def _is_upper(char: str) -> bool:
    return "A" <= char <= "Z"


def _is_alpha(char: str) -> bool:
    return _is_lower(char) or _is_upper(char)


def split_words(text: str) -> list[str]:
    """`naming::split_words`: lowercase words across camel, Pascal, snake and kebab."""
    words: list[str] = []
    current = ""
    chars = list(text)
    for index, char in enumerate(chars):
        if char in "_- .":
            if current:
                words.append(current)
                current = ""
            continue
        previous = chars[index - 1] if index else None
        following = chars[index + 1] if index + 1 < len(chars) else None
        boundary = (
            _is_upper(char)
            and bool(current)
            and (
                (previous is not None and (_is_lower(previous) or _is_digit(previous)))
                or (
                    previous is not None
                    and _is_upper(previous)
                    and following is not None
                    and _is_lower(following)
                )
            )
        )
        if boundary:
            words.append(current)
            current = ""
        # `to_ascii_lowercase` in Rust: a non-ASCII letter passes through unchanged.
        current += char.lower() if _is_upper(char) else char
    if current:
        words.append(current)
    return words


def to_snake_case(text: str) -> str:
    """`naming::to_snake_case`: a word after a digit-bearing word joins it."""
    out = ""
    for word in split_words(text):
        last = out.rsplit("_", 1)[-1]
        after_digit_word = (
            bool(out)
            and _is_digit(out[-1])
            and bool(last)
            and _is_digit(last[-1])
            and any(_is_alpha(char) for char in last)
        )
        if out and not after_digit_word:
            out += "_"
        out += word
    return out


def _fold_non_identifier(name: str) -> str:
    """`naming::fold_non_identifier`: every non-ASCII-alphanumeric is a boundary."""
    return "".join(
        char if (_is_alpha(char) or _is_digit(char)) else " " for char in name
    )


def _digit_suffix_absorbs_following(chars: list[str], digit_index: int) -> bool:
    """`naming::digit_suffix_absorbs_following`."""
    start = digit_index
    while start > 0 and _is_digit(chars[start - 1]):
        start -= 1
    if start > 0 and chars[start - 1] == "_":
        return True
    for char in reversed(chars[:start]):
        if char == "_":
            break
        if _is_alpha(char):
            return True
    return False


def _collapse_field_digit_boundaries(name: str) -> str:
    """`naming::collapse_field_digit_boundaries`: drop a digit-adjacent `_`."""
    chars = list(name)
    kept: list[str] = []
    for index, char in enumerate(chars):
        if char == "_" and (
            (
                index > 0
                and _is_digit(chars[index - 1])
                and _digit_suffix_absorbs_following(chars, index - 1)
            )
            or (index + 1 < len(chars) and _is_digit(chars[index + 1]))
        ):
            continue
        kept.append(char)
    return "".join(kept)


def _field_snake_case(wire_name: str) -> str:
    """`naming::field_snake_case`: whitespace chunks fold independently."""
    chunks = (
        _collapse_field_digit_boundaries(to_snake_case(_fold_non_identifier(chunk)))
        for chunk in wire_name.split()
    )
    return "_".join(chunk for chunk in chunks if chunk)


def is_reserved(name: str) -> bool:
    """`naming::is_reserved`: a Python keyword or a builtin Fern munges in fields."""
    return name in _PYTHON_KEYWORDS or name in _RESERVED_BUILTINS


def field_name(wire_name: str) -> str:
    """`naming::field_name`: the Python identifier crozier gives a wire name."""
    snake = _field_snake_case(wire_name)
    if snake and _is_digit(snake[0]):
        return f"f_{snake}"
    if is_reserved(snake):
        return f"{snake}_"
    return snake


def to_pascal_case(text: str) -> str:
    """`naming::to_pascal_case`: each word capitalized, and a letter after a digit."""
    out = ""
    for word in split_words(text):
        after_digit = False
        for index, char in enumerate(word):
            if index == 0 or (after_digit and _is_alpha(char)):
                # `to_ascii_uppercase` in Rust: a non-ASCII letter is unchanged.
                out += char.upper() if _is_lower(char) else char
            else:
                out += char
            after_digit = _is_digit(char)
    return out


# `naming::class_name` spells a leading digit out, so a schema name that starts
# with one still yields a legal class name (`5GmmCause` -> `FiveGmmCause`).
_DIGIT_WORDS = (
    "Zero", "One", "Two", "Three", "Four", "Five", "Six", "Seven", "Eight", "Nine",
)


def sanitize_identifier(name: str) -> str:
    """`naming::sanitize_identifier`: every other character becomes `_`."""
    out = "".join(
        char if (_is_alpha(char) or _is_digit(char) or char == "_") else "_"
        for char in name
    )
    if out and _is_digit(out[0]):
        out = f"_{out}"
    return out


def class_name(schema_key: str) -> str:
    """`naming::class_name`: the Python class name crozier gives a named schema."""
    pascal = to_pascal_case(schema_key)
    if pascal and _is_digit(pascal[0]):
        pascal = _DIGIT_WORDS[int(pascal[0])] + pascal[1:]
    return sanitize_identifier(pascal)


def normalized_path(template: str) -> str:
    """One Paths Object key with every template expression's name normalized.

    Only the names inside `{}` move: the literal segments, their order and their
    count are what distinguish two routes, so `/users/{userId}` normalizes to
    `/users/{user_id}` while `/{id}/users` and `/users/{id}` stay apart.
    """
    return _TEMPLATE_EXPRESSION.sub(
        lambda match: "{" + field_name(match.group(1)) + "}", template
    )


def primary_type(value: Any) -> str | None:
    """The `type` member `TypeField::primary` of `src/openapi.rs` reads.

    A string is its own primary type; a 3.1 list is the first member that is not
    `null`, which is why `type: [string, array]` takes the *string* path through
    every arm of `src/ir.rs` that asks whether a schema is an array. Anything else
    is a `type` crozier would refuse to deserialize, and reads as none here.
    """
    if isinstance(value, str):
        return value
    if isinstance(value, list):
        for member in value:
            if isinstance(member, str) and member != "null":
                return member
    return None


def string_valued(node: dict[Any, Any], values: Any) -> bool:
    """Whether `string_enum_values` of `src/ir.rs` would yield strings from these.

    Its three conditions, case for case: the schema is `type: string`, or it
    declares no `type` at all and every member is a string; and at least one member
    survives as a string, since a `type: string` enum whose members are integers
    leaves nothing to enumerate and crozier falls back to the base type.
    """
    if not isinstance(values, list):
        return False
    if primary_type(node.get("type")) != "string":
        omitted_type = "type" not in node
        all_strings = all(isinstance(value, str) for value in values)
        if not omitted_type or not all_strings:
            return False
    return any(isinstance(value, str) for value in values)


def path_segment_predicates(key: str) -> list[str]:
    """The three predicates `path_group` of `src/ir.rs` reads off one route.

    `path_group` splits the URL on `/`, drops the empty segments and returns the
    first that is not *wholly* a template expression, falling back to `service`
    when there is none. So a segment is templated here exactly as it is there —
    `{id}` is, `v{n}` is not — and the three arms partition every key: the first
    segment is literal, a later one is after `path_group` skipped a templated one,
    or there is none to find.
    """
    segments = [segment for segment in key.split("/") if segment]
    templated = [
        segment.startswith("{") and segment.endswith("}") for segment in segments
    ]
    if not any(not is_template for is_template in templated):
        return ["openapi.paths:all-segments-templated"]
    if templated[0]:
        return ["openapi.paths:template-before-literal-segment"]
    return ["openapi.paths:leading-literal-segment"]


def grammar() -> tuple[set[str], set[str]]:
    """Every selector the grammar allows, and every prefix that can carry an `x-`.

    Enumerable because a selector is an anchor kind's name followed by a chain of
    fields through *extending* kinds only — the chain stops at the next anchor,
    which starts a selector of its own. That closed set is what makes a mistyped
    `--selector` refusable instead of silently reportable as undeclared.
    """
    selectors: set[str] = set()
    prefixes: set[str] = set()

    def visit(kind_name: str, prefix: str) -> None:
        if prefix in prefixes:
            return
        prefixes.add(prefix)
        kind = OBJECTS[kind_name]
        for field, child in kind.fields.items():
            selectors.add(f"{prefix}.{field}")
            if child is not None and not OBJECTS[child.kind].anchor:
                visit(child.kind, f"{prefix}.{field}")
        if kind.free_map is not None and not OBJECTS[kind.free_map.kind].anchor:
            visit(kind.free_map.kind, prefix)

    for name, kind in OBJECTS.items():
        if kind.anchor:
            visit(name, kind.name)
    return selectors, prefixes


def selector_error(text: str) -> str | None:
    """Why this `--selector` names nothing the grammar can emit, or None."""
    selectors, prefixes = grammar()
    if is_conjunction(text):
        # The conjunction list is closed by the branch structure of the six blind
        # functions, not by what the operators can spell, so a well-formed
        # combination nobody declared is refused exactly as a typo is.
        if text in CONJUNCTIONS:
            return None
        close = difflib.get_close_matches(text, sorted(CONJUNCTIONS), n=3)
        suggestion = f" Did you mean: {', '.join(close)}?" if close else ""
        return (
            f"{text!r} is not one of the conjunction selectors the census declares."
            f"{suggestion} The closed list of {len(CONJUNCTIONS)} is declared in "
            "scripts/openapi-surface-census.py and restated in "
            "docs/openapi-surface-coverage.md."
        )
    base, equals, value = text.partition("=")
    if ":" in base:
        # A predicate first, even when the spelling carries an `=`: the family
        # reads a member's *position* as well as its presence, so
        # `schema.type:primary=array` is one predicate's name rather than a valued
        # selector over a field called `schema.type:primary`.
        if text in PREDICATES:
            return None
        close = difflib.get_close_matches(text, sorted(PREDICATES), n=3)
        suggestion = f" Did you mean: {', '.join(close)}?" if close else ""
        return (
            f"{text!r} is not one of the predicate selectors the census emits."
            f"{suggestion} They are: {', '.join(sorted(PREDICATES))}."
        )
    if equals and not value:
        return f"{text!r} is a valued selector with no value"
    if equals and base not in VALUED:
        return (
            f"{base!r} is not one of the fields that emit a valued selector. "
            f"They are: {', '.join(sorted(VALUED))}."
        )
    head, _, last = base.rpartition(".")
    if last.startswith("x-"):
        if head in prefixes:
            return None
        return f"{head!r} is not an object the census walks, so it declares no {last!r}"
    if base in selectors:
        return None
    close = difflib.get_close_matches(base, sorted(selectors), n=3)
    suggestion = f" Did you mean: {', '.join(close)}?" if close else ""
    return (
        f"{base!r} is not a selector of the OpenAPI object model.{suggestion} "
        "The grammar is docs/openapi-surface-coverage.md."
    )


class Census:
    """One document's declaration-site counts, keyed by selector."""

    def __init__(self) -> None:
        self.counts: dict[str, int] = defaultdict(int)
        # `operation.operationId:duplicate` compares one document's values against
        # each other, so it cannot be decided at the declaration site the way every
        # other selector is; the values are gathered here and counted by `finish`.
        self.operation_ids: list[str] = []
        # One node's own selectors are asked for twice — once to record them, once
        # per conjunction group matched against them — and a document's objects
        # live for the whole walk, so `id()` keys a stable cache.
        self.declared_cache: dict[tuple[int, str, str], list[str]] = {}

    def record(self, selector: str) -> None:
        self.counts[selector] += 1

    def declared_here(self, node: dict[Any, Any], kind_name: str, prefix: str) -> list[str]:
        """Every selector this one node declares, with repetition.

        The node's own reading of the grammar, and the only thing a conjunction
        group is ever matched against: a field it writes, the valued selector that
        field emits, an `x-` extension it carries, and the predicates this node
        alone decides. A Reference Object shadows its host's fields, exactly as the
        walk below reports it.
        """
        key = (id(node), kind_name, prefix)
        cached = self.declared_cache.get(key)
        if cached is not None:
            return cached
        kind = OBJECTS[kind_name]
        found: list[str] = []
        if kind_name == "paths":
            found += self.normalized_collisions(node)
            found += self.path_key_templates(node)
        if kind_name == "components":
            found += self.class_name_collisions(node.get("schemas"))
        if kind_name == "schema" and not is_reference_node(node, kind_name):
            found += self.schema_predicates(node)
        if is_reference_node(node, kind_name):
            reference = OBJECTS["reference"]
            found += [
                f"reference.{name}"
                for name in node
                if isinstance(name, str) and name in reference.fields
            ]
            self.declared_cache[key] = found
            return found
        for name, value in node.items():
            if not isinstance(name, str):
                continue  # an unquoted status code or a numeric map key: a name
            if name.startswith("x-"):
                found.append(f"{prefix}.{name}")
                continue
            if name not in kind.fields:
                continue
            selector = f"{prefix}.{name}"
            found.append(selector)
            if kind_name == "operation" and name == "tags":
                if isinstance(value, list) and len(value) > 1:
                    found.append("operation.tags:multiple")
            if selector in VALUED:
                for member in value if isinstance(value, list) else [value]:
                    if isinstance(member, bool):
                        # A boolean emits a valued selector only for the one field
                        # whose two booleans are two shapes; see `VALUED_BOOL`.
                        if selector in VALUED_BOOL:
                            found.append(f"{selector}={'true' if member else 'false'}")
                    elif isinstance(member, (str, int, float)):
                        found.append(f"{selector}={self.value_of(selector, member)}")
        self.declared_cache[key] = found
        return found

    def walk(self, node: Any, kind_name: str, prefix: str, seen: frozenset[int]) -> None:
        if not isinstance(node, dict):
            return
        if id(node) in seen:  # a YAML alias pointing back at an ancestor
            return
        seen = seen | {id(node)}
        kind = OBJECTS[kind_name]
        for selector in self.declared_here(node, kind_name, prefix):
            self.record(selector)
        for selector, groups in COMPILED_CONJUNCTIONS.items():
            # A fresh alias guard: a conjunction's descent is its own path from
            # this node, and the ancestors `seen` already holds are not on it.
            if self.conjunction_holds(node, kind_name, prefix, groups, 0, frozenset()):
                self.record(selector)
        if is_reference_node(node, kind_name):
            return
        for key, value in node.items():
            if not isinstance(key, str):
                # An unquoted status code or a numeric map key: a name, never a
                # field — so it declares no selector, exactly as `declared_here`
                # has it. But the object it *names* is still part of the surface,
                # so a free-keyed map is descended into here as it is below: a
                # Responses Object writing `200:` contributes what it would
                # contribute writing `"200":`, rather than losing its subtree.
                if kind.free_map is not None:
                    self.descend(value, kind.free_map, prefix, seen)
                continue
            if key.startswith("x-"):
                continue
            if key not in kind.fields:
                # Not a field of this object: either a name in a free-keyed map
                # (a path template, a status code, a property name) whose value is
                # still an OpenAPI object, or a key this specification does not
                # define, which declares no surface.
                if kind.free_map is not None:
                    self.descend(value, kind.free_map, prefix, seen)
                continue
            if kind_name == "operation":
                self.note_operation(key, value)
            child = kind.fields[key]
            if child is not None:
                self.descend(value, child, f"{prefix}.{key}", seen)

    def conjunction_holds(
        self,
        node: Any,
        kind_name: str,
        prefix: str,
        groups: tuple[tuple[frozenset[str], str | None], ...],
        index: int,
        seen: frozenset[int],
    ) -> bool:
        """Whether this conjunction's remaining groups hold from this node.

        The whole of what `&` and `>` mean, and the only place either is
        interpreted: a group holds when every one of its members is a selector the
        node itself declares, and `>` hands the groups after it to the objects the
        group's last member's value is. A field holding several objects (a `oneOf`
        list, a `properties` map) satisfies the rest if any one of them does, which
        is what keeps the count one per node at the leftmost position.
        """
        if not isinstance(node, dict) or id(node) in seen:
            return False
        members, descend = groups[index]
        if not members.issubset(self.declared_here(node, kind_name, prefix)):
            return False
        if descend is None:
            return True
        child = OBJECTS[kind_name].fields.get(descend)
        if child is None:
            return False
        value = node[descend]
        if child.container == MAP:
            entries: Iterable[Any] = value.values() if isinstance(value, dict) else []
        else:
            entries = value if isinstance(value, list) else [value]
        target = OBJECTS[child.kind]
        inner = target.name if target.anchor else f"{prefix}.{descend}"
        return any(
            self.conjunction_holds(
                entry, child.kind, inner, groups, index + 1, seen | {id(node)}
            )
            for entry in entries
        )

    def note_operation(self, key: str, value: Any) -> None:
        """The document-scoped predicate one Operation Object's own fields feed."""
        if key == "operationId" and isinstance(value, (str, int, float)) and not isinstance(
            value, bool
        ):
            # Compared as written: a document that spells one id `1` and another
            # `"1"` has written the same value twice, and Fern reads both as a name.
            self.operation_ids.append(str(value))

    def normalized_collisions(self, node: dict[Any, Any]) -> list[str]:
        """`openapi.paths:normalized-collision`: keys crozier would render as one URL.

        One per colliding key rather than one per collision, so a document that
        writes the same normalized route twice contributes two and one that writes
        it three times contributes three. `x-` keys are extensions, not routes.
        """
        keys = self.route_keys(node)
        collisions: dict[str, int] = defaultdict(int)
        for key in keys:
            collisions[normalized_path(key)] += 1
        return [
            "openapi.paths:normalized-collision"
            for key in keys
            if collisions[normalized_path(key)] > 1
        ]

    def schema_predicates(self, node: dict[Any, Any]) -> list[str]:
        """The node-local predicates one Schema Object's own fields decide.

        Every one mirrors a property an arm of one of the six blind functions of
        `src/ir.rs` tests and no selector of the first two kinds can say: which
        member of a `type` array `TypeField::primary` reads, whether a
        `properties` map holds anything, how many non-`null` members a composition
        field has, and whether an `enum` or a `const` yields strings. Nothing here
        opens another node: a `$ref` is a string to this function.
        """
        found: list[str] = []
        if primary_type(node.get("type")) == "array":
            found.append("schema.type:primary=array")
        properties = node.get("properties")
        if isinstance(properties, dict) and properties:
            found.append("schema.properties:non-empty")
        for field in ("oneOf", "anyOf"):
            members = node.get(field)
            if not isinstance(members, list):
                continue
            non_null = [
                member
                for member in members
                if not isinstance(member, dict)
                or primary_type(member.get("type")) != "null"
            ]
            if len(non_null) == 1 and len(non_null) != len(members):
                found.append(f"schema.{field}:sole-non-null-member")
            if len(members) == 1:
                found.append(f"schema.{field}:sole-member")
        if "enum" in node and string_valued(node, node.get("enum")):
            found.append("schema.enum:string-valued")
        if "const" in node and string_valued(node, [node.get("const")]):
            found.append("schema.const:string-valued")
        return found

    def path_key_templates(self, node: dict[Any, Any]) -> list[str]:
        """The five predicates the *shape* of a Paths Object key decides.

        `openapi.paths:templated-key` is one per key carrying a template
        expression at all, and `openapi.paths:several-template-expressions` one
        per key carrying more than one — two readings of the same key, so a key
        with three expressions contributes one to each and a key with one
        contributes to the first alone. The three `path_segment_predicates` adds
        are a third reading: not how many expressions a key carries but *where*
        the first one sits, which is the only thing `path_group` looks at.
        """
        found: list[str] = []
        for key in self.route_keys(node):
            expressions = len(_TEMPLATE_EXPRESSION.findall(key))
            if expressions:
                found.append("openapi.paths:templated-key")
            if expressions > 1:
                found.append("openapi.paths:several-template-expressions")
            found += path_segment_predicates(key)
        return found

    def class_name_collisions(self, node: Any) -> list[str]:
        """`components.schemas:normalized-collision`: names crozier renders as one class.

        The Paths Object counterpart above, on the other side of the same
        exclusion: a component name is a map key the grammar keeps out of the
        census as a *name*, so only a predicate can say two of them fold together
        under `naming::class_name`. One per colliding key, as there.
        """
        if not isinstance(node, dict):
            return []
        keys = [key for key in node if isinstance(key, str) and not key.startswith("x-")]
        collisions: dict[str, int] = defaultdict(int)
        for key in keys:
            collisions[class_name(key)] += 1
        return [
            "components.schemas:normalized-collision"
            for key in keys
            if collisions[class_name(key)] > 1
        ]

    @staticmethod
    def route_keys(node: dict[Any, Any]) -> list[str]:
        """The Paths Object keys that are routes: `x-` keys are extensions."""
        return [key for key in node if isinstance(key, str) and not key.startswith("x-")]

    def finish(self) -> None:
        """Record the predicates only the whole document decides."""
        written: dict[str, int] = defaultdict(int)
        for value in self.operation_ids:
            written[value] += 1
        for count in written.values():
            if count > 1:
                self.counts["operation.operationId:duplicate"] += count

    @staticmethod
    def value_of(selector: str, member: str | int | float) -> str:
        text = str(member)
        if selector == "openapi.openapi":
            # The census cares about the 3.0-vs-3.1 delta, not the patch level.
            parts = text.split(".")
            return ".".join(parts[:2]) if len(parts) > 1 else text
        return text

    def descend(self, value: Any, child: Child, selector: str, seen: frozenset[int]) -> None:
        """Walk the objects a field carries, under the selector they head.

        An anchor kind heads its own selector; a non-anchor kind extends the
        field's. A free-keyed map hands its parent's selector straight through,
        which is how the property names, path templates and status codes that key
        those maps stay out of the census.
        """
        target = OBJECTS[child.kind]
        prefix = target.name if target.anchor else selector
        if child.container == MAP:
            values: Iterable[Any] = value.values() if isinstance(value, dict) else []
        else:
            # A single-object field holding a list (or a list field holding one
            # object) is common in real documents; traverse what is there rather
            # than what the specification promised.
            values = value if isinstance(value, list) else [value]
        for entry in values:
            self.walk(entry, child.kind, prefix, seen)


def census_document(document: Any) -> dict[str, int]:
    """Every `(selector, count)` one parsed source document declares."""
    census = Census()
    census.walk(document, "openapi", "openapi", frozenset())
    census.finish()
    return dict(census.counts)


# ---------------------------------------------------------------------------
# The registered golden sources
# ---------------------------------------------------------------------------

SPEC_NAMES = ("openapi.yml", "openapi.yaml", "openapi.json")
_ROW = re.compile(r"^\s*\|\s*\d+\s*\|")


@dataclass(frozen=True)
class Source:
    """One registered golden source document."""

    fixture: str
    origin: str  # "vendored" or "corpus"
    path: Path | None  # None when a link-ok source has not been fetched


def corpus_aliases(fixtures_root: Path) -> dict[str, str]:
    """CORPUS.md name -> fixture directory, as scripts/corpus-lib.sh resolves it."""
    aliases: dict[str, str] = {}
    path = fixtures_root / "corpus-aliases.tsv"
    if not path.is_file():
        return aliases
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        name, _, fixture = line.partition("\t")
        aliases[name.strip()] = fixture.strip()
    return aliases


def manifest_rows(manifest: Path) -> Iterator[str]:
    """The canonical numbered `link-ok` names of tests/fixtures/CORPUS.md.

    Only numbered rows of the first table are canonical; CORPUS.md carries prose
    status tables after it whose cells would otherwise read as fixture names.
    This is the same rule scripts/corpus-lib.sh applies.
    """
    for line in manifest.read_text(encoding="utf-8").splitlines():
        if not _ROW.match(line):
            continue
        cells = [cell.strip().strip("`").strip() for cell in line.split("|")]
        if len(cells) < 9:
            continue
        name, decision = cells[2], cells[7]
        if name and decision in {"link-ok", "committed"}:
            yield name


def spec_in(directory: Path) -> Path | None:
    for name in SPEC_NAMES:
        candidate = directory / name
        if candidate.is_file():
            return candidate
    return None


def registered_sources(fixtures_root: Path, corpus_root: Path, vendored_only: bool) -> list[Source]:
    """Every registered golden source: the vendored half and the link-ok half."""
    sources: list[Source] = []
    vendored: dict[str, Source] = {}
    for directory in sorted(p for p in fixtures_root.iterdir() if p.is_dir()):
        spec = spec_in(directory)
        if spec is not None:
            source = Source(fixture=directory.name, origin="vendored", path=spec)
            vendored[directory.name] = source
            sources.append(source)
    if vendored_only:
        return sources
    aliases = corpus_aliases(fixtures_root)
    manifest = fixtures_root / "CORPUS.md"
    if not manifest.is_file():
        raise SystemExit(
            f"openapi-surface-census: missing corpus manifest {manifest} — run from the "
            "repo root, or pass --vendored-only to census the offline half"
        )
    for name in manifest_rows(manifest):
        if aliases.get(name, name) in vendored:
            continue  # a manifest row whose document is vendored beside its golden
        sources.append(
            Source(fixture=name, origin="corpus", path=spec_in(corpus_root / name))
        )
    return sources

def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="openapi-surface-census.py",
        description=(
            "Census the OpenAPI surface the registered golden sources declare, "
            "one row per (selector, fixture, count)."
        ),
    )
    parser.add_argument(
        "--fixture", action="append", default=[], metavar="NAME",
        help="census only this registered source (repeatable)",
    )
    parser.add_argument(
        "--selector", action="append", default=[], metavar="SELECTOR",
        help="report only this selector (repeatable); an undeclared one is reported as such",
    )
    parser.add_argument(
        "--vendored-only", action="store_true",
        help="census the vendored tests/fixtures sources alone (needs no network)",
    )
    parser.add_argument(
        "--allow-unfetched", action="store_true",
        help="warn instead of failing when a link-ok source has not been fetched",
    )
    parser.add_argument("--json", action="store_true", help="emit the census as JSON")
    parser.add_argument("--fixtures-root", type=Path, metavar="DIR")
    parser.add_argument("--corpus-root", type=Path, metavar="DIR")
    return parser.parse_args(argv)


def path_of(source: Source, repo_root: Path) -> str | None:
    """A source's document path as the JSON report carries it."""
    if source.path is None:
        return None
    if source.path.is_relative_to(repo_root):
        return source.path.relative_to(repo_root).as_posix()
    return str(source.path)


def report(rows: dict[tuple[str, str], int], selectors: list[str]) -> str:
    """The census as one line per (selector, fixture, count)."""
    lines: list[str] = []
    width = max((len(selector) for selector, _ in rows), default=0)
    width = max(width, *(len(s) for s in selectors)) if selectors else width
    fixture_width = max((len(fixture) for _, fixture in rows), default=0)
    for selector, fixture in sorted(rows):
        lines.append(f"{selector.ljust(width)}  {fixture.ljust(fixture_width)}  {rows[(selector, fixture)]:>5}")
    declared = {selector for selector, _ in rows}
    for selector in selectors:
        if selector not in declared:
            lines.append(f"{selector.ljust(width)}  (declared by no registered source)")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    repo_root = Path(__file__).resolve().parent.parent
    fixtures_root = args.fixtures_root or repo_root / "tests" / "fixtures"
    corpus_root = args.corpus_root or repo_root / ".local" / "corpus"
    if not fixtures_root.is_dir():
        print(
            f"openapi-surface-census: missing fixtures root {fixtures_root} — run from "
            "the repo root, or correct --fixtures-root",
            file=sys.stderr,
        )
        return 1

    for selector in args.selector:
        problem = selector_error(selector)
        if problem is not None:
            print(f"openapi-surface-census: {problem}", file=sys.stderr)
            return 1

    sources = registered_sources(fixtures_root, corpus_root, args.vendored_only)
    if args.fixture:
        wanted = set(args.fixture)
        known = {source.fixture for source in sources}
        unknown = sorted(wanted - known)
        if unknown:
            print(
                f"openapi-surface-census: no registered source is named {unknown[0]!r}. "
                "The registered sources are the tests/fixtures/<name>/openapi.* documents "
                "and the link-ok rows of tests/fixtures/CORPUS.md.",
                file=sys.stderr,
            )
            return 1
        sources = [source for source in sources if source.fixture in wanted]

    unfetched = [source.fixture for source in sources if source.path is None]
    if unfetched and not args.allow_unfetched:
        print(
            f"openapi-surface-census: {len(unfetched)} registered source(s) have not been "
            f"fetched, starting with {unfetched[0]!r}, so the census would report them as "
            "declaring nothing. Run 'scripts/fetch-corpus.sh' (or 'just surface-census', "
            "which fetches first), or pass --vendored-only to census the offline half.",
            file=sys.stderr,
        )
        return 1
    for fixture in unfetched:
        print(f"openapi-surface-census: warning: {fixture} is unfetched", file=sys.stderr)

    rows: dict[tuple[str, str], int] = {}
    censused: list[Source] = []
    for source in sources:
        if source.path is None:
            continue
        try:
            document = load_document(source.path)
        except DocumentError as error:
            print(f"openapi-surface-census: {source.fixture}: {error}", file=sys.stderr)
            return 1
        if not isinstance(document, dict):
            print(
                f"openapi-surface-census: {source.fixture}: {source.path} is not an "
                "OpenAPI document (its root is not a mapping)",
                file=sys.stderr,
            )
            return 1
        censused.append(source)
        for selector, count in census_document(document).items():
            if args.selector and selector not in args.selector:
                continue
            rows[(selector, source.fixture)] = count

    if args.json:
        payload = {
            "sources": [
                {
                    "fixture": source.fixture,
                    "origin": source.origin,
                    # POSIX-style inside the repo so the report reads the same on
                    # every platform of the release matrix; null when the source is
                    # a link-ok row nothing has fetched.
                    "path": path_of(source, repo_root),
                }
                for source in sources
            ],
            "rows": [
                {"selector": selector, "fixture": fixture, "count": count}
                for (selector, fixture), count in sorted(rows.items())
            ],
            "absent_selectors": sorted(
                selector
                for selector in args.selector
                if selector not in {declared for declared, _ in rows}
            ),
        }
        print(json.dumps(payload, indent=2, sort_keys=False))
    else:
        rendered = report(rows, args.selector)
        if rendered:
            print(rendered)

    vendored = sum(1 for source in censused if source.origin == "vendored")
    print(
        f"openapi-surface-census: {len({selector for selector, _ in rows})} selector(s), "
        f"{sum(rows.values())} declaration site(s) across {len(censused)} source(s) "
        f"({vendored} vendored, {len(censused) - vendored} fetched)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
