#!/usr/bin/env python3
"""Census the OpenAPI surface every registered golden source *declares*.

`just fixtures-coverage` answers what the goldens reach in `src/`, and
`just fixtures-gaps` answers which generated bytes still diverge. Neither answers
the question this instrument exists for: **which OpenAPI shapes has the corpus
ever seen?** A shape no registered source declares is generator behaviour only
crozier vouches for — the gate stays green whatever crozier does with it — so
knowing the list is the first step to closing it
(`docs/openapi-surface-coverage.md`).

Three rules make the number honest; none of them a `grep` obeys.

* **Source documents only, never generated output.** A specification is what
  *declares* a feature; the emitted Python is not. A census that read an
  `expected/` tree would be measuring the answer instead of the question, so the
  only files opened here are the vendored `tests/fixtures/<name>/openapi.*`
  documents and the `link-ok` documents `scripts/fetch-corpus.sh` fetches into
  `.local/corpus/<name>/` from `tests/fixtures/CORPUS.md`.
* **The OpenAPI object model, not the text.** A text match scores a `trace`
  operation off a path parameter named `trace`, a `name` field off a schema
  property called `name`, and a `type` field off a property called `type` — all
  three shapes are in the vendored corpus today. The walk below knows the keys of
  a Schema Object's `properties` are *names*, the keys of a Paths Object are path
  templates, and the keys of a Responses Object are status codes, so none of them
  can be mistaken for a declared field. Free-form values (`example`, `examples`,
  `default`, `enum`, `const`) are never descended into for the same reason.
* **An unfetched source is a hard failure, not a silent skip.** A `link-ok` row
  whose spec has not been fetched would otherwise report as declaring nothing,
  and 93 of the 124 registered sources are `link-ok`. Pass `--allow-unfetched`
  to downgrade that to a warning, or `--vendored-only` to census the offline half
  on purpose.

The selector grammar, the region boundaries and how a census result becomes a
classified row are `docs/openapi-surface-coverage.md`; they are not restated
here. What only this file knows is the object-model table itself — `OBJECTS`
below is the machine-readable half of that grammar.
"""

from __future__ import annotations

import argparse
import difflib
import json
import re
import sys
from collections import defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Iterable, Iterator

# ---------------------------------------------------------------------------
# Reading a source document
# ---------------------------------------------------------------------------
#
# The corpus is half JSON and half YAML, and this script has to run inside
# `just check` on the Linux/macOS/Windows matrix with nothing but the standard
# library — the gate installs no Python packages, so PyYAML is not available.
# The loader below therefore reads the block-YAML subset OpenAPI documents are
# written in (mappings, sequences, the three scalar styles, block scalars,
# anchors/aliases/merge keys, flow collections) and REFUSES anything else by
# name and line. Refusing is the point: a census built on a loader that guessed
# would be wrong quietly, which is the one failure mode the instrument cannot
# have.


class DocumentError(Exception):
    """A source document this census cannot read, with the site that stopped it."""

    def __init__(self, path: Path, line: int, message: str) -> None:
        super().__init__(f"{path}:{line}: {message}")
        self.path = path
        self.line = line


_NULL = {"", "~", "null", "Null", "NULL"}
_TRUE = {"true", "True", "TRUE"}
_FALSE = {"false", "False", "FALSE"}
_INT = re.compile(r"[-+]?[0-9]+$")
_FLOAT = re.compile(r"[-+]?(?:[0-9]*\.[0-9]+|[0-9]+\.[0-9]*)(?:[eE][-+]?[0-9]+)?$")
_EXP = re.compile(r"[-+]?[0-9]+[eE][-+]?[0-9]+$")
# A block-mapping key ends at the first ':' that is followed by a space or the
# end of the line: `https://example.test: v` is one key, and `application/json:`
# is another. Anything else (a URL's `://`, a `{$request.body#/x}` template) is
# part of the key or of the value.
_KEY_END = re.compile(r":(?=\s|$)")
_ESCAPES = {
    "0": "\0", "a": "\a", "b": "\b", "t": "\t", "\t": "\t", "n": "\n",
    "v": "\v", "f": "\f", "r": "\r", "e": "\x1b", " ": " ", '"': '"',
    "/": "/", "\\": "\\", "N": "\x85", "_": "\xa0",
}


@dataclass(frozen=True)
class _Line:
    """One significant source line: its index, indentation and comment-free text."""

    index: int
    indent: int
    text: str


class _YamlReader:
    """A strict reader for the block-YAML subset OpenAPI documents are written in."""

    def __init__(self, path: Path, text: str) -> None:
        self.path = path
        self.lines = text.replace("\r\n", "\n").replace("\r", "\n").split("\n")
        if self.lines and self.lines[-1] == "":
            self.lines.pop()  # the file's terminating newline is not a line
        self.pos = 0
        self.anchors: dict[str, Any] = {}

    def fail(self, index: int, message: str) -> None:
        raise DocumentError(self.path, index + 1, message)

    @staticmethod
    def strip_comment(text: str) -> str:
        """Drop a trailing `#` comment, honoring quotes (`$ref: "#/x"` is not one)."""
        quote = ""
        cursor = 0
        while cursor < len(text):
            char = text[cursor]
            if quote:
                if char == "\\" and quote == '"':
                    cursor += 2  # an escape: the next character cannot close the quote
                    continue
                if char == quote:
                    quote = ""
            elif char in "\"'":
                quote = char
            elif char == "#" and (cursor == 0 or text[cursor - 1] in " \t"):
                return text[:cursor]
            cursor += 1
        return text

    def peek(self) -> _Line | None:
        """The next significant line, without consuming it."""
        while self.pos < len(self.lines):
            raw = self.lines[self.pos]
            stripped = self.strip_comment(raw).rstrip()
            if not stripped.strip():
                self.pos += 1
                continue
            indent = len(stripped) - len(stripped.lstrip(" "))
            if "\t" in stripped[: len(stripped) - len(stripped.lstrip())]:
                self.fail(self.pos, "tabs cannot indent YAML; re-indent with spaces")
            return _Line(self.pos, indent, stripped[indent:])
        return None

    def load(self) -> Any:
        first = self.peek()
        if first is None:
            self.fail(0, "the document is empty")
        if first.text.startswith("%"):
            self.fail(first.index, "YAML directives are not supported")
        if first.text == "---":
            self.pos += 1
        value = self.parse_block(0)
        trailing = self.peek()
        if trailing is not None and trailing.text not in {"...", "---"}:
            self.fail(trailing.index, f"unexpected content after the document: {trailing.text!r}")
        if trailing is not None and trailing.text == "---":
            self.fail(
                trailing.index,
                "the file holds more than one YAML document; an OpenAPI source is one document",
            )
        return value

    def parse_block(self, min_indent: int) -> Any:
        """Parse the block starting at the next significant line."""
        line = self.peek()
        if line is None or line.indent < min_indent:
            return None
        if line.text == "-" or line.text.startswith("- "):
            return self.parse_sequence(line.indent)
        if line.text == "?" or line.text.startswith("? "):
            self.fail(line.index, "explicit `? ` mapping keys are not supported")
        if line.text == ":" or line.text.startswith(": "):
            self.fail(line.index, "an empty mapping key is not supported")
        if self.split_key(line.text) is None:
            # Not an entry: a scalar written on its own line(s) under its key, the
            # way real documents wrap a long `description:`.
            self.pos = line.index + 1
            return self.parse_value(line.text, line.indent - 1, line.index)
        return self.parse_mapping(line.indent)

    def parse_mapping(self, indent: int) -> dict[Any, Any]:
        mapping: dict[Any, Any] = {}
        merges: list[Any] = []
        while True:
            line = self.peek()
            if line is None or line.indent < indent:
                break
            if line.indent == 0 and line.text in {"---", "..."}:
                break  # a document marker ends this block; load() reports it
            if line.indent > indent:
                self.fail(line.index, "unexpected indentation inside a block mapping")
            if line.text == "-" or line.text.startswith("- "):
                self.fail(line.index, "a sequence item where a mapping key was expected")
            if line.text == ":" or line.text.startswith(": "):
                self.fail(line.index, "an empty mapping key is not supported")
            split = self.split_key(line.text)
            if split is None:
                self.fail(line.index, f"expected a `key: value` mapping entry, got {line.text!r}")
            key_text, rest = split
            key = self.parse_key(line, key_text)
            self.pos = line.index + 1
            value = self.parse_value(rest, indent, line.index)
            if key == "<<":
                merges.append(value)
            else:
                mapping[key] = value
        for merged in merges:
            for source in merged if isinstance(merged, list) else [merged]:
                if isinstance(source, dict):
                    for key, value in source.items():
                        mapping.setdefault(key, value)
        return mapping

    def parse_sequence(self, indent: int) -> list[Any]:
        items: list[Any] = []
        while True:
            line = self.peek()
            if line is None or line.indent < indent:
                break
            if line.indent == 0 and line.text in {"---", "..."}:
                break  # a document marker ends this block; load() reports it
            if line.indent > indent:
                self.fail(line.index, "unexpected indentation inside a block sequence")
            if not (line.text == "-" or line.text.startswith("- ")):
                break
            rest = line.text[1:].lstrip(" ")
            if rest == "":
                self.pos = line.index + 1
                items.append(self.parse_block(indent + 1))
                continue
            if rest.startswith("- ") or rest == "-" or self.split_key(rest) is not None:
                # A nested collection opening on the dash line: blank the dash so
                # the item's own lines all sit at one indentation, then parse it
                # as an ordinary block. Rewriting the line (rather than threading
                # a synthetic first line through the parser) keeps every later
                # line of the item on its real source index, so failures still
                # name the line the reader would look at.
                raw = self.lines[line.index]
                self.lines[line.index] = raw[: line.indent] + " " + raw[line.indent + 1 :]
                items.append(self.parse_block(indent + 1))
                continue
            self.pos = line.index + 1
            items.append(self.parse_value(rest, indent, line.index))
        return items

    def split_key(self, text: str) -> tuple[str, str] | None:
        """Split `key: value` into its halves, or None when `text` is not an entry."""
        if text[0] in "\"'":
            end = self.scan_quoted(text, 0)
            if end is None or not (text[end:] == ":" or text[end:].startswith(": ")):
                return None
            return text[:end], text[end + 1 :].lstrip(" ")
        if text.startswith(("[", "{", "&", "*", "|", ">")):
            return None
        match = _KEY_END.search(text)
        if match is None or not text[: match.start()].strip():
            return None  # no `key:` at all, or the empty key `: value`
        return text[: match.start()], text[match.end() :].lstrip(" ")

    def parse_key(self, line: _Line, key_text: str) -> Any:
        if key_text.startswith("? "):
            self.fail(line.index, "explicit `? ` mapping keys are not supported")
        if key_text.startswith("!"):
            self.fail(line.index, "YAML tags are not supported")
        if key_text[0] in "\"'":
            end = self.scan_quoted(key_text, 0)
            assert end is not None  # split_key only returns a terminated quote
            return self.unquote(line, key_text[:end])
        return self.scalar(key_text.rstrip())

    def parse_value(self, rest: str, indent: int, index: int) -> Any:
        """The value of a mapping entry or sequence item declared on line `index`."""
        anchor = None
        if rest.startswith("&"):
            name, _, remainder = rest.partition(" ")
            anchor = name[1:]
            rest = remainder.lstrip(" ")
        if rest.startswith("!"):
            self.fail(index, "YAML tags are not supported")
        if rest.startswith("*"):
            name = rest[1:].strip()
            if name not in self.anchors:
                self.fail(index, f"alias *{name} has no anchor")
            value: Any = self.anchors[name]
        elif rest == "":
            following = self.peek()
            # A block sequence may sit at its key's own indentation, and most
            # generator-written documents do exactly that; anything else has to be
            # more indented than the key to belong to it.
            nested = following is not None and (
                following.indent > indent
                or (
                    following.indent == indent
                    and (following.text == "-" or following.text.startswith("- "))
                )
            )
            value = self.parse_block(following.indent) if nested else None
        elif rest[0] in "|>":
            value = self.block_scalar(rest, indent, index)
        elif rest[0] in "[{":
            value = self.flow(rest, index)
        else:
            value = self.plain(rest, indent, index)
        if anchor is not None:
            self.anchors[anchor] = value
        return value

    def block_scalar(self, header: str, indent: int, index: int) -> str:
        style, header = header[0], header[1:].strip()
        chomp = ""
        explicit = 0
        for char in header:
            if char in "+-":
                chomp = char
            elif char.isdigit():
                explicit = int(char)
            else:
                self.fail(index, f"unsupported block scalar header {header!r}")
        body: list[str] = []
        block_indent = indent + explicit if explicit else 0
        cursor = index + 1
        while cursor < len(self.lines):
            raw = self.lines[cursor]
            if raw.strip() == "":
                body.append("")
                cursor += 1
                continue
            line_indent = len(raw) - len(raw.lstrip(" "))
            if line_indent <= indent:
                break
            if not block_indent:
                block_indent = line_indent
            if line_indent < block_indent:
                break
            body.append(raw[block_indent:])
            cursor += 1
        self.pos = cursor
        trailing = 0
        while body and body[-1] == "":
            body.pop()
            trailing += 1
        text = "\n".join(body) if style == "|" else self.fold(body)
        if chomp == "-" or not text:
            return text
        return text + "\n" * (1 + trailing if chomp == "+" else 1)

    @staticmethod
    def fold(body: list[str]) -> str:
        """Fold a `>` scalar: a break between two lines becomes a space, a run of
        empty lines becomes that many breaks, and a more-indented line keeps its
        own breaks."""
        out: list[str] = []
        folding = False
        cursor = 0
        while cursor < len(body):
            entry = body[cursor]
            if entry == "":
                run = 0
                while cursor < len(body) and body[cursor] == "":
                    run += 1
                    cursor += 1
                out.append("\n" * run)
                folding = False
                continue
            if entry.startswith(" "):
                out.append(("\n" if folding else "") + entry)
                folding = False
            else:
                out.append((" " if folding else "") + entry)
                folding = True
            cursor += 1
        return "".join(out)

    def plain(self, rest: str, indent: int, index: int) -> Any:
        """A quoted or plain scalar, folding any more-indented continuation lines."""
        if rest[0] in "\"'":
            end = self.scan_quoted(rest, 0)
            if end is not None:
                trailing = rest[end:].strip()
                if trailing:
                    self.fail(index, f"unexpected text after a quoted scalar: {trailing!r}")
                return self.unquote(self.line_at(index), rest[:end])
            return self.multiline_quoted(rest, indent, index)
        pieces = [rest]
        cursor = index + 1
        while cursor < len(self.lines):
            candidate = self.strip_comment(self.lines[cursor]).rstrip()
            if not candidate.strip():
                break
            candidate_indent = len(candidate) - len(candidate.lstrip(" "))
            if candidate_indent <= indent:
                break
            pieces.append(candidate.strip())
            cursor += 1
        self.pos = cursor
        if len(pieces) == 1:
            return self.scalar(rest.strip())
        return " ".join(pieces)

    def multiline_quoted(self, rest: str, indent: int, index: int) -> str:
        """A quoted scalar whose closing quote is on a later line.

        The source line breaks are folded away BEFORE the escapes are read, which
        is the only order that survives a document like slurmdb-rest's: a
        double-quoted description holding both real `\\n` escapes and a trailing
        `\\` that cancels the source break. Folding afterwards would eat the
        escapes along with the breaks.
        """
        quote = rest[0]
        buffer = rest.rstrip()
        blanks = 0
        cursor = index + 1
        while cursor < len(self.lines):
            piece = self.lines[cursor].strip()
            cursor += 1
            if not piece:
                blanks += 1
                continue
            if quote == '"' and (len(buffer) - len(buffer.rstrip("\\"))) % 2 == 1:
                buffer = buffer[:-1] + piece  # a trailing backslash cancels the break
            elif blanks:
                buffer = f"{buffer}{chr(10) * blanks}{piece}"
            else:
                buffer = f"{buffer} {piece}"
            blanks = 0
            end = self.scan_quoted(buffer, 0)
            if end is not None:
                trailing = buffer[end:].strip()
                if trailing:
                    self.fail(index, f"unexpected text after a quoted scalar: {trailing!r}")
                self.pos = cursor
                return self.unquote(self.line_at(index), buffer[:end])
        self.fail(index, "a quoted scalar is never closed")
        raise AssertionError("unreachable")  # pragma: no cover - fail() raises

    def line_at(self, index: int) -> _Line:
        raw = self.strip_comment(self.lines[index]).rstrip()
        indent = len(raw) - len(raw.lstrip(" "))
        return _Line(index, indent, raw[indent:])

    @staticmethod
    def scan_quoted(text: str, start: int) -> int | None:
        """The index just past the quoted scalar at `start`, or None if unterminated."""
        quote = text[start]
        cursor = start + 1
        while cursor < len(text):
            char = text[cursor]
            if quote == '"' and char == "\\":
                cursor += 2
                continue
            if char == quote:
                if quote == "'" and text[cursor + 1 : cursor + 2] == "'":
                    cursor += 2
                    continue
                return cursor + 1
            cursor += 1
        return None

    def unquote(self, line: _Line, text: str) -> str:
        if text[0] == "'":
            return text[1:-1].replace("''", "'")
        body = text[1:-1]
        out: list[str] = []
        cursor = 0
        while cursor < len(body):
            char = body[cursor]
            if char != "\\":
                out.append(char)
                cursor += 1
                continue
            marker = body[cursor + 1 : cursor + 2]
            if marker in ("x", "u", "U"):
                width = {"x": 2, "u": 4, "U": 8}[marker]
                digits = body[cursor + 2 : cursor + 2 + width]
                try:
                    out.append(chr(int(digits, 16)))
                except ValueError:
                    self.fail(line.index, f"invalid \\{marker} escape {digits!r}")
                cursor += 2 + width
                continue
            if marker == "\n":
                cursor += 2
                continue
            if marker not in _ESCAPES:
                self.fail(line.index, f"unsupported escape \\{marker}")
            out.append(_ESCAPES[marker])
            cursor += 2
        return "".join(out)

    def flow(self, rest: str, index: int) -> Any:
        """A flow collection, gathered across lines until its brackets balance."""
        buffer = rest
        cursor = index + 1
        while self.flow_depth(buffer) > 0 and cursor < len(self.lines):
            buffer = f"{buffer} {self.strip_comment(self.lines[cursor]).strip()}"
            cursor += 1
        if self.flow_depth(buffer) != 0:
            self.fail(index, "a flow collection is never closed")
        self.pos = cursor
        value, end = self.flow_node(buffer, 0, index)
        if buffer[end:].strip():
            self.fail(index, f"unexpected text after a flow collection: {buffer[end:].strip()!r}")
        return value

    def flow_depth(self, text: str) -> int:
        depth = 0
        cursor = 0
        while cursor < len(text):
            char = text[cursor]
            if char in "\"'":
                end = self.scan_quoted(text, cursor)
                cursor = end if end is not None else len(text)
                continue
            if char in "[{":
                depth += 1
            elif char in "]}":
                depth -= 1
            cursor += 1
        return depth

    def flow_node(self, text: str, start: int, index: int) -> tuple[Any, int]:
        cursor = self.skip_space(text, start)
        if cursor >= len(text):
            self.fail(index, "a flow collection ends where a value was expected")
        char = text[cursor]
        if char == "[":
            return self.flow_collection(text, cursor, index, "]")
        if char == "{":
            return self.flow_collection(text, cursor, index, "}")
        if char in "\"'":
            end = self.scan_quoted(text, cursor)
            if end is None:
                self.fail(index, "a quoted scalar in a flow collection is never closed")
            return self.unquote(self.line_at(index), text[cursor:end]), end
        end = cursor
        while end < len(text) and text[end] not in ",]}:":
            end += 1
        raw = text[cursor:end].strip()
        if raw.startswith("*"):
            name = raw[1:]
            if name not in self.anchors:
                self.fail(index, f"alias *{name} has no anchor")
            return self.anchors[name], end
        return self.scalar(raw), end

    def flow_collection(self, text: str, start: int, index: int, closer: str) -> tuple[Any, int]:
        items: list[Any] = []
        mapping: dict[Any, Any] = {}
        cursor = start + 1
        while True:
            cursor = self.skip_space(text, cursor)
            if cursor >= len(text):
                self.fail(index, "a flow collection is never closed")
            if text[cursor] == closer:
                return (mapping if closer == "}" else items), cursor + 1
            value, cursor = self.flow_node(text, cursor, index)
            cursor = self.skip_space(text, cursor)
            if False:
                entry, cursor = self.flow_node(text, cursor + 1, index)
                mapping[value] = entry
            else:
                items.append(value)
            cursor = self.skip_space(text, cursor)
            if cursor < len(text) and text[cursor] == ",":
                cursor += 1

    @staticmethod
    def skip_space(text: str, cursor: int) -> int:
        while cursor < len(text) and text[cursor] in " \t":
            cursor += 1
        return cursor

    @staticmethod
    def scalar(text: str) -> Any:
        """Resolve a plain scalar to the type YAML's core schema gives it."""
        if text in _NULL:
            return None
        if text in _TRUE:
            return True
        if text in _FALSE:
            return False
        if _INT.match(text):
            return int(text)
        if _FLOAT.match(text) or _EXP.match(text):
            return float(text)
        return text


def load_document(path: Path) -> Any:
    """Parse one OpenAPI source document into plain Python objects."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as error:
        raise DocumentError(path, 0, f"cannot be read: {error}") from error
    if text.startswith("﻿"):
        text = text[1:]
    if path.suffix == ".json":
        try:
            return json.loads(text)
        except json.JSONDecodeError as error:
            raise DocumentError(path, error.lineno, f"is not valid JSON: {error.msg}") from error
    return _YamlReader(path, text).load()


# ---------------------------------------------------------------------------
# The OpenAPI object model
# ---------------------------------------------------------------------------

ONE, LIST, MAP = "one", "list", "map"


@dataclass(frozen=True)
class Child:
    """A field that carries further OpenAPI objects, and how they are held."""

    container: str
    kind: str


@dataclass(frozen=True)
class ObjectKind:
    """One OpenAPI object: which fields it declares and how a selector names it.

    `anchor` is the half of the selector grammar that cannot be derived from the
    specification: an anchor kind heads its own selector (`response.links`), and
    a non-anchor kind extends its parent's instead (`info.license.identifier`,
    `mediaType.encoding.headers`). The two lists are closed and are stated in
    `docs/openapi-surface-coverage.md`; they are here because the walk needs them.
    """

    name: str
    anchor: bool
    fields: dict[str, Child | None]
    free_map: Child | None = None


def _kind(
    name: str,
    anchor: bool,
    fields: dict[str, Child | None],
    free_map: Child | None = None,
) -> ObjectKind:
    return ObjectKind(name=name, anchor=anchor, fields=fields, free_map=free_map)


_SCHEMA_FIELDS: dict[str, Child | None] = {
    # 3.0 and 3.1 alike
    "$ref": None, "title": None, "multipleOf": None, "maximum": None,
    "exclusiveMaximum": None, "minimum": None, "exclusiveMinimum": None,
    "maxLength": None, "minLength": None, "pattern": None, "maxItems": None,
    "minItems": None, "uniqueItems": None, "maxProperties": None,
    "minProperties": None, "required": None, "enum": None, "type": None,
    "description": None, "format": None, "default": None, "readOnly": None,
    "writeOnly": None, "example": None, "deprecated": None,
    "allOf": Child(LIST, "schema"), "oneOf": Child(LIST, "schema"),
    "anyOf": Child(LIST, "schema"), "not": Child(ONE, "schema"),
    "items": Child(ONE, "schema"), "properties": Child(MAP, "schema"),
    "additionalProperties": Child(ONE, "schema"),
    "discriminator": Child(ONE, "discriminator"), "xml": Child(ONE, "xml"),
    "externalDocs": Child(ONE, "externalDocs"),
    # 3.0 only
    "nullable": None,
    # 3.1 (JSON Schema 2020-12)
    "$schema": None, "$id": None, "$anchor": None, "$comment": None,
    "$dynamicRef": None, "$dynamicAnchor": None, "$vocabulary": None,
    "const": None, "examples": None, "contentEncoding": None,
    "contentMediaType": None, "dependentRequired": None, "maxContains": None,
    "minContains": None,
    "$defs": Child(MAP, "schema"), "definitions": Child(MAP, "schema"),
    "prefixItems": Child(LIST, "schema"), "contains": Child(ONE, "schema"),
    "patternProperties": Child(MAP, "schema"),
    "propertyNames": Child(ONE, "schema"),
    "unevaluatedItems": Child(ONE, "schema"),
    "unevaluatedProperties": Child(ONE, "schema"),
    "if": Child(ONE, "schema"), "then": Child(ONE, "schema"),
    "else": Child(ONE, "schema"), "dependentSchemas": Child(MAP, "schema"),
    "contentSchema": Child(ONE, "schema"),
}

_PARAMETER_FIELDS: dict[str, Child | None] = {
    "description": None, "required": None, "deprecated": None,
    "allowEmptyValue": None, "style": None, "explode": None,
    "allowReserved": None, "example": None,
    "schema": Child(ONE, "schema"), "examples": Child(MAP, "example"),
    "content": Child(MAP, "mediaType"),
}

OBJECTS: dict[str, ObjectKind] = {
    "openapi": _kind("openapi", True, {
        "openapi": None, "jsonSchemaDialect": None,
        "info": Child(ONE, "info"), "servers": Child(LIST, "server"),
        "paths": Child(ONE, "paths"), "webhooks": Child(MAP, "pathItem"),
        "components": Child(ONE, "components"),
        "security": Child(LIST, "securityRequirement"),
        "tags": Child(LIST, "tag"), "externalDocs": Child(ONE, "externalDocs"),
    }),
    "info": _kind("info", True, {
        "title": None, "summary": None, "description": None,
        "termsOfService": None, "version": None,
        "contact": Child(ONE, "contact"), "license": Child(ONE, "license"),
    }),
    "contact": _kind("contact", False, {"name": None, "url": None, "email": None}),
    "license": _kind("license", False, {"name": None, "identifier": None, "url": None}),
    "server": _kind("server", True, {
        "url": None, "description": None, "variables": Child(MAP, "serverVariable"),
    }),
    "serverVariable": _kind("serverVariable", False, {
        "enum": None, "default": None, "description": None,
    }),
    "components": _kind("components", True, {
        "schemas": Child(MAP, "schema"), "responses": Child(MAP, "response"),
        "parameters": Child(MAP, "parameter"), "examples": Child(MAP, "example"),
        "requestBodies": Child(MAP, "requestBody"), "headers": Child(MAP, "header"),
        "securitySchemes": Child(MAP, "securityScheme"), "links": Child(MAP, "link"),
        "callbacks": Child(MAP, "callback"), "pathItems": Child(MAP, "pathItem"),
    }),
    # The keys of a Paths Object are path templates, and the keys of a Callback
    # Object are runtime expressions: names, never fields. `free_map` is what
    # keeps them out of the census.
    "paths": _kind("paths", False, {}, free_map=Child(ONE, "pathItem")),
    "callback": _kind("callback", True, {}, free_map=Child(ONE, "pathItem")),
    "pathItem": _kind("pathItem", True, {
        "$ref": None, "summary": None, "description": None,
        "get": Child(ONE, "operation"), "put": Child(ONE, "operation"),
        "post": Child(ONE, "operation"), "delete": Child(ONE, "operation"),
        "options": Child(ONE, "operation"), "head": Child(ONE, "operation"),
        "patch": Child(ONE, "operation"), "trace": Child(ONE, "operation"),
        "servers": Child(LIST, "server"), "parameters": Child(LIST, "parameter"),
    }),
    "operation": _kind("operation", True, {
        "tags": None, "summary": None, "description": None, "operationId": None,
        "deprecated": None,
        "externalDocs": Child(ONE, "externalDocs"),
        "parameters": Child(LIST, "parameter"),
        "requestBody": Child(ONE, "requestBody"),
        "responses": Child(ONE, "responses"),
        "callbacks": Child(MAP, "callback"),
        "security": Child(LIST, "securityRequirement"),
        "servers": Child(LIST, "server"),
    }),
    "externalDocs": _kind("externalDocs", True, {"description": None, "url": None}),
    "parameter": _kind("parameter", True, {"name": None, "in": None, **_PARAMETER_FIELDS}),
    "header": _kind("header", True, dict(_PARAMETER_FIELDS)),
    "requestBody": _kind("requestBody", True, {
        "description": None, "required": None, "content": Child(MAP, "mediaType"),
    }),
    "mediaType": _kind("mediaType", True, {
        "example": None, "schema": Child(ONE, "schema"),
        "examples": Child(MAP, "example"), "encoding": Child(MAP, "encoding"),
    }),
    "encoding": _kind("encoding", False, {
        "contentType": None, "style": None, "explode": None, "allowReserved": None,
        "headers": Child(MAP, "header"),
    }),
    # The keys of a Responses Object are status codes; only `default` is a field.
    "responses": _kind("responses", False, {
        "default": Child(ONE, "response"),
    }, free_map=Child(ONE, "response")),
    "response": _kind("response", True, {
        "description": None, "headers": Child(MAP, "header"),
        "content": Child(MAP, "mediaType"), "links": Child(MAP, "link"),
    }),
    "example": _kind("example", True, {
        "summary": None, "description": None, "value": None, "externalValue": None,
    }),
    "link": _kind("link", True, {
        "operationRef": None, "operationId": None, "parameters": None,
        "requestBody": None, "description": None, "server": Child(ONE, "server"),
    }),
    "tag": _kind("tag", True, {
        "name": None, "description": None, "externalDocs": Child(ONE, "externalDocs"),
    }),
    "schema": _kind("schema", True, _SCHEMA_FIELDS),
    "discriminator": _kind("discriminator", False, {"propertyName": None, "mapping": None}),
    "xml": _kind("xml", False, {
        "name": None, "namespace": None, "prefix": None, "attribute": None,
        "wrapped": None,
    }),
    "securityScheme": _kind("securityScheme", True, {
        "type": None, "description": None, "name": None, "in": None,
        "scheme": None, "bearerFormat": None, "openIdConnectUrl": None,
        "flows": Child(ONE, "oauthFlows"),
    }),
    "oauthFlows": _kind("oauthFlows", False, {
        "implicit": Child(ONE, "oauthFlow"), "password": Child(ONE, "oauthFlow"),
        "clientCredentials": Child(ONE, "oauthFlow"),
        "authorizationCode": Child(ONE, "oauthFlow"),
    }),
    "oauthFlow": _kind("oauthFlow", False, {
        "authorizationUrl": None, "tokenUrl": None, "refreshUrl": None, "scopes": None,
    }),
    # The keys of a Security Requirement Object are scheme names declared in
    # `components.securitySchemes`, so the object contributes no selector of its own.
    "securityRequirement": _kind("securityRequirement", True, {}),
    "reference": _kind("reference", True, {
        "$ref": None, "summary": None, "description": None,
    }),
}

# The closed list of fields that also emit a valued selector, `<selector>=<value>`.
# A field is here when its value is drawn from a small, specification-defined set
# that a region needs to census one member of at a time (`parameter.in=cookie`);
# `schema.format` is here despite being an open set because a format is exactly
# the kind of shape a generator either maps to a Python type or drops.
VALUED = {
    "openapi.openapi", "parameter.in", "parameter.style", "header.style",
    "mediaType.encoding.style", "schema.type", "schema.format",
    "securityScheme.type", "securityScheme.in", "securityScheme.scheme",
}

# `$ref` inside these kinds is a declared field of the kind itself (a JSON Schema
# keyword, a Path Item reference); anywhere else a `$ref` makes the node a
# Reference Object, which is counted as one and not descended into.
REF_TRANSPARENT = {"schema", "pathItem"}


def grammar() -> tuple[set[str], set[str]]:
    """Every selector the grammar allows, and every prefix that can carry an `x-`.

    Enumerable because a selector is an anchor kind's name followed by a chain of
    fields through *extending* kinds only — the chain stops at the next anchor,
    which starts a selector of its own. That closed set is what makes a mistyped
    `--selector` refusable instead of silently reportable as undeclared.
    """
    selectors: set[str] = set()
    prefixes: set[str] = set()

    def visit(kind_name: str, prefix: str) -> None:
        if prefix in prefixes:
            return
        prefixes.add(prefix)
        kind = OBJECTS[kind_name]
        for field, child in kind.fields.items():
            selectors.add(f"{prefix}.{field}")
            if child is not None and not OBJECTS[child.kind].anchor:
                visit(child.kind, f"{prefix}.{field}")
        if kind.free_map is not None and not OBJECTS[kind.free_map.kind].anchor:
            visit(kind.free_map.kind, prefix)

    for name, kind in OBJECTS.items():
        if kind.anchor:
            visit(name, kind.name)
    return selectors, prefixes


def selector_error(text: str) -> str | None:
    """Why this `--selector` names nothing the grammar can emit, or None."""
    selectors, prefixes = grammar()
    base, equals, value = text.partition("=")
    if equals and not value:
        return f"{text!r} is a valued selector with no value"
    if equals and base not in VALUED:
        return (
            f"{base!r} is not one of the fields that emit a valued selector. "
            f"They are: {', '.join(sorted(VALUED))}."
        )
    head, _, last = base.rpartition(".")
    if last.startswith("x-"):
        if head in prefixes:
            return None
        return f"{head!r} is not an object the census walks, so it declares no {last!r}"
    if base in selectors:
        return None
    close = difflib.get_close_matches(base, sorted(selectors), n=3)
    suggestion = f" Did you mean: {', '.join(close)}?" if close else ""
    return (
        f"{base!r} is not a selector of the OpenAPI object model.{suggestion} "
        "The grammar is docs/openapi-surface-coverage.md."
    )


class Census:
    """One document's declaration-site counts, keyed by selector."""

    def __init__(self) -> None:
        self.counts: dict[str, int] = defaultdict(int)

    def record(self, selector: str) -> None:
        self.counts[selector] += 1

    def walk(self, node: Any, kind_name: str, prefix: str, seen: frozenset[int]) -> None:
        if not isinstance(node, dict):
            return
        if id(node) in seen:  # a YAML alias pointing back at an ancestor
            return
        seen = seen | {id(node)}
        kind = OBJECTS[kind_name]
        if "$ref" in node and kind_name not in REF_TRANSPARENT:
            reference = OBJECTS["reference"]
            for key in node:
                if isinstance(key, str) and key in reference.fields:
                    self.record(f"reference.{key}")
            return
        for key, value in node.items():
            if not isinstance(key, str):
                continue  # an unquoted status code or a numeric map key: a name
            if key.startswith("x-"):
                self.record(f"{prefix}.{key}")
                continue
            if key not in kind.fields:
                # Not a field of this object: either a name in a free-keyed map
                # (a path template, a status code, a property name) whose value is
                # still an OpenAPI object, or a key this specification does not
                # define, which declares no surface.
                if kind.free_map is not None:
                    self.descend(value, kind.free_map, prefix, seen)
                continue
            selector = f"{prefix}.{key}"
            self.record(selector)
            if selector in VALUED:
                for member in value if isinstance(value, list) else [value]:
                    if isinstance(member, (str, int, float)) and not isinstance(member, bool):
                        self.record(f"{selector}={self.value_of(selector, member)}")
            child = kind.fields[key]
            if child is not None:
                self.descend(value, child, selector, seen)

    @staticmethod
    def value_of(selector: str, member: str | int | float) -> str:
        text = str(member)
        if selector == "openapi.openapi":
            # The census cares about the 3.0-vs-3.1 delta, not the patch level.
            parts = text.split(".")
            return ".".join(parts[:2]) if len(parts) > 1 else text
        return text

    def descend(self, value: Any, child: Child, selector: str, seen: frozenset[int]) -> None:
        """Walk the objects a field carries, under the selector they head.

        An anchor kind heads its own selector; a non-anchor kind extends the
        field's. A free-keyed map hands its parent's selector straight through,
        which is how the property names, path templates and status codes that key
        those maps stay out of the census.
        """
        target = OBJECTS[child.kind]
        prefix = target.name if target.anchor else selector
        if child.container == MAP:
            values: Iterable[Any] = value.values() if isinstance(value, dict) else []
        else:
            # A single-object field holding a list (or a list field holding one
            # object) is common in real documents; traverse what is there rather
            # than what the specification promised.
            values = value if isinstance(value, list) else [value]
        for entry in values:
            self.walk(entry, child.kind, prefix, seen)


def census_document(document: Any) -> dict[str, int]:
    """Every `(selector, count)` one parsed source document declares."""
    census = Census()
    census.walk(document, "openapi", "openapi", frozenset())
    return dict(census.counts)


# ---------------------------------------------------------------------------
# The registered golden sources
# ---------------------------------------------------------------------------

SPEC_NAMES = ("openapi.yml", "openapi.yaml", "openapi.json")
_ROW = re.compile(r"^\s*\|\s*\d+\s*\|")


@dataclass(frozen=True)
class Source:
    """One registered golden source document."""

    fixture: str
    origin: str  # "vendored" or "corpus"
    path: Path | None  # None when a link-ok source has not been fetched


def corpus_aliases(fixtures_root: Path) -> dict[str, str]:
    """CORPUS.md name -> fixture directory, as scripts/corpus-lib.sh resolves it."""
    aliases: dict[str, str] = {}
    path = fixtures_root / "corpus-aliases.tsv"
    if not path.is_file():
        return aliases
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        name, _, fixture = line.partition("\t")
        aliases[name.strip()] = fixture.strip()
    return aliases


def manifest_rows(manifest: Path) -> Iterator[str]:
    """The canonical numbered `link-ok` names of tests/fixtures/CORPUS.md.

    Only numbered rows of the first table are canonical; CORPUS.md carries prose
    status tables after it whose cells would otherwise read as fixture names.
    This is the same rule scripts/corpus-lib.sh applies.
    """
    for line in manifest.read_text(encoding="utf-8").splitlines():
        if not _ROW.match(line):
            continue
        cells = [cell.strip().strip("`").strip() for cell in line.split("|")]
        if len(cells) < 9:
            continue
        name, decision = cells[2], cells[7]
        if name and decision in {"link-ok", "committed"}:
            yield name


def spec_in(directory: Path) -> Path | None:
    for name in SPEC_NAMES:
        candidate = directory / name
        if candidate.is_file():
            return candidate
    return None


def registered_sources(fixtures_root: Path, corpus_root: Path, vendored_only: bool) -> list[Source]:
    """Every registered golden source: the vendored half and the link-ok half."""
    sources: list[Source] = []
    vendored: dict[str, Source] = {}
    for directory in sorted(p for p in fixtures_root.iterdir() if p.is_dir()):
        spec = spec_in(directory)
        if spec is not None:
            source = Source(fixture=directory.name, origin="vendored", path=spec)
            vendored[directory.name] = source
            sources.append(source)
    if vendored_only:
        return sources
    aliases = corpus_aliases(fixtures_root)
    manifest = fixtures_root / "CORPUS.md"
    if not manifest.is_file():
        raise SystemExit(f"openapi-surface-census: missing corpus manifest {manifest}")
    for name in manifest_rows(manifest):
        if aliases.get(name, name) in vendored:
            continue  # a manifest row whose document is vendored beside its golden
        sources.append(
            Source(fixture=name, origin="corpus", path=spec_in(corpus_root / name))
        )
    return sources


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        prog="openapi-surface-census.py",
        description=(
            "Census the OpenAPI surface the registered golden sources declare, "
            "one row per (selector, fixture, count)."
        ),
    )
    parser.add_argument(
        "--fixture", action="append", default=[], metavar="NAME",
        help="census only this registered source (repeatable)",
    )
    parser.add_argument(
        "--selector", action="append", default=[], metavar="SELECTOR",
        help="report only this selector (repeatable); an undeclared one is reported as such",
    )
    parser.add_argument(
        "--vendored-only", action="store_true",
        help="census the vendored tests/fixtures sources alone (needs no network)",
    )
    parser.add_argument(
        "--allow-unfetched", action="store_true",
        help="warn instead of failing when a link-ok source has not been fetched",
    )
    parser.add_argument("--json", action="store_true", help="emit the census as JSON")
    parser.add_argument("--fixtures-root", type=Path, metavar="DIR")
    parser.add_argument("--corpus-root", type=Path, metavar="DIR")
    return parser.parse_args(argv)


def path_of(source: Source, repo_root: Path) -> str | None:
    """A source's document path as the JSON report carries it."""
    if source.path is None:
        return None
    if source.path.is_relative_to(repo_root):
        return source.path.relative_to(repo_root).as_posix()
    return str(source.path)


def report(rows: dict[tuple[str, str], int], selectors: list[str]) -> str:
    """The census as one line per (selector, fixture, count)."""
    lines: list[str] = []
    width = max((len(selector) for selector, _ in rows), default=0)
    width = max(width, *(len(s) for s in selectors)) if selectors else width
    fixture_width = max((len(fixture) for _, fixture in rows), default=0)
    for selector, fixture in sorted(rows):
        lines.append(f"{selector.ljust(width)}  {fixture.ljust(fixture_width)}  {rows[(selector, fixture)]:>5}")
    declared = {selector for selector, _ in rows}
    for selector in selectors:
        if selector not in declared:
            lines.append(f"{selector.ljust(width)}  (declared by no registered source)")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    repo_root = Path(__file__).resolve().parent.parent
    fixtures_root = args.fixtures_root or repo_root / "tests" / "fixtures"
    corpus_root = args.corpus_root or repo_root / ".local" / "corpus"
    if not fixtures_root.is_dir():
        print(f"openapi-surface-census: missing fixtures root {fixtures_root}", file=sys.stderr)
        return 1

    for selector in args.selector:
        problem = selector_error(selector)
        if problem is not None:
            print(f"openapi-surface-census: {problem}", file=sys.stderr)
            return 1

    sources = registered_sources(fixtures_root, corpus_root, args.vendored_only)
    if args.fixture:
        wanted = set(args.fixture)
        known = {source.fixture for source in sources}
        unknown = sorted(wanted - known)
        if unknown:
            print(
                f"openapi-surface-census: no registered source is named {unknown[0]!r}. "
                "The registered sources are the tests/fixtures/<name>/openapi.* documents "
                "and the link-ok rows of tests/fixtures/CORPUS.md.",
                file=sys.stderr,
            )
            return 1
        sources = [source for source in sources if source.fixture in wanted]

    unfetched = [source.fixture for source in sources if source.path is None]
    if unfetched and not args.allow_unfetched:
        print(
            f"openapi-surface-census: {len(unfetched)} registered source(s) have not been "
            f"fetched, starting with {unfetched[0]!r}, so the census would report them as "
            "declaring nothing. Run 'scripts/fetch-corpus.sh' (or 'just surface-census', "
            "which fetches first), or pass --vendored-only to census the offline half.",
            file=sys.stderr,
        )
        return 1
    for fixture in unfetched:
        print(f"openapi-surface-census: warning: {fixture} is unfetched", file=sys.stderr)

    rows: dict[tuple[str, str], int] = {}
    censused: list[Source] = []
    for source in sources:
        if source.path is None:
            continue
        try:
            document = load_document(source.path)
        except DocumentError as error:
            print(f"openapi-surface-census: {source.fixture}: {error}", file=sys.stderr)
            return 1
        if not isinstance(document, dict):
            print(
                f"openapi-surface-census: {source.fixture}: {source.path} is not an "
                "OpenAPI document (its root is not a mapping)",
                file=sys.stderr,
            )
            return 1
        censused.append(source)
        for selector, count in census_document(document).items():
            if args.selector and selector not in args.selector:
                continue
            rows[(selector, source.fixture)] = count

    if args.json:
        payload = {
            "sources": [
                {
                    "fixture": source.fixture,
                    "origin": source.origin,
                    # POSIX-style inside the repo so the report reads the same on
                    # every platform of the release matrix; null when the source is
                    # a link-ok row nothing has fetched.
                    "path": path_of(source, repo_root),
                }
                for source in sources
            ],
            "rows": [
                {"selector": selector, "fixture": fixture, "count": count}
                for (selector, fixture), count in sorted(rows.items())
            ],
            "absent_selectors": sorted(
                selector
                for selector in args.selector
                if selector not in {declared for declared, _ in rows}
            ),
        }
        print(json.dumps(payload, indent=2, sort_keys=False))
    else:
        rendered = report(rows, args.selector)
        if rendered:
            print(rendered)

    vendored = sum(1 for source in censused if source.origin == "vendored")
    print(
        f"openapi-surface-census: {len({selector for selector, _ in rows})} selector(s), "
        f"{sum(rows.values())} declaration site(s) across {len(censused)} source(s) "
        f"({vendored} vendored, {len(censused) - vendored} fetched)",
        file=sys.stderr,
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
