

import typing

from ...core import enum

T_Result = typing.TypeVar("T_Result")


class RegisterPushDeviceRequestTokenKind(enum.StrEnum):
    """
    Whether the token was generated by FCM or APNs.
    """

    FCM = "fcm"
    APNS = "apns"

    def visit(self, fcm: typing.Callable[[], T_Result], apns: typing.Callable[[], T_Result]) -> T_Result:
        if self is RegisterPushDeviceRequestTokenKind.FCM:
            return fcm()
        if self is RegisterPushDeviceRequestTokenKind.APNS:
            return apns()
