//! Rendering the IR to Python source files with minijinja.
//!
//! Rust computes the semantics — resolved type expressions, the exact import
//! block, per-field annotations and defaults — and minijinja lays out the files.
//! The split keeps the byte-sensitive logic (import ordering, alias wrapping) in
//! testable Rust while templates stay presentational.

use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

use minijinja::{context, Environment};

use crate::error::{Error, Result};
use crate::ir::{Field, Ir, Prim, TypeDecl, TypeRef};
use crate::naming;

/// The header comment crozier writes atop every generated file. It differs from
/// Fern's by design; the comment-stripping normalizer removes it before any
/// comparison, so the wording is free.
const HEADER: &str = "# This file was auto-generated by crozier from an OpenAPI document.";

/// A generated file: a repo-relative path and its contents.
#[derive(Debug, Clone)]
pub struct GeneratedFile {
    /// Path relative to the output root.
    pub path: PathBuf,
    /// File contents.
    pub contents: String,
}

/// Python standard-library top-level modules crozier may import. Used to split
/// imports into Fern's two ordered groups (stdlib first, everything else second).
const STDLIB_MODULES: &[&str] = &[
    "typing",
    "datetime",
    "uuid",
    "importlib",
    "enum",
    "os",
    "sys",
    "json",
    "base64",
    "collections",
    "decimal",
    "abc",
];

/// Collects imports and renders them in Fern's order: group 1 is stdlib
/// (`import`s then `from`s), group 2 is everything else (`import`s then `from`s),
/// separated by a blank line. Names within a `from` and the statements within a
/// group are sorted.
#[derive(Default)]
struct Imports {
    /// Plain `import module [as alias]`, keyed by module for sorting.
    plain: BTreeMap<String, Option<String>>,
    /// `from module import a, b`, module -> sorted names.
    from: BTreeMap<String, BTreeSet<String>>,
}

impl Imports {
    fn add_plain(&mut self, module: &str) {
        self.plain.entry(module.to_string()).or_insert(None);
    }

    fn add_plain_as(&mut self, module: &str, alias: &str) {
        self.plain
            .insert(module.to_string(), Some(alias.to_string()));
    }

    fn add_from(&mut self, module: &str, name: &str) {
        self.from
            .entry(module.to_string())
            .or_default()
            .insert(name.to_string());
    }

    /// Is a module (or a `from` path's leading segment) part of the stdlib group?
    /// Relative imports (leading `.`) are never stdlib.
    fn is_stdlib(module: &str) -> bool {
        if module.starts_with('.') {
            return false;
        }
        let top = module.split('.').next().unwrap_or(module);
        STDLIB_MODULES.contains(&top)
    }

    fn render(&self) -> String {
        let (mut g1, mut g2): (Vec<String>, Vec<String>) = (Vec::new(), Vec::new());

        // Plain imports first within each group (BTreeMap iterates sorted).
        for (module, alias) in &self.plain {
            let line = match alias {
                Some(a) => format!("import {module} as {a}"),
                None => format!("import {module}"),
            };
            if Self::is_stdlib(module) {
                g1.push(line);
            } else {
                g2.push(line);
            }
        }
        // Then `from` imports within each group.
        for (module, names) in &self.from {
            let joined = names.iter().cloned().collect::<Vec<_>>().join(", ");
            let line = format!("from {module} import {joined}");
            if Self::is_stdlib(module) {
                g1.push(line);
            } else {
                g2.push(line);
            }
        }

        let groups: Vec<String> = [g1, g2]
            .into_iter()
            .filter(|g| !g.is_empty())
            .map(|g| g.join("\n"))
            .collect();
        groups.join("\n\n")
    }
}

/// Render a resolved type to a Python expression, registering needed imports.
fn render_type(t: &TypeRef, imports: &mut Imports) -> String {
    match t {
        TypeRef::Primitive(p) => match p {
            Prim::Str => "str".to_string(),
            Prim::Int => "int".to_string(),
            Prim::Float => "float".to_string(),
            Prim::Bool => "bool".to_string(),
            Prim::Any => {
                imports.add_plain("typing");
                "typing.Any".to_string()
            }
            Prim::Datetime => {
                imports.add_plain_as("datetime", "dt");
                "dt.datetime".to_string()
            }
            Prim::Date => {
                imports.add_plain_as("datetime", "dt");
                "dt.date".to_string()
            }
        },
        TypeRef::Named(class) => {
            let module = naming::module_name(class);
            imports.add_from(&format!(".{module}"), class);
            class.clone()
        }
        TypeRef::Optional(inner) => {
            imports.add_plain("typing");
            format!("typing.Optional[{}]", render_type(inner, imports))
        }
        TypeRef::Literal(values) => {
            imports.add_plain("typing");
            let joined = values
                .iter()
                .map(|v| format!("\"{v}\""))
                .collect::<Vec<_>>()
                .join(", ");
            format!("typing.Literal[{joined}]")
        }
        TypeRef::List(inner) => {
            imports.add_plain("typing");
            format!("typing.List[{}]", render_type(inner, imports))
        }
        TypeRef::Set(inner) => {
            imports.add_plain("typing");
            format!("typing.Set[{}]", render_type(inner, imports))
        }
        TypeRef::Dict(k, v) => {
            imports.add_plain("typing");
            format!(
                "typing.Dict[{}, {}]",
                render_type(k, imports),
                render_type(v, imports)
            )
        }
        TypeRef::Union(variants) => {
            imports.add_plain("typing");
            let rendered: Vec<String> = variants.iter().map(|v| render_type(v, imports)).collect();
            format!("typing.Union[{}]", rendered.join(", "))
        }
    }
}

/// A field prepared for emission: its Python name, resolved annotation, the
/// `= <default>` suffix, and an optional docstring.
struct RenderedField {
    py_name: String,
    annotation: String,
    default: String,
    docstring: Option<String>,
}

/// Compute a field's annotation + default, registering imports.
fn render_field(field: &Field, imports: &mut Imports) -> RenderedField {
    let inner = render_type(&field.type_ref, imports);
    let typ = if field.optional {
        imports.add_plain("typing");
        format!("typing.Optional[{inner}]")
    } else {
        inner
    };

    // Fern carries the wire alias in `FieldMetadata` inside the `Annotated`, not
    // in `pydantic.Field`.
    let annotation = if field.needs_alias() {
        imports.add_plain("typing_extensions");
        imports.add_from("..core.serialization", "FieldMetadata");
        format!(
            "typing_extensions.Annotated[{typ}, FieldMetadata(alias=\"{}\")]",
            field.wire_name
        )
    } else {
        typ
    };

    RenderedField {
        py_name: field.py_name.clone(),
        annotation,
        default: field_default(field, imports),
        docstring: field.docstring.clone(),
    }
}

/// The `= <default>` suffix for a field. A documented field carries a
/// `pydantic.Field` (with `default=None` when optional); an undocumented
/// optional field defaults to `None`; a required undocumented field has none.
fn field_default(field: &Field, imports: &mut Imports) -> String {
    if field.docstring.is_some() {
        imports.add_plain("pydantic");
        if field.optional {
            " = pydantic.Field(default=None)".to_string()
        } else {
            " = pydantic.Field()".to_string()
        }
    } else if field.optional {
        " = None".to_string()
    } else {
        String::new()
    }
}

/// Build the minijinja environment with the embedded templates.
fn environment() -> Environment<'static> {
    let mut env = Environment::new();
    env.set_keep_trailing_newline(true);
    env.set_trim_blocks(true);
    env.set_lstrip_blocks(true);
    env.add_template("version.py", include_str!("../templates/version.py.j2"))
        .expect("version template compiles");
    env.add_template("object.py", include_str!("../templates/object.py.j2"))
        .expect("object template compiles");
    env.add_template("alias.py", include_str!("../templates/alias.py.j2"))
        .expect("alias template compiles");
    env
}

/// Generate every file crozier currently emits for an IR.
pub fn generate(ir: &Ir) -> Result<Vec<GeneratedFile>> {
    let env = environment();
    let mut files = Vec::new();
    let pkg = &ir.package_name;

    // version.py
    let version = render(
        &env,
        "version.py",
        "version.py",
        context! { project_name => ir.project_name },
    )?;
    files.push(GeneratedFile {
        path: PathBuf::from(format!("src/{pkg}/version.py")),
        contents: version,
    });

    // py.typed (an empty marker file).
    files.push(GeneratedFile {
        path: PathBuf::from(format!("src/{pkg}/py.typed")),
        contents: String::new(),
    });

    // One file per generated type.
    for decl in &ir.types {
        let file = render_type_decl(&env, decl)?;
        files.push(GeneratedFile {
            path: PathBuf::from(format!("src/{pkg}/types/{}.py", decl.module())),
            contents: file,
        });
    }

    Ok(files)
}

/// The pydantic model configuration block Fern emits at the end of every model.
/// Static (the `# type: ignore` comment is stripped before the byte comparison).
const CONFIG_BLOCK: &str = "    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra=\"allow\", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow";

/// Render a docstring as an indented triple-quoted block, escaping backslashes
/// the way Fern does so the value round-trips. Every line (including blank ones)
/// carries the block indent; the block has no trailing newline.
fn render_docstring(doc: &str, indent: usize) -> String {
    let pad = " ".repeat(indent);
    let mut out = format!("{pad}\"\"\"\n");
    for line in doc.split('\n') {
        out.push_str(&pad);
        out.push_str(&line.replace('\\', "\\\\"));
        out.push('\n');
    }
    out.push_str(&pad);
    out.push_str("\"\"\"");
    out
}

/// Assemble a model's class body: an optional class docstring, the fields (each
/// with an optional docstring), then the config block. Consecutive fields are
/// separated by a blank line only after a documented field; a blank line always
/// precedes the config block. No trailing newline (the template adds it).
fn object_body(class_docstring: Option<&str>, fields: &[RenderedField]) -> String {
    let mut body = String::new();
    if let Some(doc) = class_docstring {
        body.push_str(&render_docstring(doc, 4));
        body.push_str("\n\n");
    }
    for (i, field) in fields.iter().enumerate() {
        body.push_str("    ");
        body.push_str(&field.py_name);
        body.push_str(": ");
        body.push_str(&field.annotation);
        body.push_str(&field.default);
        body.push('\n');
        if let Some(doc) = &field.docstring {
            body.push_str(&render_docstring(doc, 4));
            body.push('\n');
        }
        // Separate a documented field from the next field with a blank line.
        if field.docstring.is_some() && i + 1 < fields.len() {
            body.push('\n');
        }
    }
    if !fields.is_empty() {
        body.push('\n');
    }
    body.push_str(CONFIG_BLOCK);
    body
}

/// Render one type declaration to a file body.
fn render_type_decl(env: &Environment<'static>, decl: &TypeDecl) -> Result<String> {
    match decl {
        TypeDecl::Object(obj) => {
            let mut imports = Imports::default();
            imports.add_plain("typing");
            imports.add_plain("pydantic");
            imports.add_from("..core.pydantic_utilities", "IS_PYDANTIC_V2");
            imports.add_from("..core.pydantic_utilities", "UniversalBaseModel");
            let fields: Vec<RenderedField> = obj
                .fields
                .iter()
                .map(|f| render_field(f, &mut imports))
                .collect();
            render(
                env,
                "object.py",
                &obj.name,
                context! {
                    header => HEADER,
                    imports => imports.render(),
                    class_name => obj.name,
                    body => object_body(obj.docstring.as_deref(), &fields),
                },
            )
        }
        TypeDecl::Alias(alias) => {
            let mut imports = Imports::default();
            let target = render_type(&alias.target, &mut imports);
            render(
                env,
                "alias.py",
                &alias.name,
                context! {
                    header => HEADER,
                    imports => imports.render(),
                    name => alias.name,
                    target => target,
                },
            )
        }
    }
}

/// Render a named template with a context, mapping errors to [`Error::Render`].
fn render(
    env: &Environment<'static>,
    template: &str,
    file: &str,
    ctx: minijinja::value::Value,
) -> Result<String> {
    env.get_template(template)
        .and_then(|t| t.render(ctx))
        .map_err(|e| Error::Render {
            file: file.to_string(),
            message: e.to_string(),
        })
}

/// Write generated files under `root`, creating parent directories.
pub fn write_files(root: &std::path::Path, files: &[GeneratedFile]) -> Result<()> {
    for file in files {
        let full = root.join(&file.path);
        if let Some(parent) = full.parent() {
            std::fs::create_dir_all(parent).map_err(|source| Error::WriteOutput {
                path: parent.to_path_buf(),
                source,
            })?;
        }
        std::fs::write(&full, &file.contents).map_err(|source| Error::WriteOutput {
            path: full.clone(),
            source,
        })?;
    }
    Ok(())
}
