//! Rendering the IR to Python source files with minijinja.
//!
//! Rust computes the semantics — resolved type expressions, the exact import
//! block, per-field annotations and defaults — and minijinja lays out the files.
//! The split keeps the byte-sensitive logic (import ordering, alias wrapping) in
//! testable Rust while templates stay presentational.

use std::collections::{BTreeMap, BTreeSet};
use std::path::PathBuf;

use minijinja::{context, Environment};

use crate::error::{Error, Result};
use crate::ir::{Field, Ir, Prim, TypeDecl, TypeRef};
use crate::naming;
use crate::wrap::{self, Doc};

/// The header comment crozier writes atop every generated file. It differs from
/// Fern's by design; the comment-stripping normalizer removes it before any
/// comparison, so the wording is free.
const HEADER: &str = "# This file was auto-generated by crozier from an OpenAPI document.";

/// A generated file: a repo-relative path and its contents.
#[derive(Debug, Clone)]
pub struct GeneratedFile {
    /// Path relative to the output root.
    pub path: PathBuf,
    /// File contents.
    pub contents: String,
}

/// Python standard-library top-level modules crozier may import. Used to split
/// imports into Fern's two ordered groups (stdlib first, everything else second).
const STDLIB_MODULES: &[&str] = &[
    "typing",
    "datetime",
    "uuid",
    "importlib",
    "enum",
    "os",
    "sys",
    "json",
    "base64",
    "collections",
    "decimal",
    "abc",
];

/// Collects imports and renders them in Fern's order: group 1 is stdlib
/// (`import`s then `from`s), group 2 is everything else (`import`s then `from`s),
/// separated by a blank line. Names within a `from` and the statements within a
/// group are sorted.
#[derive(Default)]
struct Imports {
    /// Plain `import module [as alias]`, keyed by module for sorting.
    plain: BTreeMap<String, Option<String>>,
    /// `from module import a, b`, module -> sorted names.
    from: BTreeMap<String, BTreeSet<String>>,
}

impl Imports {
    fn add_plain(&mut self, module: &str) {
        self.plain.entry(module.to_string()).or_insert(None);
    }

    fn add_plain_as(&mut self, module: &str, alias: &str) {
        self.plain
            .insert(module.to_string(), Some(alias.to_string()));
    }

    fn add_from(&mut self, module: &str, name: &str) {
        self.from
            .entry(module.to_string())
            .or_default()
            .insert(name.to_string());
    }

    /// Is a module (or a `from` path's leading segment) part of the stdlib group?
    /// Relative imports (leading `.`) are never stdlib.
    fn is_stdlib(module: &str) -> bool {
        if module.starts_with('.') {
            return false;
        }
        let top = module.split('.').next().unwrap_or(module);
        STDLIB_MODULES.contains(&top)
    }

    fn render(&self) -> String {
        let (mut g1, mut g2): (Vec<String>, Vec<String>) = (Vec::new(), Vec::new());

        // Plain imports first within each group (BTreeMap iterates sorted).
        for (module, alias) in &self.plain {
            let line = match alias {
                Some(a) => format!("import {module} as {a}"),
                None => format!("import {module}"),
            };
            if Self::is_stdlib(module) {
                g1.push(line);
            } else {
                g2.push(line);
            }
        }
        // Then `from` imports within each group.
        for (module, names) in &self.from {
            let joined = names.iter().cloned().collect::<Vec<_>>().join(", ");
            let line = format!("from {module} import {joined}");
            if Self::is_stdlib(module) {
                g1.push(line);
            } else {
                g2.push(line);
            }
        }

        let groups: Vec<String> = [g1, g2]
            .into_iter()
            .filter(|g| !g.is_empty())
            .map(|g| g.join("\n"))
            .collect();
        groups.join("\n\n")
    }
}

/// Render a resolved type to a [`Doc`] expression, registering needed imports.
/// The `Doc` tree lets [`wrap::layout`] reproduce ruff's line wrapping.
fn render_type(t: &TypeRef, imports: &mut Imports) -> Doc {
    match t {
        TypeRef::Primitive(p) => match p {
            Prim::Str => Doc::atom("str"),
            Prim::Int => Doc::atom("int"),
            Prim::Float => Doc::atom("float"),
            Prim::Bool => Doc::atom("bool"),
            Prim::Any => {
                imports.add_plain("typing");
                Doc::atom("typing.Any")
            }
            Prim::Datetime => {
                imports.add_plain_as("datetime", "dt");
                Doc::atom("dt.datetime")
            }
            Prim::Date => {
                imports.add_plain_as("datetime", "dt");
                Doc::atom("dt.date")
            }
        },
        TypeRef::Named(class) => {
            let module = naming::module_name(class);
            imports.add_from(&format!(".{module}"), class);
            Doc::atom(class.clone())
        }
        TypeRef::Optional(inner) => {
            imports.add_plain("typing");
            Doc::group("typing.Optional[", vec![render_type(inner, imports)], "]")
        }
        TypeRef::Literal(values) => {
            imports.add_plain("typing");
            let items = values
                .iter()
                .map(|v| Doc::atom(format!("\"{v}\"")))
                .collect();
            Doc::group("typing.Literal[", items, "]")
        }
        TypeRef::List(inner) => {
            imports.add_plain("typing");
            Doc::group("typing.List[", vec![render_type(inner, imports)], "]")
        }
        TypeRef::Set(inner) => {
            imports.add_plain("typing");
            Doc::group("typing.Set[", vec![render_type(inner, imports)], "]")
        }
        TypeRef::Dict(k, v) => {
            imports.add_plain("typing");
            Doc::group(
                "typing.Dict[",
                vec![render_type(k, imports), render_type(v, imports)],
                "]",
            )
        }
        TypeRef::Union(variants) => {
            imports.add_plain("typing");
            let items = variants.iter().map(|v| render_type(v, imports)).collect();
            Doc::group("typing.Union[", items, "]")
        }
    }
}

/// A field prepared for emission: its Python name, resolved annotation, the
/// `= <default>` suffix, and an optional docstring.
struct RenderedField {
    py_name: String,
    annotation: Doc,
    default: String,
    docstring: Option<String>,
}

/// Compute a field's annotation + default, registering imports.
fn render_field(field: &Field, imports: &mut Imports) -> RenderedField {
    let inner = render_type(&field.type_ref, imports);
    let typ = if field.optional {
        imports.add_plain("typing");
        Doc::group("typing.Optional[", vec![inner], "]")
    } else {
        inner
    };

    // Fern carries the wire alias in `FieldMetadata` inside the `Annotated`, not
    // in `pydantic.Field`.
    let annotation = if field.needs_alias() {
        imports.add_plain("typing_extensions");
        imports.add_from("..core.serialization", "FieldMetadata");
        Doc::group(
            "typing_extensions.Annotated[",
            vec![
                typ,
                Doc::atom(format!("FieldMetadata(alias=\"{}\")", field.wire_name)),
            ],
            "]",
        )
    } else {
        typ
    };

    RenderedField {
        py_name: field.py_name.clone(),
        annotation,
        default: field_default(field, imports),
        docstring: field.docstring.clone(),
    }
}

/// The `= <default>` suffix for a field. A documented field carries a
/// `pydantic.Field` (with `default=None` when optional); an undocumented
/// optional field defaults to `None`; a required undocumented field has none.
fn field_default(field: &Field, imports: &mut Imports) -> String {
    if field.docstring.is_some() {
        imports.add_plain("pydantic");
        if field.optional {
            " = pydantic.Field(default=None)".to_string()
        } else {
            " = pydantic.Field()".to_string()
        }
    } else if field.optional {
        " = None".to_string()
    } else {
        String::new()
    }
}

/// Build the minijinja environment with the embedded templates.
fn environment() -> Environment<'static> {
    let mut env = Environment::new();
    env.set_keep_trailing_newline(true);
    env.set_trim_blocks(true);
    env.set_lstrip_blocks(true);
    env.add_template("version.py", include_str!("../templates/version.py.j2"))
        .expect("version template compiles");
    env.add_template("object.py", include_str!("../templates/object.py.j2"))
        .expect("object template compiles");
    env.add_template("alias.py", include_str!("../templates/alias.py.j2"))
        .expect("alias template compiles");
    env
}

/// Generate every file crozier currently emits for an IR.
pub fn generate(ir: &Ir) -> Result<Vec<GeneratedFile>> {
    let env = environment();
    let mut files = Vec::new();
    let pkg = &ir.package_name;

    // version.py
    let version = render(
        &env,
        "version.py",
        "version.py",
        context! { project_name => ir.project_name },
    )?;
    files.push(GeneratedFile {
        path: PathBuf::from(format!("src/{pkg}/version.py")),
        contents: version,
    });

    // py.typed (an empty marker file).
    files.push(GeneratedFile {
        path: PathBuf::from(format!("src/{pkg}/py.typed")),
        contents: String::new(),
    });

    // One file per generated type.
    for decl in &ir.types {
        let file = render_type_decl(&env, decl)?;
        files.push(GeneratedFile {
            path: PathBuf::from(format!("src/{pkg}/types/{}.py", decl.module())),
            contents: file,
        });
    }

    // Fern's static core runtime, emitted verbatim (see assets/README.md).
    files.extend(core_files(pkg, &ir.project_name));

    // One package marker per endpoint client module. Fern's `__init__.py` here is
    // a comment-only header, so the comment-stripped form is four blank lines.
    for module in &ir.endpoint_modules {
        files.push(GeneratedFile {
            path: PathBuf::from(format!("src/{pkg}/{module}/__init__.py")),
            contents: "\n\n\n\n".to_string(),
        });
    }

    Ok(files)
}

/// Fern's SDK runtime, vendored under `assets/core/` and emitted into every SDK.
/// Each entry is (path under `core/`, verbatim contents). Only `client_wrapper`
/// carries substitutions. See `assets/README.md` and `NOTICE` for provenance.
const CORE_ASSETS: &[(&str, &str)] = &[
    ("__init__.py", include_str!("../assets/core/__init__.py")),
    ("api_error.py", include_str!("../assets/core/api_error.py")),
    (
        "client_wrapper.py",
        include_str!("../assets/core/client_wrapper.py"),
    ),
    (
        "datetime_utils.py",
        include_str!("../assets/core/datetime_utils.py"),
    ),
    ("file.py", include_str!("../assets/core/file.py")),
    (
        "force_multipart.py",
        include_str!("../assets/core/force_multipart.py"),
    ),
    (
        "http_client.py",
        include_str!("../assets/core/http_client.py"),
    ),
    (
        "http_response.py",
        include_str!("../assets/core/http_response.py"),
    ),
    (
        "http_sse/__init__.py",
        include_str!("../assets/core/http_sse/__init__.py"),
    ),
    (
        "http_sse/_api.py",
        include_str!("../assets/core/http_sse/_api.py"),
    ),
    (
        "http_sse/_decoders.py",
        include_str!("../assets/core/http_sse/_decoders.py"),
    ),
    (
        "http_sse/_exceptions.py",
        include_str!("../assets/core/http_sse/_exceptions.py"),
    ),
    (
        "http_sse/_models.py",
        include_str!("../assets/core/http_sse/_models.py"),
    ),
    (
        "jsonable_encoder.py",
        include_str!("../assets/core/jsonable_encoder.py"),
    ),
    (
        "pydantic_utilities.py",
        include_str!("../assets/core/pydantic_utilities.py"),
    ),
    (
        "query_encoder.py",
        include_str!("../assets/core/query_encoder.py"),
    ),
    (
        "remove_none_from_dict.py",
        include_str!("../assets/core/remove_none_from_dict.py"),
    ),
    (
        "request_options.py",
        include_str!("../assets/core/request_options.py"),
    ),
    (
        "serialization.py",
        include_str!("../assets/core/serialization.py"),
    ),
];

/// Placeholders substituted in `client_wrapper.py`.
const SDK_NAME_PLACEHOLDER: &str = "@@CROZIER_SDK_NAME@@";
const SDK_VERSION_PLACEHOLDER: &str = "@@CROZIER_SDK_VERSION@@";
/// Default SDK version stamped into the runtime (Fern uses `0.0.0` when none is
/// configured). Not yet exposed as a flag.
const DEFAULT_SDK_VERSION: &str = "0.0.0";

/// Emit the vendored core runtime for a package, substituting the SDK name
/// (project name) and version into `client_wrapper.py`.
fn core_files(pkg: &str, project_name: &str) -> Vec<GeneratedFile> {
    CORE_ASSETS
        .iter()
        .map(|(rel, content)| GeneratedFile {
            path: PathBuf::from(format!("src/{pkg}/core/{rel}")),
            contents: content
                .replace(SDK_NAME_PLACEHOLDER, project_name)
                .replace(SDK_VERSION_PLACEHOLDER, DEFAULT_SDK_VERSION),
        })
        .collect()
}

/// The pydantic model configuration block Fern emits at the end of every model.
/// Static (the `# type: ignore` comment is stripped before the byte comparison).
const CONFIG_BLOCK: &str = "    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra=\"allow\", frozen=True)  # type: ignore # Pydantic v2
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow";

/// Render a docstring as an indented triple-quoted block, escaping backslashes
/// the way Fern does so the value round-trips. Every line (including blank ones)
/// carries the block indent; the block has no trailing newline.
fn render_docstring(doc: &str, indent: usize) -> String {
    let pad = " ".repeat(indent);
    let mut out = format!("{pad}\"\"\"\n");
    for line in doc.split('\n') {
        out.push_str(&pad);
        out.push_str(&line.replace('\\', "\\\\"));
        out.push('\n');
    }
    out.push_str(&pad);
    out.push_str("\"\"\"");
    out
}

/// Assemble a model's class body: an optional class docstring, the fields (each
/// with an optional docstring), then the config block. Consecutive fields are
/// separated by a blank line only after a documented field; a blank line always
/// precedes the config block. No trailing newline (the template adds it).
fn object_body(class_docstring: Option<&str>, fields: &[RenderedField]) -> String {
    let mut body = String::new();
    if let Some(doc) = class_docstring {
        body.push_str(&render_docstring(doc, 4));
        body.push_str("\n\n");
    }
    for (i, field) in fields.iter().enumerate() {
        let line = wrap::layout(
            &format!("    {}: ", field.py_name),
            &field.annotation,
            &field.default,
            4,
        );
        body.push_str(&line);
        body.push('\n');
        if let Some(doc) = &field.docstring {
            body.push_str(&render_docstring(doc, 4));
            body.push('\n');
        }
        // Separate a documented field from the next field with a blank line.
        if field.docstring.is_some() && i + 1 < fields.len() {
            body.push('\n');
        }
    }
    if !fields.is_empty() {
        body.push('\n');
    }
    body.push_str(CONFIG_BLOCK);
    body
}

/// Render one type declaration to a file body.
fn render_type_decl(env: &Environment<'static>, decl: &TypeDecl) -> Result<String> {
    match decl {
        TypeDecl::Object(obj) => {
            let mut imports = Imports::default();
            imports.add_plain("typing");
            imports.add_plain("pydantic");
            imports.add_from("..core.pydantic_utilities", "IS_PYDANTIC_V2");
            // Bases come from an `allOf`'s `$ref` members; with none, the model
            // extends Fern's `UniversalBaseModel`.
            let bases = if obj.bases.is_empty() {
                imports.add_from("..core.pydantic_utilities", "UniversalBaseModel");
                "UniversalBaseModel".to_string()
            } else {
                for base in &obj.bases {
                    imports.add_from(&format!(".{}", naming::module_name(base)), base);
                }
                obj.bases.join(", ")
            };
            let fields: Vec<RenderedField> = obj
                .fields
                .iter()
                .map(|f| render_field(f, &mut imports))
                .collect();
            render(
                env,
                "object.py",
                &obj.name,
                context! {
                    header => HEADER,
                    imports => imports.render(),
                    class_name => obj.name,
                    bases => bases,
                    body => object_body(obj.docstring.as_deref(), &fields),
                },
            )
        }
        TypeDecl::Alias(alias) => {
            let mut imports = Imports::default();
            let target = render_type(&alias.target, &mut imports);
            let assignment = wrap::layout(&format!("{} = ", alias.name), &target, "", 0);
            render(
                env,
                "alias.py",
                &alias.name,
                context! {
                    header => HEADER,
                    imports => imports.render(),
                    assignment => assignment,
                },
            )
        }
    }
}

/// Render a named template with a context, mapping errors to [`Error::Render`].
fn render(
    env: &Environment<'static>,
    template: &str,
    file: &str,
    ctx: minijinja::value::Value,
) -> Result<String> {
    env.get_template(template)
        .and_then(|t| t.render(ctx))
        .map_err(|e| Error::Render {
            file: file.to_string(),
            message: e.to_string(),
        })
}

/// Write generated files under `root`, creating parent directories.
pub fn write_files(root: &std::path::Path, files: &[GeneratedFile]) -> Result<()> {
    for file in files {
        let full = root.join(&file.path);
        if let Some(parent) = full.parent() {
            std::fs::create_dir_all(parent).map_err(|source| Error::WriteOutput {
                path: parent.to_path_buf(),
                source,
            })?;
        }
        std::fs::write(&full, &file.contents).map_err(|source| Error::WriteOutput {
            path: full.clone(),
            source,
        })?;
    }
    Ok(())
}
