

import typing

import pydantic
import typing_extensions
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from ..core.serialization import FieldMetadata
from .organisation_id import OrganisationId


class OrganisationEnrolmentsItem(UniversalBaseModel):
    client_name: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ClientName"),
        pydantic.Field(alias="ClientName", description="ORG name as per eIDAS certificate"),
    ] = None
    """
    ORG name as per eIDAS certificate
    """

    client_secret: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ClientSecret"),
        pydantic.Field(alias="ClientSecret", description="Client secret generated by Directory"),
    ] = None
    """
    Client secret generated by Directory
    """

    client_uri: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="ClientUri"),
        pydantic.Field(
            alias="ClientUri", description="A compliant URI string of a web page providing information about the client"
        ),
    ] = None
    """
    A compliant URI string of a web page providing information about the client
    """

    grant_types: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="GrantTypes"), pydantic.Field(alias="GrantTypes")
    ] = None
    jwks: typing_extensions.Annotated[
        typing.Optional[typing.Dict[str, typing.Any]],
        FieldMetadata(alias="Jwks"),
        pydantic.Field(alias="Jwks", description="Client's JSON Web Key Set [RFC7517] document value"),
    ] = None
    """
    Client's JSON Web Key Set [RFC7517] document value
    """

    jwks_uri: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="JwksUri"),
        pydantic.Field(
            alias="JwksUri", description="A compliant URI string referencing the client's JSON Web Key (JWK) Set"
        ),
    ] = None
    """
    A compliant URI string referencing the client's JSON Web Key (JWK) Set
    """

    logo_uri: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="LogoUri"),
        pydantic.Field(alias="LogoUri", description="A compliant URI"),
    ] = None
    """
    A compliant URI
    """

    organisation_id: typing_extensions.Annotated[
        typing.Optional[OrganisationId], FieldMetadata(alias="OrganisationId"), pydantic.Field(alias="OrganisationId")
    ] = None
    policy_uri: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="PolicyUri"),
        pydantic.Field(
            alias="PolicyUri",
            description="A compliant URI string that points to a human-readable privacy policy document",
        ),
    ] = None
    """
    A compliant URI string that points to a human-readable privacy policy document
    """

    redirect_uris: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="RedirectUris"), pydantic.Field(alias="RedirectUris")
    ] = None
    response_types: typing_extensions.Annotated[
        typing.Optional[typing.List[str]], FieldMetadata(alias="ResponseTypes"), pydantic.Field(alias="ResponseTypes")
    ] = None
    token_endpoint_auth_method: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="TokenEndpointAuthMethod"),
        pydantic.Field(alias="TokenEndpointAuthMethod"),
    ] = None
    tos_uri: typing_extensions.Annotated[
        typing.Optional[str],
        FieldMetadata(alias="TosUri"),
        pydantic.Field(
            alias="TosUri",
            description="A compliant URI string that points to a human-readable terms of service document for the client",
        ),
    ] = None
    """
    A compliant URI string that points to a human-readable terms of service document for the client
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
