

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .connect_v1connector_tasks import ConnectV1ConnectorTasks
from .connect_v1connector_with_offsets_config import ConnectV1ConnectorWithOffsetsConfig
from .connect_v1connector_with_offsets_offsets_item import ConnectV1ConnectorWithOffsetsOffsetsItem
from .connect_v1connector_with_offsets_type import ConnectV1ConnectorWithOffsetsType


class ConnectV1ConnectorWithOffsets(UniversalBaseModel):
    name: str = pydantic.Field()
    """
    Name of the connector
    """

    config: ConnectV1ConnectorWithOffsetsConfig = pydantic.Field()
    """
    Configuration parameters for the connector. These configurations
    are the minimum set of key-value pairs which can be used to
    define how the connector connects Kafka to the external system.
    Some of these key-value pairs are common to all the connectors, such as
    connection parameters to Kafka, connector metadata, etc. The list
    of common connector configurations is as follows
    - cloud.environment
    - cloud.provider
    - connector.class
    - kafka.api.key
    - kafka.api.secret
    - kafka.endpoint
    - kafka.region
    - name
    A specific connector such as `GcsSink` would have additional
    parameters such as `gcs.bucket.name`, `flush.size`, etc.
    """

    tasks: typing.Optional[typing.List[ConnectV1ConnectorTasks]] = pydantic.Field(default=None)
    """
    List of active tasks generated by the connector
    """

    type: typing.Optional[ConnectV1ConnectorWithOffsetsType] = pydantic.Field(default=None)
    """
    Type of connector, sink or source
    """

    offsets: typing.Optional[typing.List[ConnectV1ConnectorWithOffsetsOffsetsItem]] = pydantic.Field(default=None)
    """
    Array of offsets which are categorised into partitions.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
