

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .secret import Secret


class CryptFsConfig(UniversalBaseModel):
    """
    Crypt filesystem configuration details
    """

    passphrase: typing.Optional[Secret] = pydantic.Field(default=None)
    """
    Master passphrase used to derive the per-file encryption keys. This is encryption key material, not a memorable password: it must be high-entropy and random, for example a base64-encoded random value, since the confidentiality of the stored data depends on its strength. When submitted in plain text it must pass a configurable minimum-entropy check (the "common.secret_min_entropy" setting); this is a heuristic estimate used to reject weak secrets, not a measure of cryptographic strength, so always supply key material generated by a CSPRNG. Store it safely and back it up: if it is lost, the encrypted files are permanently unrecoverable.
    """

    read_buffer_size: typing.Optional[int] = pydantic.Field(default=None)
    """
    The read buffer size, as MB, to use for downloads. 0 means no buffering, that's fine in most use cases.
    """

    write_buffer_size: typing.Optional[int] = pydantic.Field(default=None)
    """
    The write buffer size, as MB, to use for uploads. 0 means no buffering, that's fine in most use cases.
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
