

import typing

from ..core import enum

T_Result = typing.TypeVar("T_Result")


class EventProtocols(enum.StrEnum):
    """
    Protocols:
      * `SSH` - SSH commands
      * `SFTP` - SFTP protocol
      * `SCP` - SCP protocol
      * `FTP` - plain FTP and FTPES/FTPS
      * `DAV` - WebDAV
      * `HTTP` - WebClient/REST API
      * `HTTPShare` - the event is generated in a public share
      * `DataRetention` - the event is generated by a data retention check
      * `EventAction` - the event is generated by an EventManager action
      * `OIDC` - OpenID Connect
    """

    SSH = "SSH"
    SFTP = "SFTP"
    SCP = "SCP"
    FTP = "FTP"
    DAV = "DAV"
    HTTP = "HTTP"
    HTTP_SHARE = "HTTPShare"
    DATA_RETENTION = "DataRetention"
    EVENT_ACTION = "EventAction"
    OIDC = "OIDC"

    def visit(
        self,
        ssh: typing.Callable[[], T_Result],
        sftp: typing.Callable[[], T_Result],
        scp: typing.Callable[[], T_Result],
        ftp: typing.Callable[[], T_Result],
        dav: typing.Callable[[], T_Result],
        http: typing.Callable[[], T_Result],
        http_share: typing.Callable[[], T_Result],
        data_retention: typing.Callable[[], T_Result],
        event_action: typing.Callable[[], T_Result],
        oidc: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is EventProtocols.SSH:
            return ssh()
        if self is EventProtocols.SFTP:
            return sftp()
        if self is EventProtocols.SCP:
            return scp()
        if self is EventProtocols.FTP:
            return ftp()
        if self is EventProtocols.DAV:
            return dav()
        if self is EventProtocols.HTTP:
            return http()
        if self is EventProtocols.HTTP_SHARE:
            return http_share()
        if self is EventProtocols.DATA_RETENTION:
            return data_retention()
        if self is EventProtocols.EVENT_ACTION:
            return event_action()
        if self is EventProtocols.OIDC:
            return oidc()
