

import typing

import pydantic
from ..core.pydantic_utilities import IS_PYDANTIC_V2, UniversalBaseModel
from .secret import Secret


class S3Config(UniversalBaseModel):
    """
    S3 Compatible Object Storage configuration details
    """

    bucket: typing.Optional[str] = None
    region: typing.Optional[str] = None
    access_key: typing.Optional[str] = None
    access_secret: typing.Optional[Secret] = None
    sse_customer_key: typing.Optional[Secret] = pydantic.Field(default=None)
    """
    Customer-provided key for S3 server-side encryption (SSE-C). This is encryption key material, not a memorable password: it must be high-entropy and random, for example a base64-encoded random value. When submitted in plain text it must pass a configurable minimum-entropy check (the "common.secret_min_entropy" setting); this is a heuristic estimate used to reject weak secrets, not a measure of cryptographic strength, so always supply key material generated by a CSPRNG. Keep a safe backup: if this key is lost, objects encrypted with it cannot be decrypted, by SFTPGo or by AWS.
    """

    role_arn: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional IAM Role ARN to assume
    """

    session_token: typing.Optional[str] = pydantic.Field(default=None)
    """
    Optional Session token that is a part of temporary security credentials provisioned by AWS STS
    """

    endpoint: typing.Optional[str] = pydantic.Field(default=None)
    """
    optional endpoint
    """

    storage_class: typing.Optional[str] = None
    acl: typing.Optional[str] = pydantic.Field(default=None)
    """
    The canned ACL to apply to uploaded objects. Leave empty to use the default ACL. For more information and available ACLs, see here: https://docs.aws.amazon.com/AmazonS3/latest/userguide/acl-overview.html#canned-acl
    """

    upload_part_size: typing.Optional[int] = pydantic.Field(default=None)
    """
    the buffer size (in MB) to use for multipart uploads. The minimum allowed part size is 5MB, and if this value is set to zero, the default value (5MB) for the AWS SDK will be used. The minimum allowed value is 5.
    """

    upload_concurrency: typing.Optional[int] = pydantic.Field(default=None)
    """
    the number of parts to upload in parallel. If this value is set to zero, the default value (5) will be used
    """

    upload_part_max_time: typing.Optional[int] = pydantic.Field(default=None)
    """
    the maximum time allowed, in seconds, to upload a single chunk (the chunk size is defined via "upload_part_size"). 0 means no timeout
    """

    download_part_size: typing.Optional[int] = pydantic.Field(default=None)
    """
    the buffer size (in MB) to use for multipart downloads. The minimum allowed part size is 5MB, and if this value is set to zero, the default value (5MB) for the AWS SDK will be used. The minimum allowed value is 5. Ignored for partial downloads
    """

    download_concurrency: typing.Optional[int] = pydantic.Field(default=None)
    """
    the number of parts to download in parallel. If this value is set to zero, the default value (5) will be used. Ignored for partial downloads
    """

    download_part_max_time: typing.Optional[int] = pydantic.Field(default=None)
    """
    the maximum time allowed, in seconds, to download a single chunk (the chunk size is defined via "download_part_size"). 0 means no timeout. Ignored for partial downloads.
    """

    force_path_style: typing.Optional[bool] = pydantic.Field(default=None)
    """
    Set this to "true" to force the request to use path-style addressing, i.e., "http://s3.amazonaws.com/BUCKET/KEY". By default, the S3 client will use virtual hosted bucket addressing when possible ("http://BUCKET.s3.amazonaws.com/KEY")
    """

    key_prefix: typing.Optional[str] = pydantic.Field(default=None)
    """
    key_prefix is similar to a chroot directory for a local filesystem. If specified the user will only see contents that starts with this prefix and so you can restrict access to a specific virtual folder. The prefix is normalized on save: a leading "/" is removed and a trailing "/" is added; a non-empty value that resolves to the storage root is rejected. If empty the whole bucket contents will be available
    """

    if IS_PYDANTIC_V2:
        model_config: typing.ClassVar[pydantic.ConfigDict] = pydantic.ConfigDict(extra="allow", frozen=True)
    else:

        class Config:
            frozen = True
            smart_union = True
            extra = pydantic.Extra.allow
